### ISSUE TITLE
Not able to sync to Teams

### ISSUE THREAD

**Issue by Mylenesch** [OfficeDev/microsoft-teams-apps-champion-management#101]
Hi CMP team,

I followed all the steps and it worked up until the part where I had to "sync to teams". When I try this it says failed, but not further explanation. What am I missing?
<img width="937" alt="Screenshot 2022-04-28 145100" src="https://user-images.githubusercontent.com/40021297/165756048-79b6b678-dc23-4251-870a-5ec82edffcaf.png">

**Comment by v-saikirang** [comment]
Hi @Mylenesch,

Thanks for reaching out to us. Can you please clarify couple questions.

1) Are you installing the app for the first time or are you trying to upgrade from a previous version.
2) Do you see the app in Teams.
Thanks,

**Comment by Mylenesch** [comment]
Hi @v-saikirang,

1. Yes this is the first time I am installing the app. I had no previous version.
2. I can see the app in Teams, but it is very limited. I am the team owner.
<img width="596" alt="Screenshot 2022-04-28 154030" src="https://user-images.githubusercontent.com/40021297/165765685-0009d6d9-0f63-4301-80a3-a55e3a1ed63b.png">
<img width="574" alt="Screenshot 2022-04-28 154112" src="https://user-images.githubusercontent.com/40021297/165765689-eff66f8f-d4b0-4b70-bdfa-fd29769de744.png">

**Comment by v-saikirang** [comment]
Hi @Mylenesch,

Can you please check if the "ChampionManagementPlatform" site is created in sharepoint. If yes, can you please share the below 2 screenshots:
1) Site contents page
2) Members List
Thanks.

**Comment by Mylenesch** [comment]
Hi @v-saikirang,

The ChampionManagementPlatform site is indeed created. Here are the screenshots:
1. 
<img width="678" alt="site-contents-page" src="https://user-images.githubusercontent.com/40021297/165777929-c750371e-94ab-4c90-888f-8f6d2faa3e5c.png">
2. 
<img width="784" alt="memberlist" src="https://user-images.githubusercontent.com/40021297/165777969-5df73d35-5e9f-4dec-a2a5-5cfdeb7ec0af.png">
Thank you for the help!

**Comment by v-saikirang** [comment]
Thanks @Mylenesch.

In the second screenshot for your account can you change the "Status" to Approved and "Role" to "Manager" as shown below.
![image](https://user-images.githubusercontent.com/87538202/165780167-c235b31b-d660-48cf-b4d0-8dc8179f8ef7.png)

**Comment by v-saikirang** [comment]
Hi @Mylenesch,

Can you please confirm if the above solution worked for you.
Thanks.

**Comment by v-saikirang** [comment]
Hi @Mylenesch,

Thanks for confirming. Iam closing the ticket.
Thanks.
