### ISSUE TITLE
Company Communicator failed to upload CSV as Error the file is too big

### ISSUE THREAD

**Issue by MSFTHarry** [OfficeDev/microsoft-teams-apps-champion-management#104]
There is an issue from my customer that when they uploads CSV with a picture it keeps always showing below error the file is too big, but in fact even there is only one email address with the CSV, it will be failed still except remove the image.

May I know if the app counts the whole things size together here? What's the limitation.

![23ad9cd9-a2db-4020-accf-42f00b263592](https://user-images.githubusercontent.com/105835083/169196395-94caa8c1-ba1e-4262-b16e-9319a1144534.jpg)

**Comment by v-prigunasek** [comment]
Hi @MSFTHarry ,

Thanks for reporting the issue about CC application but can you please create this issue under the CC repo here - https://github.com/OfficeDev/microsoft-teams-apps-company-communicator/issues

Thanks!
