### ISSUE TITLE
Stuck in first run experience (setup in teams)

### ISSUE THREAD

**Issue by leng4ever** [OfficeDev/microsoft-teams-apps-champion-management#105]
Hi,
having issue with setting up champions management in teams.
Im at first-run-experience-add-champion-management-platform-tab-in-teams and stuck on stage 6. Only gets error:
"An unexpected error occurred while setting up the App. Please try refreshing or loading after some time"
I have tried re-innstallation with SharePoint admin and global admin without any help.

Tried the same setup in another tenant, which is working fine.
Been struggling for weeks. Uninnstalled the app, waited over weekend and reinstalled it without any help either.

**Comment by v-saikirang** [comment]
Hi @leng4ever,

Thanks for trying this app. 
Few questions:
1) Can you please check if the "ChampionManagementPlatform" site collection is created from Sharepoint Admin center.
2) If it's not in "Active Site" can you check if it's in "Deleted Sites"
3) Have you logged in to Teams with an account which has admin access.
4) Can you try opening Teams in browser and share the errors in console logs. It would be good if you can share the entire logs from console.
5) Is this a GCC tenant?

Thanks.

**Comment by leng4ever** [comment]
> 

Hi and thanks for prompt reply.

1. It does not show up as active site
2. It is not listed in deleted sites
3. Yes, i have logged in with a Global admin during whole deployment process
4. Where can i upload the .har file?
5. Not GCC tenant

**Comment by leng4ever** [comment]
[Teams Error log.zip](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/8890265/Teams.Error.log.zip)

**Comment by leng4ever** [comment]
Hi again,
i had a look at the error log and seems like it tries to access a site called /sites/champ.
I created this one manually and added champions in teams. Seems to work now :)

**Comment by v-saikirang** [comment]
Hi @leng4ever ,

May I know if you have customised the code or directly using the package file. The existing code is supposed to create and look for championmanagementplatform site unless changed in the code. Can you please check if the app is working as expected.

Thanks.
Thanks.

**Comment by leng4ever** [comment]
Hi @v-saikirang 
App seems to work (at least no error when i click on multiple icons), but since you mention the code do some customization will it have any affect when i created the SPO site manually?

**Comment by leng4ever** [comment]
![image](https://user-images.githubusercontent.com/107401139/173341135-b91f5868-d88e-4792-82f8-66927129ed33.png)
![image](https://user-images.githubusercontent.com/107401139/173341225-c285775f-b137-4702-8172-9ab9ef37fe5a.png)
Not sure which features to verify. In teams i can access all those icons and add some people.

**Comment by v-saikirang** [comment]
Hi @leng4ever,

I see that few default data is not loaded as expected. Can you please click on the Champions List icon under Admin section and share the url of the window that it opens. And can you also share the url of the site collection that you created manually.
Thanks.

**Comment by leng4ever** [comment]
> 

https://domain.sharepoint.com/sites/champ/Lists/Member%20List/AllItems.aspx
I see my account on that list..

Any reason it still look for the old site? I dont have the history of the first time the previous guy tried to install it.
First i just tried to upgrade
Then I uninstalled the app, removed the graph permission and removed it from Teams.

What is the correct way to remove everything?
Thanks

**Comment by v-saikirang** [comment]
Hi @leng4ever,

If you are fine to troubleshoot this offline please share your email. I will contact you and we can take this forward.

Thanks.

**Comment by leng4ever** [comment]
> 

Hi,
i have time 14.00 Norway time (in 5.5 hours from now) and can be reached at leng.jacobsen@fremtind.no in teams.

**Comment by v-saikirang** [comment]
Summary of the Issue Resolution:

Root Cause: The url of the sharepoint site was modified later manually causing the issues with the App. Even after deleting the site it was coming in power shell.

Resolution: Deleted the site using power shell and re set up the app. This time due to caching the logs were still pointing to old site. Tried after clearing the cache and opening new browser and the set up completed successfully.
Thanks.
