### ISSUE TITLE
Stuck loading after adding to teams

### ISSUE THREAD

**Issue by davidpat99** [OfficeDev/microsoft-teams-apps-champion-management#106]
Hi,
The page is stuck at the loading circle. Refreshing it several times has still failed.
I am in a MS test tenant if that could affect anything. Also running it on the Edge browser Version 103.0.1264.37 (Official build) (64-bit).
I can't run it in a production environment until I test it in this tenant and write a report as to it's effectiveness and features.
Happy to provide any additional information as needed.
Thanks!

**Comment by v-saikirang** [comment]
Hi @davidpat99,

Thanks for your feedback. 

Few things to check:
1) Is the site collection "championmanagementplatform" created. Please check this from Sharepoint Admin center under both "Active" and "Deleted" sections. If the site is created share a screenshot of the site contents page.
2) Can you share the console logs  from the browser when you see this error.

Thanks.

**Comment by davidpat99** [comment]
[teams.microsoft.com-1656434750696.log](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/9003071/teams.microsoft.com-1656434750696.log)

<img width="1058" alt="Screenshot 2022-06-28 104233" src="https://user-images.githubusercontent.com/38844525/176234774-32325801-8cd5-4b9b-8f50-191ba8eb9f45.png">

**Comment by v-saikirang** [comment]
Hi @davidpat99, Thanks for sharing the information . I have checked the logs and we can try few things here:

1) Can you access the SharePoint site. If yes, Can you navigate to "Site Contents" and share a screenshot.
2) Can you also navigate to "Members List" and share a screenshot.
3) Are you using the same account that you installed the app to open the app in teams as well. If not can you please try accessing the app using the admin account.

Thanks.

**Comment by davidpat99** [comment]
1. not sure which sharepoint site you meant so both the champion platform one and the one I'm trying to install it to
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/38844525/176483024-3f1476cf-850d-4843-babf-0feb351ac34f.png">
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/38844525/176483089-b64379f3-702c-493b-a8ec-46b98a5f6602.png">
2. 
<img width="1237" alt="image" src="https://user-images.githubusercontent.com/38844525/176483271-a4c92138-8789-4a13-a306-1589a08a6eb2.png">
3. Yes using the admin account, which is the same one I used to install the app

**Comment by v-saikirang** [comment]
Hi @davidpat99,

Can you please share a screenshot of the "API Access"  page from Share point Admin center as mentioned in the step 11 of the deployment guide - https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Deployment-Guide
Thanks.

**Comment by davidpat99** [comment]
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/38844525/176718538-a917cf0c-05cc-4cf6-8bee-90a1751a44d6.png">

**Comment by davidpat99** [comment]
I uninstalled and reinstalled the application, got the 3rd request.

<img width="1160" alt="image" src="https://user-images.githubusercontent.com/38844525/176723271-4d9444ba-a67b-42c7-80e6-c394bd7175ae.png">

**Comment by davidpat99** [comment]
Oh it works now, thanks! So the fix is uninstall and reinstall, then wait 1 hour after approve API access, 20 mins wasn't enough

**Comment by v-saikirang** [comment]
@davidpat99, Great! Thanks for your interest in the app and reaching out to us.

Thanks.
