### ISSUE TITLE
Suggestion: Add more control over Tournament of Teams and Champion Leaderboard

### ISSUE THREAD

**Issue by steffiyappy** [OfficeDev/microsoft-teams-apps-champion-management#108]
Hi team, 
Loving the new updates! 
I have been receiving some feedback from users on wanting to have more controls over the Tournament of Teams and Champion Leaderboard to make things a little more challenging and exciting. It is a little too easy for users to obtain points without the controls. 
Some examples:
1. Users would need to submit some proof to say that they have really completed the tournament before getting the badges. 
2. Users to get a code (after completing a challenge) from the admin/tournament setter to key in prior to obtaining the points. 
3. Being able to finish several tournaments to collect a set number of badges before collecting an ultimate badge at the end.
4. Level up badge system to see the champions' tiers. 
5. Automated workflow on approving the points. 

Hope this can be taken into consideration for the next update!
Thanks!

**Comment by v-saikirang** [comment]
Hi @steffiyappy,

Thanks for your interest in the app and sharing your feedback. 
We appreciate your suggestions and will try to consider them for our future releases.

Thanks.

**Comment by LisaJo48** [comment]
@v-saikirang Please add me to the suggested for all 5 of these. I am having to alter permissions, create Microsoft Forms and workflows to monitor and restrict badge collecting for events and tournaments to safeguard against inaccurate communication about a user's expertise or participation.
