### ISSUE TITLE
API request not appearing in 'API Access'

### ISSUE THREAD

**Issue by keefahh** [OfficeDev/microsoft-teams-apps-champion-management#109]
Hey all,

Similar to this [issue](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/issues/37), I'm not getting the _championmanagment_ app appear in the API Access page

![image](https://user-images.githubusercontent.com/99415918/179516880-6436da5c-5294-486c-befb-fc7517832491.png)

But the app does appear in the apps page 
![image](https://user-images.githubusercontent.com/99415918/179516968-0742abf5-e91a-4f96-8300-3aa7461a3bed.png)

I've tried deleting the app and reinstalling it several times, both in the classic SharePoint and modern.

I will try the older 1.2 version and report back.

Thanks in advance!

**Comment by v-saikirang** [comment]
Hi @keefahh,

Thanks for reaching out to us. Your screen shot is the expected outcome. One you approve the permissions it would not show the app name. It would show the app name only for pending requests. So you can go ahead with the set up process and let us know if you see any issues.
Thanks.

**Comment by keefahh** [comment]
Hi @v-saikirang 

Thanks for the quick reply! My should the Team/Site have been created automatically? After the API approval or is this something I should do.

**Comment by v-saikirang** [comment]
Hi @keefahh,

The share point site is created automatically. But please follow the steps from the deployment guide.
[Deployment Guide](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Deployment-Guide)

Thanks.

**Comment by v-saikirang** [comment]
Hi @keefahh,

If possible can you please share a screenshot of your API Requests page. 
Thanks.

**Comment by keefahh** [comment]
@v-saikirang 
Here we are 
![image](https://user-images.githubusercontent.com/99415918/179535551-1bb1e2a4-aba4-497d-9d38-3fbab0f1de5a.png)

**Comment by v-saikirang** [comment]
Hi @keefahh,

I see that those 2 permissions are already approved at the organisation level. So you don't have to anything here. You can proceed with other steps considering this step as complete.

Thanks.

**Comment by keefahh** [comment]
Just to confirm, in that part of the guide it says

> First Run Experience: Add Champion Management Platform Tab in Teams
> 
> NOTE: Please wait for around 20 minutes for API access approvals done in the previous section to take effect before proceeding with the below steps.
> 
>     Navigate to Microsoft teams, select the Team and channel where you want to install Champion Management Platform. 

Does this assume that the site has been created? Because I cannot find the site in our environment.

**Comment by keefahh** [comment]
@v-saikirang Thank you so much for your help! All sorted now
