### ISSUE TITLE
Teams SharePoint Error

### ISSUE THREAD

**Issue by EBogie** [OfficeDev/microsoft-teams-apps-champion-management#11]
I did not make any custom configurations and just uploaded cmp.sppkg into SharePoint Admin App Catalog and did a sync to Teams. I'm able to add the see Champion Management Platform in my Teams tab, but it doesn't load fully. 

Not sure if the error is Teams or SharePoint?

Thank you for any help you can provide. 

![ErrorMessage](https://user-images.githubusercontent.com/82591576/114875914-c8ef9b00-9dcb-11eb-8c7e-6e97b1ce9452.png)

**Comment by johnravas** [comment]
I recently installed this in my development tenant.  This screen works perfectly fine for the admin account, but I see the exact same thing when I test with an account that is a champion.  I just downloaded and installed the SharePoint package as is.  Any help would be appreciated.

**Comment by saurabhjatara** [comment]
I have the same issue.

**Comment by saurabhjatara** [comment]
It worked for me this time, I made the mistake of creating the SharePoint site.

**Comment by EBogie** [comment]
@saurabhjatara,

Thank for the post and update. I'm not sure I follow what you mean by "I made the mistake of creating the SharePoint site.". Can you provide more details so I can understand what I might have missed?

Thank you so much for the help.

**Comment by saurabhjatara** [comment]
@VesaJuvonen 
1> Don't create a site "ChampionManagementPlatform" manually, and if you already did delete that from the tenant and deleted sites.
2> Don't Pin the app in the left panel instead add it in the Teams tab.
Follow this video step by step 
https://www.youtube.com/watch?v=t16pUbR0ljg

**Comment by Smitat-msft** [comment]
@johnravas @EBogie @saurabhjatara Thanks for being patient. We triaged this issue and I will get back on this.

**Comment by eshwarmsft** [comment]
This issue we are able to reproduce when the ChampionLeaderBoard site is not deleted from active sharepoint sites and Deleted Sites.

Also should make sure the MemberList Sharepoint list to be deleted from Parent or Main Sharepoint site and from the respective site recycle bin. Please let us know if you still see after doing these steps.

**Comment by johnravas** [comment]
@eshwarmsft Thank you for the updates.  I want to be sure that I understand the next steps correctly.  I didn't manually create the "championmanagementplatform" manually.  It was created as part of the process to set up the CMP.  Are you saying that I should delete this site?  Also, I noticed that the member list was on the root/main site in the tenant, which didn't make much sense to me.  Are you saying that I should delete it too?  Is there anything that I need to do with the SharePoint package itself?  Is there any kind of update?  The version that I have installed is version 1.0.0.0.  Thank you for your assistance with this issue.

**Comment by EBogie** [comment]
@johnravas  - Thanks for posting the clarification request. I tried to work on this, this morning and haven't made any headway. I'm a SharePoint newbie, so I don't know much about the backend changes. I can see that the Champion Management Platform is in the "deleted sites" area. 

@eshwarmsft - I like @johnravas didn't create Champion Management Platform manually. Just completed the import process from step 9.
https://github.com/OfficeDev/microsoft-teams-apps-champion-management#deploy-your-package-to-sharepoint
9. Click the ***Choose Files*** button, select the ***cmp.sppkg*** file you downloaded or created earlier, and click on ***OK***

**Comment by eshwarmsft** [comment]
Hi @johnravas , Thanks for your patience and following the readme steps. Would you please check the group has contribute access 
![image](https://user-images.githubusercontent.com/69787520/116867916-76b3d400-ac2b-11eb-943a-a824f44d3523.png) Also. If it still not resolves, Would prefer having detailed steps followed from scratch or screenshare session to better assist you.

**Comment by johnravas** [comment]
@eshwarmsft I double checked the permission for the Member List.  Inheritance is broken and the site members group has edit access (one step above Contribute).  Here is a screenshot:
![image](https://user-images.githubusercontent.com/59970962/116916369-39dfe100-ac1b-11eb-820a-ec15a9afcfe3.png)
You can also see the Everyone Except External has edit access to the list.  The members group contains the 2 users that I have been using for testing.

If you have time for a screenshare, it might help to get the to bottom of this issue more quickly.  Thanks for all of your help.

**Comment by eshwarmsft** [comment]
Hi @johnravas 

Would you please provide end to end steps in line again or try to create the setup by seeing the readme file again as there are other users who can be able to set up following the same.

**Comment by johnravas** [comment]
@eshwarmsft - I would prefer not to do a full re-install, but here is what I can tell you about the process/config and an anomoly:

- Downloaded the standard cmp.sppkg file - dated 4/12/2021
- Added to the App Catalog where it shows as version 1.0.0.0 - Tenant deployed = Yes
- Went to the SharePoint Admin center Advanced/API Access and approved all pending requests
- Then clicked the Sync to Teams button
- In one of my MS Teams, I added a Champions Management Platform channel and added the tab - which is available to all users, even though it does not work for all
- In my ChampionManagementPlatform site collection - Shared the site with Edit access to Everyone except external.  This put that entry in the members site group.  As part of my testing I took 2 of my users and added them to the Owners group.
- In the root site, where the Member list lives, 2 of my test users are in the members group.
- The Member List has unique permissions where Everyone except external has edit access
This should cover the install process.  Now here is the worst part of all of this, my 2 real users have the issue where the Teams tab does not load and just spins.  I have an additional test user, which I switch back and forth with - it does work for this user!

None of these users are tenant admins.  If anything the 2 real users have more permissions to the components:

- The team that has the channel and tab - the 2 real users are owners.  The test user is a member
- The CMP site collection - the 2 real users are owners, the test user is a member
- For the Member List - all users have the same edit access

Hopefully, this will give you some insight as to how this is set up.  If you truly want me to start fresh this would require me to delete the CMP site collection, delete the Member List, delete the SharePoint package and start again.  I am not sure if there would be anything residual from the API access or Teams sync.

Please advise.

**Comment by florianviertel** [comment]
@johnravas
Even if it might not help: In the Teams Admin Center, make both owners members and then owners again.
I had several times the situation that tabs in Teams did not work properly for owners without having done this step at least once.

**Comment by eshwarmsft** [comment]
@johnravas  @EBogie  Thanks for your update and Would you also give a try by trying to access the app as a personal app from Teams--> Apps --> Search for Champions Management Platform and provide your update
![image](https://user-images.githubusercontent.com/69787520/117818212-04c03800-b286-11eb-8520-1def7c76804b.png)
![image](https://user-images.githubusercontent.com/69787520/117818271-10abfa00-b286-11eb-81fa-1cea7df65200.png)

**Comment by eshwarmsft** [comment]
Thanks you @johnravas  Will get the fix soon

**Comment by eshwarmsft** [comment]
Recent update Champions Management Portal 1.1.0.0 fixed this issue

**Comment by EBogie** [comment]
@eshwarmsft and @johnravas 

I downloaded the newest file and still getting the same thing. Did you have to take any additional steps\changes?

![image](https://user-images.githubusercontent.com/82591576/119676922-43203000-be0c-11eb-8175-bee0a5144a3a.png)

**Comment by johnravas** [comment]
@EBogie & @eshwarmsft - I'll download and install in my Dev tenant to test.  Thanks for the update

**Comment by johnravas** [comment]
@eshwarmsft & @EBogie - I installed this updates sppkg file in my Dev tenant today.  No luck.  Here is the process that I followed for the update:

- Went to the App Catalog and installed the newer sppkg file for the entire tenant - now version 1.1.0.0
- Checked the Admin Center, API access - no requests pending
- App Catalog selected sppkg file and clicked Sync to Teams on tool bar

Is there anything else that I should be doing to ensure that the update is fully installed?

**Comment by say-brad** [comment]
I installed the CMP application but the functions of add members are not visible, I deleted the site and app but reinstalling its not creating the SharePoint site, old site was in recycle bin and I deleted it today, now it says sync to teams failed and also new site is not created, the application does import success, but no permissions are asked and none other steps work. If I should create a new thread for the issue let me know.

**Comment by v-saikirang** [comment]
Hi @EBogie, @say-brad, @johnravas, 

 Thanks for your patience! We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by say-brad** [comment]
Hello,

Do you have specific steps for uninstall please?
Should I delete the SharePoint site, Teams App, is there an order to follow ?

Regards,
Sayee

**Comment by v-saikirang** [comment]
Hi @say-brad,

Please refer to the section "Upgrade to version 1.2.0.0" in the ReadMe document [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/blob/main/README.md#upgrade-to-version-1200). Make sure you wait for around 15 minutes after step 4 and then continue with step 5. Please let me know if you see any issues along with screenshots if any.

**Comment by JoshLeporati** [comment]
@say-brad - please let us know in issues if you had any further questions post the uninstall directions noted earlier by Sai, will be closing issue for now
