### ISSUE TITLE
Digital Badge

### ISSUE THREAD

**Issue by Cronekel** [OfficeDev/microsoft-teams-apps-champion-management#111]
One of my Champions is having issues loading her digital badge. Do you have any suggestions on how to fix this? She said it's not updating  and showing up dark and hard to read?

**Comment by v-prigunasek** [comment]
Hi @Cronekel ,

Thanks for reaching out to us here. 
Could you please check with the user whether She is using the Dark Mode theme on the Teams application? If not, please open the CMP application in the browser version of teams and send us the console logs from browser and also share us the screenshot of the digital badge screen to get a better idea on the image issue.

Thanks!

**Comment by Cronekel** [comment]
Hey there, I apologize for my delayed response.
My issue resolved itself the next day. The digital badges appeared for the users. Thanks for following up!

From: v-prigunasek ***@***.***>
Sent: Friday, August 5, 2022 12:12 AM
To: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Crone, Kelly N ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [OfficeDev/microsoft-teams-apps-champion-management] Digital Badge (Issue #111)

CAUTION:This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Hi @Cronekel<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCronekel&data=05%7C01%7CKelly.n.crone%40conocophillips.com%7C2dec5e40d54a4be7de4f08da76a10577%7Cb449db5ea80a48eba4c23c88bb78353b%7C0%7C0%7C637952731215159626%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Wrkas%2BYsTQ7Uxh6NOXN%2BUb4y8OHub2pDEAqkDi9NLxM%3D&reserved=0> ,

Thanks for reaching out to us here.
Could you please check with the user whether She is using the Dark Mode theme on the Teams application? If not, please open the CMP application in the browser version of teams and send us the console logs from browser and also share us the screenshot of the digital badge screen to get a better idea on the image issue.

Thanks!

-
