### ISSUE TITLE
Multiple instances of the CMP in the same Sharepoint tenant?

### ISSUE THREAD

**Issue by PhantomMenace25** [OfficeDev/microsoft-teams-apps-champion-management#114]
Hello, 

We are attempting to install a second instance of the CMP for a different functionality within the same Sharepoint tenant. 

I have followed the customization steps to repackage the product after changing the Sharepoint site location and logo files. However, when I attempt to upload to Sharepoint Apps, I am met with the following error: 

![image](https://user-images.githubusercontent.com/111144866/184417195-f72aa3d5-628d-4db1-96d4-d650433918e8.png)

Is there something in the configuration that can be edited to alter the package ID so that two instances of this product can exist in the same environment?

Thank you!

**Comment by v-saikirang** [comment]
Hi @PhantomMenace25,

Thanks for reaching out to us.

It's not straight forward to deploy a second instance of the same web part in a tenant. Please refer to this article:https://www.c-sharpcorner.com/article/deploy-multiple-instance-of-spfx-webpart-in-same-app-catalog/

Apart from the above steps there are couple other steps tat you need to perform.
1) Modify the ID in the manifest.json under "Teams" folder with the same ID as the one in CLBHomeWebPart.manifest.json.
2) Delete the "TeamsSPFXApp.zip" and re generate a new one with the manifest and 2 image files under "Teams" folder. This zip should only have 2 files and no nested folders.
3) Modify the "sitename" property in the siteconfig.json under "config" folder. This will create a new sharepoint site to avoid conflicts with existing site.
4) After making all the changes re generate the package and try deploying again.

Please let us know if you need additional information.
Thanks.

**Comment by v-saikirang** [comment]
Hi @PhantomMenace25,

I just to highlight one more point here. Once you have customized version of the app any further upgrades to the app released in git hub will not automatically pass over to your custom installed version. All the upgrades to the code will have to be manually copied over and maintained by your team. Please consider this if you are planning for a custom version.

Please let me know if you need more information. Else we would like to close this ticket in next 2 days.
Thanks.

**Comment by PhantomMenace25** [comment]
Thank you for your assistance with this issue and mentioning the above considerations.

You can go ahead and close out the request.

Thanks!

**Comment by v-saikirang** [comment]
Thanks for your confirmation. Closing out this ticket.
