### ISSUE TITLE
unable to SyncToTeams

### ISSUE THREAD

**Issue by QuintenPXS** [OfficeDev/microsoft-teams-apps-champion-management#115]
Hello
We are trying to deploy this solution on our UAT test environment.
At the step where we need to press SyncToTeams we get an error.
'could't add app to Teams - Check your network connection and try agian'
![image](https://user-images.githubusercontent.com/86714660/185415954-0ed2e5e4-8554-4483-9acf-b3bdbde16f79.png)
[proximuscorpuat.sharepoint.com.zip](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/9374555/proximuscorpuat.sharepoint.com.zip)

Attached you find screenshot of the error & HAR file of the action.

I tested on VM connected straight on our UAT network.
Also from within seperated browser profile on PRD computer.
Both environments give the same error.

Any feedback on this?

Quite possible it is network/firewall/proxy related. not sure

![image](https://user-images.githubusercontent.com/86714660/185416465-8f554c3b-a921-4197-afec-bf80defd0589.png)

**Comment by v-saikirang** [comment]
Hi @QuintenPXS,

Thanks for trying out this app. Can you please confirm on few questions:

1) Is this the first time that you are installing this app in this tenant
2) Can you search under "Apps" in teams to see if you can find "champion management platform" app.
3) Can you search under "Manage Apps" section in the Teams Admin center(https://admin.teams.microsoft.com) to see if you can find the app there.
Thanks,
Sai.

**Comment by QuintenPXS** [comment]
hi there,

I checked again today and now can find the Champions app.
Seems like issue was related to our test tenant or Teams / sharepoint admin center was bugging out.

The app was now succesfully added to a Team and is working.

Thanks! !
