### ISSUE TITLE
Which are the current supported languages?

### ISSUE THREAD

**Issue by JorgeALeitao** [OfficeDev/microsoft-teams-apps-champion-management#118]
Release notes for v2.3 says:
New Feature: Local language support (translations) available for 12 languages.
https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Release-Notes#23-jul-28-2022

However, it doesn't state which languages are supported.

@Porkai-Pandian, could you please clarify?

Thanks!

**Comment by Porkai-Pandian** [comment]
@JorgeALeitao please check the FAQ section to know more about the languages supported,

https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Frequently-Asked-Questions-(FAQ)#4-does-the-app-support-multiple-locales

**Comment by JorgeALeitao** [comment]
Brilliant, thanks a lot!
