### ISSUE TITLE
Install on GCC or Higher

### ISSUE THREAD

**Issue by gregtrumpfheller** [OfficeDev/microsoft-teams-apps-champion-management#12]
When attempting to install on GCC Tenant the backend SP Site and associated lists are not created.

**Comment by karuanag** [comment]
@JoshLeporati  We tested on GCC so lets redo testing and get any information from @gregtrumpfheller  to allow our troubleshooting.

**Comment by eshwarmsft** [comment]
Hi @JoshLeporati  Would you please provide more information.

1. Whether site created?
2. Sharepoint list at parent site created [memberlist]
3. Sharepoint list at ChampionLeaderBoard created
4. Meanwhile will also validate on the gcc tenant if you could provide it would be great help.

**Comment by JoshLeporati** [comment]
Hi @eshwarmsft - from your notes,
1. yes site was created
2. correct, memberlist created at parent site
3. correct, eventlist and eventtrackdetails created from championleaderboard

All three of those actions will not occur until the first run of the app once it's loaded into a team. You were able to get it added to SP App catalog, and then load into a team and on first run, none of the above assets created for you in your GCC environment? I'm running again but my last load all of the above actions happened correctly.

**Comment by JoshLeporati** [comment]
@eshwarmsft on second reload I've confirmed that assets load as expected. This is being completed in my GCC tenant. 

Again, assets (the SP site and associated lists) were not created until after the first run experience of loading the app into a team and opening it. 

Please let me know if that step was completed and if you still have issues with the assets loading!

**Comment by JoshLeporati** [comment]
@gregtrumpfheller tagging here for your awareness as well. When you loaded the solution in, the assets (should) create after the first run experience. Can you confirm that you ran the app for the first time and that even after that first run, no assets were created? If YES - did the platform show the expected shortcuts on the screen as well (Leaderboard / Add Member / Digital Badge) or did it perhaps just show Leaderboard?

Thanks in advance!

**Comment by gregtrumpfheller** [comment]
The Events asset were created, but the member's list did not.  The only icon that showed in the Teams App was the leader board, but it didn't link to anything in the site.

I am deleting all and restarting install/creation validate install.

Thank you!
--
Greg Trumpfheller
Customer Engineer
***@***.***D73C46.B70D2BF0]
***@***.***D73C46.B70D2BF0]
[Microsoft]
Office: (980) 776-7056
***@***.******@***.***%0d>
8 AM - 5 PM (Eastern)

Chat with me on ***@***.***>
Find a time to ***@***.***>

**Comment by gregtrumpfheller** [comment]
I removed all remnants of the install by removing any API Access, removing from the App Catalog, and deleting the partial site that was created.  I also had to clear the old site from the deleted sites area, and waited 24 hours before retrying to install.  Reinstalled with no issues.

**Comment by JoshLeporati** [comment]
thanks for confirming Greg!
