### ISSUE TITLE
Getting error with 'Add to Teams' option

### ISSUE THREAD

**Issue by kkarra3** [OfficeDev/microsoft-teams-apps-champion-management#120]
Hi

I have uploaded the package to the SharePoint App Catalog and enabled it and approved all the permissions. When I try to 'Add to Teams' I keep getting the below error (Couldn't add app to Teams, check you network connection and try again). I have no issues with the network and I have tried multiple times. I have even deleted the app and reuploaded it with the same result. Anyone had this issue and have a workaround?

![image](https://user-images.githubusercontent.com/36901686/190685736-e81e668c-c82c-479e-bac8-e6e45a443d06.png)

**Comment by v-saikirang** [comment]
Hi @kkarra3,

Thanks for reaching out to us. May I know if this is a new installation or if this is an upgrade.

Usually this error pops up when you have have the app deployed already. But since you mentioned you tried deleting the app it could be a temporary glitch in Teams Admin center. You can check back after some time.
In any case this issue is not specific to the App itself. Please let me know how this works out.
Thanks.

**Comment by kkarra3** [comment]
Thanks for the quick response. It's a new installation. I could now successfully add the app to teams after multiple attempts. 
Now, when I try to add the app in a teams channel I get 'This app cannot be found' error. I verified that the app is visible in the teams admin center-->Manage Apps and it's status is 'Allowed' . Any ideas here?

![image](https://user-images.githubusercontent.com/36901686/190708481-84c091a6-c3b2-4192-af84-49ab0a80da22.png)

**Comment by v-saikirang** [comment]
Hi @kkarra3,

May I know if you are using a demo tenant(on.microsoft.com)?

Instead of adding it to a teams try to set up the app first by opening it from the "Apps" section in teams. It could also be caching issues which usually gets cleared with time. Please try in a new browser after few hours.

Thanks.

**Comment by kkarra3** [comment]
Hi

Ours is not a demo tenant, it's a prod tenant. As you mentioned, it could have been a cache issue as I could now install and add the app to a team.

However, I am getting the below 'spinning wheel' forever. My colleague tried it on a different team channel with the same result.

![image](https://user-images.githubusercontent.com/36901686/191364891-99ab713d-30f8-4a87-95cd-2a485e71e991.png)

**Comment by v-saikirang** [comment]
Hi @kkarra3,

Can you please provide the below information:

1) Screenshot of the API permissions from SP Admin center
2) Have you tried opening the app with an admin account. If not please try opening the app with a SP admin account.
3) Can you check if site collection "championmanagementplatform" is created. If yes, can you share a screenshot of the Site contents page of the site.
4) If you are still facing the issue please open the app in chrome browser and share the console logs.
Thanks.

**Comment by kkarra3** [comment]
I am attaching the screenshots for both API permissions & the site collection site contents page. 
I did try to open the app as a SP admin.
I will send the chrome browser logs shortly.

![image](https://user-images.githubusercontent.com/36901686/191590335-55e8556b-1923-4f3f-ac51-9c52820b824d.png)

![image](https://user-images.githubusercontent.com/36901686/191590383-3d16078d-fabd-4993-980f-f90466919284.png)

**Comment by v-saikirang** [comment]
Hi @kkarra3,
Thanks for the screenshots. Please share the console logs.
Thanks,

**Comment by timokock** [comment]
Hi, I´m facing same issue. Working on a demo tenant and Edge browser. I´m not able to sync to Teams. Tried out in both views classic/modern.
![image](https://user-images.githubusercontent.com/24475382/191776248-147a8615-01f1-4241-89aa-227128d3ce6a.png)

**Comment by kkarra3** [comment]
Please find console log attached.

[champion-error.txt](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/9636131/champion-error.txt)

**Comment by v-saikirang** [comment]
Hi @kkarra3,

Thanks for sharing the console logs. I see 403 forbidden errors in the console logs. I have not seen this errors before.

Can you please check couple things here:
1) Can you add your self as site collection admin to the share point app and try opening the app again.
2) Can you also try accessing this URL in the browser and share a screenshot.

https://<<your tenant>>.sharepoint.com/sites/ChampionManagementPlatform/_api/web/lists/ 

Thanks.

**Comment by v-saikirang** [comment]
Hi @kkarra3,

No, it's not required for anyone else to be added as SCA. You just need to provide them contribute access to the site. 

I will go ahead and close the ticket for now. Please let me know if you need more information.

Thanks.
