### ISSUE TITLE
Failed to sync to Teams

### ISSUE THREAD

**Issue by timokock** [OfficeDev/microsoft-teams-apps-champion-management#123]
Hi,

After following the Deployment Guide provided in the repository, everything has worked fine until the step you have to sync to Teams. There comes always a banner "Failed to sync to Teams".
![image](https://user-images.githubusercontent.com/24475382/191778570-0749a362-0220-47a2-9f14-5f2b4982bc89.png)

I´ve tried out in both views: classic/modern.

All API Accesses are approved.
![image](https://user-images.githubusercontent.com/24475382/191778881-9e2e7405-6d2a-4f82-8839-e342531e21e1.png)

Tried out to uninstall the app, removing it from Recylce Bin, but it has the same behavior after a new fresh installation.

Thank you,
BR,
Timo

**Comment by v-saikirang** [comment]
Hi @timokock,

Can you please check if you can see the app under Manage Apps in teams admin center. If you see it there try opening a new browser and open teams to see if the app shows up.

Can you also share a screenshot of the error from modern app catalog.

Thanks.

**Comment by timokock** [comment]
Hi,

Thank you for your quick reply ;)

App is not shown in Manage Apps in the Teams Admin Center.

![image](https://user-images.githubusercontent.com/24475382/191781041-ca946ec1-71fe-4e3f-bdc0-4cbc913ea6e2.png)

![image](https://user-images.githubusercontent.com/24475382/191781412-3178169f-ac2e-4173-87ac-5c4a9291f6b2.png)

**Comment by v-saikirang** [comment]
Hi @timokock,

This should be a glitch from admin center and not specific to the CMP app. Please try after few hours and share console logs if you still get the error.
Thanks.

**Comment by timokock** [comment]
Thank you, one more thing, how can I get the console logs?

**Comment by timokock** [comment]
Hi, just tried hours later and same behavior. Can´t find the way to get console logs.

**Comment by v-saikirang** [comment]
Hi @timokock,

Please let me know if you are available for a Teams Call so we could try to check this issue over a call. If yes, Please share your availability and email id. I am available during 10:00 AM - 7:00 PM IST. We can work out on a suitable time for both us.
Thanks.

**Comment by timokock** [comment]
I´m available during 10:00 AM - 5 PM

I´ve found this:
{
    "error": {
        "code": "-1, System.Net.WebException",
        "message": "The remote server returned an error: (409) Conflict."
    }
}

**Comment by timokock** [comment]
![image](https://user-images.githubusercontent.com/24475382/192225586-672df106-5b36-4f0e-bc93-853f481db268.png)

**Comment by v-saikirang** [comment]
Hi @timokock,

Below are the observations as per our Teams call:
1) The app was already showing up in Teams Admin center. This is the reason you see an error when you are trying to "Add to Teams". This is expected behavior. 
2) We have set up the app in Teams successfully and you were able to see the CMP dashboard.

Thanks for your interest in the app and reach out to us if you have any questions/issues.
