### ISSUE TITLE
Clash Version after updated

### ISSUE THREAD

**Issue by ZulhilmiAhmad** [OfficeDev/microsoft-teams-apps-champion-management#125]
Hi Support team,

Our org tried to update the version from 2.2 to 2.3, somehow in the Manage App-SharePoint Admin Centre showed it's completed and success. But when user open the CMP, still showed Version 2.2 and the icon doesn't appear. Please advice. Appreciate it.

Thanks,

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/62020061/192933893-47b500e3-e781-4c50-9966-67cc8b3335e3.png)

![MicrosoftTeams-image V2 3](https://user-images.githubusercontent.com/62020061/192934250-a792e6a4-5f06-4aa2-9a82-f837f6991ca2.png)

**Comment by v-saikirang** [comment]
Hi @ZulhilmiAhmad,

Thanks for reaching out to us.

In most cases it should be the cache. Can you please open teams in an incognito browser and check once.
Thanks.

**Comment by ZulhilmiAhmad** [comment]
Hi @v-saikirang 

Thanks for your prompt response. Fyi, the screenshot I've captured above from private mode in Edge Browser.
<img width="957" alt="Logo dont appear" src="https://user-images.githubusercontent.com/62020061/192936533-41242ee3-f7c6-46ca-b043-2acbf5047dda.png">

**Comment by v-saikirang** [comment]
Hi @ZulhilmiAhmad,

Thanks for the screenshot. Please wait for 15 minutes and try open a new browser.

Can you also please share a screenshot of the Site Contents page from the SharePoint site.
Thanks.

**Comment by ZulhilmiAhmad** [comment]
Hi @v-saikirang 

Wait and open with a new browser still the same.

Please refer to attached image
<img width="831" alt="CMP SharePoint Site" src="https://user-images.githubusercontent.com/62020061/192938369-e2f69bdf-6896-45d1-9211-7bf2298c3a43.png">

**Comment by ZulhilmiAhmad** [comment]
Can you also confirm if you have clicked on Add to Teams from App catalog after you have replaced the package. - **We have done, and wait for 15mins, refresh, result still the same.**

**Comment by ZulhilmiAhmad** [comment]
From our end user experience, the platform keep on loading. Already tested about 2hours ago.

<img width="952" alt="EU Experience_Buffering" src="https://user-images.githubusercontent.com/62020061/192939028-7447dc91-7e4e-4d38-85f6-85e34a9a4054.png">

**Comment by v-saikirang** [comment]
Hi @ZulhilmiAhmad,

Can you please click on Site Contents and share a screenshot.
![image](https://user-images.githubusercontent.com/87538202/192943401-2c54fb96-9f90-4173-ad1b-0eb8a88f9594.png)
 And can you please try this once incognito chrome browser and check.
 If it still doesn't work we can work on this over a Teams call.
Thanks.

**Comment by ZulhilmiAhmad** [comment]
Hi @v-saikirang 

Sorry for the delay. what time you're available to do a call. We in Malaysia, UTC+8

**Comment by v-saikirang** [comment]
Hi,

I am available now. Please share your Email. I will send out a meeting invite and we can work on suitable time if needed.

Thanks,
Sai.

**Comment by ZulhilmiAhmad** [comment]
Hi Sai,

Here our email, appreciate to include my team too in the call.
matthew.bok@kenfil.com.my
zulhilmi.ahmad@kenfil.com.my
arif@midf.com.my

**Comment by ZulhilmiAhmad** [comment]
Thanks Sai for the support.

**Comment by v-saikirang** [comment]
Hi @ZulhilmiAhmad,

As per our Teams call below are the observations:

1) Admin is able to see the CMP dashboard but not other users. After providing them access on SP site and adding as a member in the app it showed up as per expected.
2) The version of the APP is showing as 2.2 in Teams app store and Teams admin center. We have deleted the app from Teams Admin center and 2.3 showed up immediately.
3) The 2.3 version got reflected in few places. Suggested that clearing the cache and reopening after some time should reflect the correct version number everywhere.
Thanks for your interest in the app.
