### ISSUE TITLE
App Not Loading for standard users

### ISSUE THREAD

**Issue by PhantomMenace25** [OfficeDev/microsoft-teams-apps-champion-management#126]
Hello,

We are currently having an issue with our implementation of the CMP where the home page of the app just sits and loads indefinitely. 

However, this is only occurring for certain users and it appears to be only the "Champion" users. For any "Manager" users the app loads with no issue. I have referred to other previously submitted questions with a similar issue and noticed most were related to the site.manage.all API permission. 

I have verified that that permission is enabled. We have already had this product deployed and available to our users for some time but since the Admin view is working with no issue, we were only just made aware that the standard users were have this issue. 

Any assistance in other troubleshooting steps would be greatly appreciated!
![2022-09-30 09_08_08-Window](https://user-images.githubusercontent.com/111144866/193312269-0c4ead9a-ae9f-4219-b30c-ffd87310911d.png)

**Comment by v-saikirang** [comment]
Hi @PhantomMenace25,

Thanks for reaching out to us.

Can you please confirm if you have given access to the other people to the SharePoint site as mentioned in the deployment guide.
You need to add them to the Members group to be able to access the app. Please check and let us know if that works.
Thanks.

**Comment by PhantomMenace25** [comment]
That was the issue! Thank you @v-saikirang for the assistance. I must've glazed over that step in the deployment guide...

Thanks again!
