### ISSUE TITLE
The tab won't load in Teams without error

### ISSUE THREAD

**Issue by aps-gilberts** [OfficeDev/microsoft-teams-apps-champion-management#129]
Attempting to add the tab to a team channel results in an error:
![221013 Champion Management Error](https://user-images.githubusercontent.com/102178910/195619572-09636fd0-addd-4010-96f0-66fa60f4e83d.png)

**Comment by v-royavinash** [comment]
@aps-gilberts Thanks for reaching out. We are analyzing the issue and will get back to you for further details to troubleshoot the issue better.

**Comment by v-saikirang** [comment]
Hi @aps-gilberts,
Can you please share the below information so we can troubleshoot the issue:
1) Screenshot of the "Site Contents" page of the "championmanagementplatform" sharepoint site collection.
2) screen shot of the contents of  "Members List" list created in the Sharepoint site.
Thanks.

**Comment by aps-gilberts** [comment]
Screenshots as requested


Andrew Sowden


________________________________

**Comment by v-saikirang** [comment]
Hi @aps-gilberts,
For some reason I cannot see the screenshots. Can you please repost the screenshots directly from git hub.

Thanks.

**Comment by aps-gilberts** [comment]
![221017 Member List](https://user-images.githubusercontent.com/102178910/196145512-fb43b930-c9fb-4e17-ae28-dd49cd94a91b.png)
![221017 Site Contents](https://user-images.githubusercontent.com/102178910/196145530-5122f183-b5f2-495f-8a8d-1b27a488163a.png)

**Comment by v-saikirang** [comment]
Hi @aps-gilberts,

Thanks for the screenshots. I see that the lists got created fine but the list items are missing. It could be due to missing graph permission "Sites.Manage.All". Can you please share a screenshot of the API Permissions page from the SharePoint Admin center.
Thanks.

**Comment by aps-gilberts** [comment]
![221071 API Access](https://user-images.githubusercontent.com/102178910/196157756-eaaa93db-5007-40fb-9f97-890d5a9b5723.png)

A "not very helpful" screen shot (!)

**Comment by v-saikirang** [comment]
Hi @aps-gilberts,

This helps. I see that you already have the permission required. 

Can you please try deleting the "Member List" and open the app as personal from "Apps" section in Teams browser. Please let me know if you still see the same error message and if the list got created again in the SP site.

Thanks.

**Comment by aps-gilberts** [comment]
Hi

That worked - the list was recreated and I've managed to add some colleagues to the App; and the App to a tab within a team channel

Thanks for your help

**Comment by v-saikirang** [comment]
Hi @aps-gilberts,

That's great. I assume it didn't create the default entries in the "Events List". On a safer side just to make sure it created all the columns and default list items correctly you can try deleting the 3 lists "Member List", "Events List", "Event Track list" and refresh so it would create all the 3 lists correctly along with default list items.

Please let me know if you need additional help. Else I can close the ticket.
Thanks.

**Comment by aps-gilberts** [comment]
I deleted the three lists and when opening the App within Teams it recreated them again.

I did notice this SharePoint Alert from Microsoft that may have had an impact: https://admin.microsoft.com/AdminPortal/home#/servicehealth/:/alerts/SP447295

It all appears to be working again and this issue may be closed.
