### ISSUE TITLE
Champion Leader Board page not loading in team tab context

### ISSUE THREAD

**Issue by yhabersaat** [OfficeDev/microsoft-teams-apps-champion-management#13]
The Champion Leader Board page isn't loading in a team tab context (blank page).

![image](https://user-images.githubusercontent.com/15676985/115194865-5265dc80-a0ee-11eb-89c4-2f30334fff65.png)

**Comment by Smitat-msft** [comment]
@yhabersaat - We triaged this issue, it could be the permissions on the initial load. I'll try to repro on my end and get back to you.

**Comment by eshwarmsft** [comment]
This issue require more information with steps to reproduce like

1. Sharepoint site created ?
2. Sharepoint list created?
3. Is the white page  coming for first time logged in user who will be responsible for creating the lists or the other teams user who requested the champions
4. If a team member tried, Then on which case this white page has appear

**Comment by yhabersaat** [comment]
I've recreated the tab in the team and now everything is working well!

**Comment by Smitat-msft** [comment]
Thanks @yhabersaat for confirming. Closing this issue as resolved.
