### ISSUE TITLE
Option to remove badge in profile

### ISSUE THREAD

**Issue by NatNat2** [OfficeDev/microsoft-teams-apps-champion-management#130]
Hi, checking into the badges, there is an "apply badge" option but there is no "remove badge" option. Would it be possible to add/include it?
<img width="218" alt="image" src="https://user-images.githubusercontent.com/115982414/196132387-5a497a1d-9b81-4baa-9cdc-fa2581d5b796.png">

**Comment by v-saikirang** [comment]
Hi @NatNat2,

Thanks for your interest in the app.

As per your screenshot, at that stage the profile picture is not yet applied. So if you don't want to apply you can just navigate away from this screen without clicking "Apply image". But if you want to apply another badge then you can navigate back to Digital Badge and start over.
Please let me know if you need more information.
Thanks.

**Comment by NatNat2** [comment]
Hi @v-saikirang,
Thanks for the prompt reply and I agree with you on this. I am actually referring to "after" the user already applied the badge and decided to remove it afterwards. As I was navigating, the only option to remove the badge is to re-upload your profile picture. Hope this clears out my query.

**Comment by v-saikirang** [comment]
Hi @v-saikirang,
Yes, as of now the only option is to re upload your original picture through office 365. This ides around this component is only to apply a badge on tour profile picture. If you want to change it to anything else I am afraid you have to do it through office 365. But we would definitely assess this if possible for our future releases. Thanks for your feedback.
Please let me know if you need more information.
Thanks.

**Comment by LisaJo48** [comment]
Thank you @NatNat2 . I have the same concern and suggestion.  @v-saikirang please include me in the feedback/feature request for this.

**Comment by LisaJo48** [comment]
Related question: when a champion wants to change his current 'C' badge to a different one (ie. from tournaments), what is happening, to the saved profile image? Is it being replaced or is the original badge 'overlay' being replaced with the new one?

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Thanks for reaching out to us.

Digital Badge will always replace your existing office 365 profile picture. So if you already had a badge applied on your profile picture the new badge will also be applied on top of your existing picture. This app does not save any profile pictures anywhere. We always get your current Office 365 profile picture and apply the badge on top of it.

If you want a copy of your current picture you can click on "Download" so you may use it back as needed. For any direct changes to your profile picture you can use Office 365 profile settings page.

Please let me know if you need more information.

Thanks.

**Comment by LisaJo48** [comment]
OK, so if my current profile picture now includes the C for champion (so much so that to remove it I have to upload a completely new image file via Delve, for example), are you saying the Photo_Frame_Booked.png badge is added to that modified version of my profile picture to create yet another version of my profile picture or does it replace the one that had the C badge added to it? Does my profile picture end up having the C badge AND the Booked badge or does the C badge get replaced by the Booked badge?

**Comment by v-saikirang** [comment]
Hi @LisaJo48,
Thanks for your response.
So in your example, If you have applied "C" badge first and then applied "Booked" again the new badge will be applied on top of your old picture which also has the C badge. You can try this and see how it works. 

We are always retrieving your current profile picture and applying on top of it. We are not storing the images anywhere so we will not have the history of your old picture.  

Please let us know if you need more information.
Thanks.

**Comment by LisaJo48** [comment]
Thank you. That answers my question. (I'm not able to actually test it because it will show to other users and we're not ready to deploy this until December.

I can't speak for the author of this ticket, but I have no other questions.
