### ISSUE TITLE
Not able to use the EventName field in the Event Track Details list

### ISSUE THREAD

**Issue by LisaJo48** [OfficeDev/microsoft-teams-apps-champion-management#132]
The Event Track Details list, there are 2 fields/columns (among others) name Title and EventName that contain the identical data. This is a problem because it renders the EventName field redundant and useless. 

For example, "Blog" is an event type choice in the Events List list. The problem is that there are many instances of blogs: a blog about TEAMS, another blog about Word, another blog about Power BI, another blog about SharePoint, etc.  Because the EventName field contains the same info as the Title field, there is no way to distinguish between the different blogs. The EventName field needs to contain the name of the specific blog i.e. TEAMS, Word, Power BI, SharePoint, etc.

The result is a significant gap in information about the interests, accomplishments and expertise about our champions. I don't simply want to know that they read a blog; I want to know which blog/which topic they read. 

The solve this issue, the EventName field, which is currently useless and meaningless, should identify which blog event the champion attended/completed. 

Therefore, the EventName field needs to be exposed on the Leaderboard in the Record Event section so that the champion can complete it with the name of the 'event' he/she/they attended, read, or completed.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Thanks for your feedback.

One of the features in our next release might be able to handle your scenario. We have introduced a "Notes" field in the leader board section when the user is recording a new event. Here they can add more notes about the event that they attended. I hope this should address your concern. Please let me know.

As far as the redundant columns, we have already identified this concern and will plan to clean it up in future.

Thanks,

**Comment by LisaJo48** [comment]
Thanks for the response but, unfortunately, a Notes section is not going to clearly explain what information belongs in the field unless we do significant training and documentation beforehand....and everyone reads and uses the field correctly which is hard to achieve. A Notes field is a great idea but exposing the EventName field is still useful in addition to the ability to include additional notes.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Thanks for your feedback. 

We understand your business requirement here. Unfortunately we cannot include this in our template as this requires major code changes. The "Notes" field might help you to an extent in your scenario. But you can still clone this repo and customize the app to suit your needs. We have also provided high level instructions on App customization in our Deployment guide. Please refer to it and let us know if you need more information.

Thanks.

**Comment by LisaJo48** [comment]
Thank you. I was hoping this might be something of value to others as well and would warrant a place on your To Do List for future enhancements. Sounds like it's not.

**Comment by LisaJo48** [comment]
Where do I post suggestions for this app that other users can vote up (or not) so that you and I can learn, accurately, if a suggestion is more broadly applicable (or not) than we thought?

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

You can continue to post your suggestions here in the same GitHub Repo Issue section as well and we keep track of all items and we add it our own internal backlog wherever applicable and prioritize accordingly. And if you find a related feature request in the existing Issues in GitHub you can tag them to your issue as well.

Thanks for your interest in the app and appreciate your feedback.

Thanks.
