### ISSUE TITLE
Added CMP as a tab in Teams, blue loading circle is gone

### ISSUE THREAD

**Issue by rfriberg001** [OfficeDev/microsoft-teams-apps-champion-management#135]
Have installed CMP app, added to Teams tab, blue circle was loading for longer than 5min. So, I hit refresh. 

Now the tab opens I see the blue circle for 1-2secs it disappears and none of the additional tiles appear (only the original leader board tile is displayed)

**Comment by v-saikirang** [comment]
Hi @rfriberg001,

Thanks for your interest in the app.

Can you please share the below:
1) Screenshot of the app home page
2) Screenshot of the contents of the "Members List" in SharePoint site "ChampionManagementPlatform".

I suspect you may not be added as "Manager" in the Member List. We can proceed based on your screenshots.
Thanks.

**Comment by rfriberg001** [comment]
[cid:e4ecee79-852d-4e63-b6a4-a8e2f51b8466]
[cid:d42de06e-5af8-4629-b88f-9dc16c1b3ba7]
________________________________

**Comment by v-saikirang** [comment]
Hi @rfriberg001,

I am not able to view the images that you shared. Can you please share the images directly from GitHub instead of email.
Thanks.

**Comment by rfriberg001** [comment]
![image](https://user-images.githubusercontent.com/116697674/197957209-dc3dbd47-868c-4b58-be30-72b3d08eaa00.png)
![image](https://user-images.githubusercontent.com/116697674/197957330-a6194b62-b226-42a3-a9de-87e2c4cd4f3f.png)

**Comment by v-saikirang** [comment]
Hi @rfriberg001,

For some reason I don't see you were added to "Members List". Can you add a entry in this list with the below details and refresh the app.
1) Title: Your Email
2) Role: Manager
3) Status: Approved.
4) First Name and Last Name
Rest of the fields are optional.

Please try this and let me know if it worked.
Thanks,
Sai.

**Comment by LisaJo48** [comment]
If I may be so bold, is the user a member of a SPO's permission group (i.e. Members or Owners)? That made a diff for me.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Yes, that could be one of the reasons too. But irrespective of that the user still needs to be added as manager in "MemberList". So That could be the next step of trouble shooting depending on the outcome of the above step.
Thanks.

**Comment by rfriberg001** [comment]
Hello, I can confirm adding to the Member List fixed the issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-saikirang** [comment]
Hi @rfriberg001,

Thanks for confirming. Please create a new issue if you see any further issues.

Thanks.
