### ISSUE TITLE
Issue adding champion management tool to teams

### ISSUE THREAD

**Issue by MatthiasVeelaert** [OfficeDev/microsoft-teams-apps-champion-management#138]
I currently have an issue adding the champion management tool to teams. I have added it once before and I didn't do the initial configuration in teams so we could only see 1 tab called champion leaderboard. I have then tried to uninstall the ap completely from sharepoint and teams and reinstall it, but I always get the same display screen with only 1 tab to press. It's the same for everyone. Is there a way to fix this?
![Screenshot 2022-11-30 143154](https://user-images.githubusercontent.com/43444296/204809390-ac7ad8e4-74a7-4fb8-a061-47c5438cc347.png)
This is the output I get.

**Comment by v-saikirang** [comment]
Hi @MatthiasVeelaert,

Thanks for reaching out to us. Can you please share a screenshot of Site Contents page from the SharePoint site "championmanagementplatform" and also the contents of the "members list". 
Thanks.

**Comment by MelanieCamden** [comment]
I had a similar issue and found it resolved when I went into ...sites/ChampionManagementPlatform/Lists/Member%20List/AllItems.aspx and added myself as a manager and ensured the status was approved.  I also added everyone exccept externals as read access to the sharepoint site. 

Once I was a manager in the members list I was able to see the admin icons in the app
