### ISSUE TITLE
Multiple default items creation in Event list

### ISSUE THREAD

**Issue by yhabersaat** [OfficeDev/microsoft-teams-apps-champion-management#14]
When using the app, there is multiple default items creation in the Event list. I don't think it's a normal behavior from this app.

![image](https://user-images.githubusercontent.com/15676985/115195420-05ced100-a0ef-11eb-8259-395b89bde3b7.png)

**Comment by Smitat-msft** [comment]
@yhabersaat , thank you for being patient while we triaged this issue. I'll update you once we have a resolution.

**Comment by eshwarmsft** [comment]
This issue require EnvofrceUniqueKey at column level to restrict duplicates at code level, Which we are working and will address at earliest in the coming build.

**Comment by yhabersaat** [comment]
Checked the Enforce unique values for the Title column and looks like it solved the issue!

**Comment by Smitat-msft** [comment]
Thanks, @yhabersaat for confirming. closing this issue as resolved.
