### ISSUE TITLE
Provide detail on the picture overlay process

### ISSUE THREAD

**Issue by grundy2** [OfficeDev/microsoft-teams-apps-champion-management#142]
Could you please provide more detail on how the picture/badge is overlayed? thank you

**Comment by v-saikirang** [comment]
Hi @grundy2,

Thanks for your interest in the app. The app provides "Digital Badge" from the dashboard which is aimed at giving the users the flexibility to apply champion badges on top of their current office 365 profile picture. When you navigate to Digital Badge you will see the badges available for you depending on 2 things:
1) Points you scored 
2) Tournaments you completed under "Tournament of Teams" section(If Enabled).
3) Admin settings in the "Digital Badges Assets" library the SP site.

Please refer to the "Digital Badges" section in the wiki [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Solution-Overview#digital-badge).
Thanks.
