### ISSUE TITLE
Spinning when adding a new member 

### ISSUE THREAD

**Issue by nicolamorris925** [OfficeDev/microsoft-teams-apps-champion-management#145]
When adding a new champion, the platform will continuously spin. The only way to add a new member is through the SharePoint site. Has anyone seen this issue before and are there any troubleshooting tips?

**Comment by MelanieCamden** [comment]
I had a similar issue and found it resolved when I went into ...sites/ChampionManagementPlatform/Lists/Member%20List/AllItems.aspx and added myself as a manager and ensured the status was approved. I also added everyone exccept externals as read access to the sharepoint site.

**Comment by v-saikirang** [comment]
Hi @nicolamorris925,

Thanks for reaching out to us.
As @MelanieCamden  pointed above please check if the "MembersList" in Sharepoint is empty. If empty add a record with the below values and try again.
1) Title: Your email id
2) Status: Approved
3) Role: Manager

If this still doesn't work please share a screenshot of the "MemberList" and also errors in browser console logs when you are adding a member.

Thanks.
