### ISSUE TITLE
Is this possible in GCC High?

### ISSUE THREAD

**Issue by timclynch** [OfficeDev/microsoft-teams-apps-champion-management#146]
Do you know if this is something that can be used in a GCC High environment?

**Comment by v-saikirang** [comment]
Hi @timclynch,

Thanks for reaching out to us. 

Sorry to say that the CMP app does not work in GCC-H tenant as of now due to some limitations. But it works in GCC tenant. Please consider installing this in GCC tenant if that's a possibility.

Thanks.
