### ISSUE TITLE
Spinning & Question about site collection 

### ISSUE THREAD

**Issue by nicolamorris925** [OfficeDev/microsoft-teams-apps-champion-management#147]
Hi all - we are running into an issue when a user is added to the champion app though teams, they see the spinning circle and aren't able to access content.
![MicrosoftTeams-imageCM1](https://user-images.githubusercontent.com/109625325/213495510-1f7cdb67-430d-4565-82a7-34b50cb9d763.png)

However, if the user is added as a member directly to the backend member list in SharePoint, they are able to access the content. 
![MicrosoftTeams-imageCM2](https://user-images.githubusercontent.com/109625325/213495653-4e65726a-c5f5-4dcb-97f0-2da9b0800516.png)

I have seen some similar issues with spinning being related to API permissions, so I am including screenshot below: 
![MicrosoftTeams-imageCM3](https://user-images.githubusercontent.com/109625325/213495853-d019763f-9c40-46ad-bfd5-43e4ebe1ae54.png)
![MicrosoftTeams-imageCM4](https://user-images.githubusercontent.com/109625325/213495884-04c29e76-5bde-4bd8-931f-e3d6f2c2d381.png)

Also, we have a separate question about edit permissions for end-users - if someone were to stumble on the site collection and try to add webparts or edit the page would they be able to? The concern stems from the step in the deployment guide where we give everyone except external users edit rights. 

Please let me know if we can set up a troubleshooting call. Thanks!

**Comment by v-saikirang** [comment]
Hi @nicolamorris925,

Thanks for reaching out to us.

1) For a user to be be a champion the Admin needs to add the person through "Add Member" screen on the dashboard also apart from giving them access to the Share point site. This will add the person automatically to the "Members List" and you don't have to do it manually.
2) If you want to restrict the SP site you can avoid adding "Everyone" and explicitly add the people that you want to share the app with. This way, only people that you have added will have access to the SP site. You can choose to unselect "Send email notifications" while adding to Share point site so they are not ware of the direct links. 

Please let me know if you need more information.

Thanks,
Sai.
