### ISSUE TITLE
Discrepancy in Event Rank?

### ISSUE THREAD

**Issue by LisaJo48** [OfficeDev/microsoft-teams-apps-champion-management#149]
Why am I listed as #1 and also as #16?

![Screenshot 2023-02-10 090647](https://user-images.githubusercontent.com/46016140/218112000-e655d879-90b3-4f9c-8a03-33e9f1d24251.png)

**Comment by LisaJo48** [comment]
I cannot be positive that this changed with the upgrade. I can only say it never caught my eye before 3 days ago. So, I can only assume there wasn't a discrepancy before. 

I made some changes to the membership data in an attempt to straighten this out and it is better. I think it best that I keep an eye on it to see if it happens again. I am going to close this one.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

Can you please share more details about this issue and fix. If this is something that needs to fixed in our code it would be helpful.
Thanks.
