### ISSUE TITLE
403 Error in MS Teams

### ISSUE THREAD

**Issue by calvinnbs** [OfficeDev/microsoft-teams-apps-champion-management#15]
We installed the package successfully in the App Catalog. The user who created a MS Team from the template can access the app tab without issues but when I go (desktop or web) I get "Something went wrong. 403" dialog and only see the Champion Leader Board, Add Members, and Digital Badge icons.  Digital Badge and Add Members both seem to work but Champion Leader Board is a blank white page with the blue CMP banner.

**Comment by VesaJuvonen** [comment]
Thanks @calvinnbs for reporting on this. We are actively looking into this issue. Seems like a permission related issue which we'll work on the code. Issue has been reported for the solution development team and we should have an update on this soon.

**Comment by karuanag** [comment]
Yes thank you @calvinnbs  we are actively troubleshooting this issues.  We will update here shortly.

**Comment by arun-msft** [comment]
@calvinnbs : Apologies for delay, we are working on this issue and will provide you updates ASAP.

**Comment by calvinnbs** [comment]
Thank you, that did it!

**Comment by arun-msft** [comment]
Thanks for the confirmation.
