### ISSUE TITLE
Champions Team App Not Loading All Content

### ISSUE THREAD

**Issue by tborchardt** [OfficeDev/microsoft-teams-apps-champion-management#152]
I recently installed the Champion Management Platform in my M365 Tenant and set it up in a Teams group. However, when I load the tab for the app, it only shows Champion Leaderboard and no other options.

The SharePoint site for the app was created and the app is allowed to run in Teams (Verified permissions for app to be allowed in Teams admin). API access was also approved in the SharePoint Admin console. This is my first time installing this on my org's tenant. 

![image](https://user-images.githubusercontent.com/125387906/218797738-298184fe-8cd4-4a8a-ac12-4dc7c6d93e86.png)

**Comment by LisaJo48** [comment]
Idea: have you checked the SP site permissions to be sure your user is a member of a permission group? That tripped me up for a while.

**Comment by tborchardt** [comment]
I can confirm that I’m the Primary Admin on the ChampionPlatform SharePoint Site that was generated as well as the Teams group I’ve added the app to.


[k Trip Inc.]<https://www.kwiktrip.com/>

Tyler Borchardt
IT – Business Integrations Support Analyst 1
608-793-4064
***@***.******@***.***>
My Microsoft Bookings Page

[ebook Icon]<https://www.facebook.com/KwikTrip/> [tter Icon] <https://www.twitter.com/KwikTrip/>  [tagram Icon] <https://www.instagram.com/KwikTrip/>  [pchat Icon] <https://www.snapchat.com/add/KwikTrip/>  [tube Icon] <https://www.youtube.com/user/KwikTripKwikStar/>

Mission Statement: "To serve our customers and community more effectively than anyone else by treating our customers, co-workers and suppliers as we, personally, would like to be treated and to make a difference in someone's life.”

**Comment by LisaJo48** [comment]
OK. Sounds like you have confirmed that your user is a member of the CMP's SPO site's Owners SharePoint permission group along with being noted as the Admin in the Members List list, which means being in one and not the other isn't the issue for you. That was the only idea I had to offer.

**Comment by tborchardt** [comment]
Thanks for the input though. It was still greatly appreciated and items I should've mentioned in the original post. If there are any other details worth mentioning, please let me know that as well.

**Comment by v-saikirang** [comment]
Hi @tborchardt,

Thanks for reaching out to us.

Can you please share screenshots of "Site Contents" and "Membership List" from the Sharepoint site.

Thanks,
Sai.

**Comment by tborchardt** [comment]
> Hi @tborchardt,
> 
> Thanks for reaching out to us.
> 
> Can you please share screenshots of "Site Contents" and "Membership List" from the Sharepoint site.
> 
> Thanks, Sai.

Which site? The SharePoint site tied to the Teams group I added it to? Or the one stood up by itself for the Champion Management Platform?

**Comment by v-saikirang** [comment]
Hi @tborchardt,

I am referring to the Champion Management Platform site. And can you also try open the app as a personal app directly from "Apps" in Teams instead of opening it as a tab within a channel.

Thanks.

**Comment by tborchardt** [comment]
Well, when I logged in for work today I found that the CMP app is now loading properly in the Teams channel I originally added it to. Nothing was done specifically on my end to solve. Not sure if it just took a couple days to populate permissions and such appropriately?Anywhos, thankjs for the help everyone!

**Comment by LisaJo48** [comment]
[@tborchardt ](https://github.com/tborchardt)
Didn't see that your question, "can you also try open the app as a personal app directly from "Apps" in Teams instead of opening it as a tab within a channel", was answered so, just in case:

TEAMS->App icon->Search for "Champion Management Program"->Select app's tile->Add button.
Adds Star icon to your lefthand menu in TEAMS. 
Right click on the Star icon and PIN it so that it will always show in your lefthand list of icons. 
Each user must do this for themselves.
