### ISSUE TITLE
Reset the App?

### ISSUE THREAD

**Issue by JtcainTX** [OfficeDev/microsoft-teams-apps-champion-management#153]
What is the best way to reset the leaderboard and all posted data?

**Comment by v-saikirang** [comment]
Hi @JtcainTX,

Thanks for reaching out to us.

To reset the leaderboard you can try clearing the data in the "Event Track Details" list. To remove the champions as well you can clean up the "Members List". Please make sure not to remove the "Manager" in the Members List.
Thanks.
