### ISSUE TITLE
Tournament and Participants Report do not include newest tournament data

### ISSUE THREAD

**Issue by LisaJo48** [OfficeDev/microsoft-teams-apps-champion-management#156]
The User Actions list contains 154 records of which 112 are related to a tournament for which no data is found in the Tournament or Participants Reports for that tournament. Shouldn't there be a record in the Tournament Report showing counts/totals? Shouldn't there be entries for each person who completed at least one activity for the tournament?

112 entries from 14 participants
![image](https://user-images.githubusercontent.com/46016140/226072523-0a016e68-f96f-4f4f-b7d1-d3a8346429ef.png)

Nothing listed for the "TEAM-Up..." tournament's participants
![image](https://user-images.githubusercontent.com/46016140/226072100-e6055c88-8273-4b73-8631-e3109986bd1a.png)

Nothing listed for the "TEAM-Up..." tournament giving summary stats for it
![image](https://user-images.githubusercontent.com/46016140/226072160-57094799-46d5-4d5e-aa5b-bb5681e36ac9.png)

**Comment by v-saikirang** [comment]
Hi @LisaJo48 ,

Can you please confirm if the Tournament you are referring to has been "Completed" or still in progress. The Tournament report  shows data only for completed tournaments. So until you complete a tournament you will not see the data in the "Tournaments Report" list.

Thanks.

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

May I know which Participants Report are you referring to. There is only one Report for Tournaments as of now. And yes we would consider your feedback and assess if that is some thing that we can implement in future.

Thanks.

**Comment by LisaJo48** [comment]
As the screenshots I included earlier indicate, I see 2 reports/lists: 

1. Tournament Report
2. Participant Report

both of which are associated to tournaments because both of them reference tournament names. 

You stated earlier that the Tournament Report only contains data for completed tournaments. I am asking, now, about the other report: the Participant Report, and the problem I'm having with it (which was also part of this submitted issue).

**Comment by v-saikirang** [comment]
Hi @LisaJo48,

1. Tournament Report
2 Participant Report

Both the above SP lists are actually feeding the same report in "Tournaments Report". These 2 lists are not meant to be consumed directly. They have the supporting data for the report in the UI. And both the lists will have the data for only completed tournaments.
Please let us know if you need more information.
Thanks.
Thanks.
