### ISSUE TITLE
Champion Management App and Tab load only one tile in Teams and there is a spin icon spinning for rest of the tiles

### ISSUE THREAD

**Issue by vishrutachopra** [OfficeDev/microsoft-teams-apps-champion-management#160]
Hi, I have successfully deployed the CMP application but the App only loads one tile which is "Champion Leader board" in the Teams direct App and when CMP is associated as a Tab. Following is the screenshot of what is happening.
![image](https://user-images.githubusercontent.com/86916946/229367047-76ca4571-abf1-4de2-afc5-0da390fd2632.png)

Please advise on how this can be remediated at the earliest.

**Comment by v-saikirang** [comment]
Hi @vishrutachopra,

Thanks for reaching out to us. Can you please confirm below:
1) Have you opened the app with the admin account.
2) Can you confirm if the Sharepoint site "ChampionManagementPlatform" is created. If yes, can you share a screenshot of the Site Contents page.
3) If you don't see the site collection can you please check under "Deleted Sites" in SP admin center.
4) Have you approved the API permissions in SP Admin center as specified in the deployment guide.
Thanks.

**Comment by vishrutachopra** [comment]
Hi,

Answers to your questions are as follows in green:

  1.  Have you opened the app with the admin account. - Yes
  2.  Can you confirm if the Sharepoint site "ChampionManagementPlatform" is created. If yes, can you share a screenshot of the Site Contents page. - Yes, the site is created. ***@***.***
  3.  If you don't see the site collection can you please check under "Deleted Sites" in SP admin center. - I can see the sitecollection.
  4.  Have you approved the API permissions in SP Admin center as specified in the deployment guide. - Yes, all the API permissions are approved.
***@***.***
Please let me know if any other information is needed.

Thanks and Regards
Vishruta Chopra
she/her
CSA Engineering
Customer Success Unit
Mobile: +91-9811037200
***@***.******@***.***>

[Microsoft Logo]

**Comment by v-saikirang** [comment]
Hi @vishrutachopra,

As per our offline communication we were able to deploy the app successfully. The deployment failed due to a discrepancy with the API permissions.
Thanks.
