### ISSUE TITLE
Unexpected Error when Nominating a Member 

### ISSUE THREAD

**Issue by chrisbrockell** [OfficeDev/microsoft-teams-apps-champion-management#165]
![config list settings error msg](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/135256985/712597b4-c77b-40f6-bc19-61fa85130065)

Member tried updating the nominating a member list by adding a new person and received this error message and the SharePoint list did not update with new member.  Member had to force close teams.  Then the error message came up again but the second time around the member did populate on the SharePoint list.

Anyone experience the same error message?

**Comment by v-saikirang** [comment]
Hi @chrisbrockell,

Thanks for reaching out to us. Can you please confirm you dont see the error anymore and you are able to add users now. If yes, then you can ignore that error since its related to setting up of the config list in the SharePoint site. The list might not have been created already the first time. But once created it should be fine. Please let me know.
Thanks.

**Comment by chrisbrockell** [comment]
Confirming that I am an owner of the CMP and I do not get any errors but one of our members is still getting this error.  I thought it was when he tried to nominate a new member but he was actually receiving the error message when he initially clicked on the Champion Management Platform.
Error is still happening but allowing him to nominate a new member.

Do you think there is something wrong with his individual profile within the CMP and I would need to remove it and re-add.  So far it’s only isolated to this one individual.


***@***.***

Please submit an IT Service Portal ticket for any Microsoft questions or help
Submit a ticket - IT Service Portal (service-now.com)<https://christianacare.service-now.com/itserviceportal?id=sc_cat_item&sys_id=07b7be1adb47e45485dfd5cdd396195f>

Schedule time with me
https://calendly.com/christina-brockell

From: v-saikirang ***@***.***>
Sent: Thursday, June 1, 2023 12:58 PM
To: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Brockell, Chris M ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OfficeDev/microsoft-teams-apps-champion-management] Unexpected Error when Nominating a Member (Issue #165)

Caution: This message originated from outside the ChristianaCare organization. Please exercise additional caution with any links or attachments.

Hi @chrisbrockell<https://secure-web.cisco.com/1OVmOqRFLB78XFlyaRMnHyLOSxjAP1JbPvSDRY_VrSj9F3FUJZB4NB6j_DyqQQZ4N5FzLQSX1fXs1_N9FHAVOsRkZsReF39LzpHdhuEQnKbjdE4Uw3xfVFeNp_Xoe0pOaBcoQL3NWZX7foFZo5L8ZcoImWv-nnSlZ14ADpQE_Xgt3l6_rguvQ2cwMeW1cdmxSmKy3OauPYWILgAZ-lh_er-vj9T2I1adzNVqLoaSfvNZvv-4a9kVpqZdGrx1_4elQyCtbOcDvLSHjaRNla2Lq3tVF5UC-VQYRGLNBLOu27lgRFDLZ4VUyGy4FImDXYKF0/https%3A%2F%2Fgithub.com%2Fchrisbrockell>,

Thanks for reaching out to us. Can you please confirm you dont see the error anymore and you are able to add users now. If yes, then you can ignore that error since its related to setting up of the config list in the SharePoint site. The list might not have been created already the first time. But once created it should be fine. Please let me know.
Thanks.

—
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1IatLd0RUAePU8sKN4_YkCOVv1yMzHS5vijq54BOPPdMDtNGrgjy-iDa_DgZnpVgwi7EJMrvG9502SmP45g1LZV6PHe6g2HHvaL2wCD46ewwokq9VtnRILMLbVeqj4iq3xbkPNr_RFQK0XhqdsrJvcgViIPRk-Hl6lU8qRGvhzj6mj_IeIuGVBnXbxGlsUvyKiyzOU_5oZHdVPR58-qGUO-TFAekfH4coeZtWEBir0MkQmANCyt94e2e0COe-bA3nu_FSdvQwijIs9G44wBLsATcVYbyzNcYcFL8kbL7P1sRZQrvBchZyq_6wyxkgxPrl/https%3A%2F%2Fgithub.com%2FOfficeDev%2Fmicrosoft-teams-apps-champion-management%2Fissues%2F165%23issuecomment-1572426496>, or unsubscribe<https://secure-web.cisco.com/1wngp-UBzaejnKCyRuwWOBabM7yIwhbjmYGRD9xkYEeMh32QXPk4YtSi2MN5GMRjHJ3ZkRZJKCWeDW51hljHpuStH00qlfv-pHCYdzcZdf9v7gN1U1UwDndFTGAPc5tAAZnTqf_xfTNrxGFuNoA_K2xx48T827hPl_y2I4wAHJxWOJluEkCRkPeRAJ-kXNw396IV7H5_JWNp1ydMSLqBZX37VIu8WLer006MV_F0gO-2ryt8YxR1mdG265Erjsu1-kUbL2xfWd3e-EG5gkLTleHXHzw4acbJ-6e8zRdy2kHXy0_JUW0CRJmRqyFxbRluz/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBAH5XGPQBDF3VXXJB7JLZ6DXJDCYRANCNFSM6AAAAAAYXGCUJM>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Confidentiality Notice: This email (including any attachments) is intended solely for the addressee(s) and may contain confidential and/or privileged information and may be legally protected from disclosure. If you received this email in error, please immediately notify the sender by reply email and then delete this message and any attachments. If you are not the intended recipient, you are hereby notified that any disclosure, distribution, reproduction, or other use of this message or its attachments is strictly prohibited.

**Comment by v-saikirang** [comment]
Hi @chrisbrockell,

As I understand you dont see that error and you are able to add the users without any issues. If that is the case can you please confirm if that person is added to the Members group.
Thanks.
