### ISSUE TITLE
Multiple instances of solution

### ISSUE THREAD

**Issue by nomorechili** [OfficeDev/microsoft-teams-apps-champion-management#167]
Quick check, are we able to deploy multiple instances of this solution within the same tenant?
Our single tenant environment hosts many organisations and each organisation may want to keep their own instance of champion management. .

**Comment by v-saikirang** [comment]
Hi @nomorechili,

Thanks for reaching out to us. 

Currently there is no way to deploy multiple instances of the app in same tenant. To do so, you will have to customize the app and modify the code to suit your needs. Please let me know if you need more information.

Thanks.
