### ISSUE TITLE
Champions Management Platform Issues 

### ISSUE THREAD

**Issue by Artpillz** [OfficeDev/microsoft-teams-apps-champion-management#168]
![Screenshot 2023-07-05 122134](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/66799fc0-6d45-4db3-9c4f-708f6f5d69e6)
### Champions Management Platform Circle of Death
I followed the installation process for Champions Management into Teams, but it has been continuously loading since yesterday with the spinning circle. Could you please assist me with resolving this issue?

**Comment by v-saikirang** [comment]
Hi @Artpillz,

Thanks for reaching out to us.

Can you please check if the sharepoint site "championmanagementplatform" got created. If yes, please share the screenshot of the "Site Contents" page. I assume you have approved the Graph API permissions from Sharepoint Admin center as mentioned in the deployment guide. Please share a screenshot of the API permissions page as well.

Thanks.

**Comment by Artpillz** [comment]
![MicrosoftTeams-image (3)](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/a7c54c15-0936-499b-b1fd-fbf8cb86ca89)
![MicrosoftTeams-image (2)](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/cb3fc53d-f7cf-4a6d-a2a0-fd3317ba031d)
Yes they approve the two files API

**Comment by v-saikirang** [comment]
Hi @Artpillz,

Thanks for sharing the information.

I see the same permission repeated twice. It should be ideally as below:
<img width="589" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/87538202/8a497e04-510f-453e-97f3-8608dceba721">

Please try the below steps to fix this.
1) Delete both the API permissions.
2) Delete the package from App Catalog
3) Reupload and deploy the package as per the deployment guide.
4) You should now see both the API permissions as shown in the above screenshot. Approve both the permissions.
5) Open the Teams app with admin account(the account you used to set it up earlier)

Please let me know if you see any issues.

Thanks.

**Comment by v-saikirang** [comment]
Hi @Artpillz,

Can you please share the screenshots of the below:
1) API permissions
2) "Site Contents" page of the  Share point site.

Thanks.

**Comment by Artpillz** [comment]
![Screenshot 2023-07-11 091732](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/74691536-b068-47bb-b46b-3e4d5b1a4090)
![Screenshot 2023-07-11 091650](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/81cfed49-1030-4e6e-bf8d-d241a338fb03)

**Comment by Artpillz** [comment]
![Screenshot 2023-07-11 091732](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/6198c173-8916-45f7-a375-dc1690c2eae6)
![Screenshot 2023-07-11 091650](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/54e80624-eb06-43f0-af7a-8d8e4d46a65f)
![Screenshot 2023-07-11 092006](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/6a113de6-8c79-4baa-b1b9-fe108c3b9641)

**Comment by Artpillz** [comment]
Y
![Screenshot 2023-07-11 183339](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/34c12300-c3b1-4b94-aea5-8b693cf97379)
es I am stuck in an endless cycle with no progress or variation. MJTMT89

**Comment by Artpillz** [comment]
> Hello, I am experiencing a similar error.
> 
> ![API](https://user-images.githubusercontent.com/139350334/252986130-609b12a2-d991-4ecb-961e-5de8a3704586.jpg) ![manage apps](https://user-images.githubusercontent.com/139350334/252986138-5822c37a-e11a-44a6-be0b-21fc90d817f3.jpg) ![Active sites](https://user-images.githubusercontent.com/139350334/252986167-0a09001b-3b67-430a-a0b4-f56635e819d6.jpg)
> 
> This is what is showing on the admin
> 
> ![app](https://user-images.githubusercontent.com/139350334/252986470-f50b0a29-1aec-4d8b-ad24-334ba94c28e2.jpg)
![Screenshot 2023-07-11 183339](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/d2a6890d-6a86-468d-bb85-91a624dc700d)

Yes, the same thing just a circle, and nothing else happen.

**Comment by v-saikirang** [comment]
Hi @Artpillz, 

Can you please confirm if you are using the SP Admin account to open the app in Teams. It would be the same account that you used to deploy the package file.

And can you also navigate to the Share point site and share a screenshot of the "View all Site contents" page. I would like to verify the lists created in the SP site.

Hi @MJTMT89,

Can you please create a new ticket for ease of tracking and also share the requested information as above. 

Thanks.

**Comment by Artpillz** [comment]
Will do 
![Screenshot 2023-07-13 124636](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/9da66d84-7998-4b16-a56d-855f7eca2288)
![Screenshot 2023-07-13 124349](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/311d9f6f-7047-4072-bac2-164699a4a18b)
![Screenshot 2023-07-13 091319](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/be5975ea-6667-4fb2-9260-7f60c8cafb4e)

**Comment by v-saikirang** [comment]
Hi @Artpillz,

Can you please confirm if you you have SP admin access. If not can you please ask the SP admin to open the App in Teams. 

If it still doesn't work you can try the below:

1) Delete the "championmanagementplatform" from both "Active Sites" and "Deleted Sites"
2) Wait for around 30 minutes for the cache to clear out. 
3) Open the app in Teams in browser using SP admin account.
4) If you still see any issues please share the browser console logs.

Thanks.

**Comment by Artpillz** [comment]
Alright, I will do that. Thank you for the information. I'll get back to you within 1 day

**Comment by Artpillz** [comment]
![Screenshot 2023-07-14 161337](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/84aa1d66-5760-4b90-abaa-ec3e079c8a28)
 I'm the admin of SharePoint.

**Comment by v-prigunasek** [comment]
Hi @Artpillz ,

This issue could happen sometimes when the "Sites.Manage.All" permission was missing under Configured Permissions in the Azure Portal ( Azure >> App Registrations >> API Permissions for "SharePoint Online Client Extensibility Web Application Principal" >> API Permissions).

To fix that issue, please follow the below steps:

1. Add the missing permissions ("Sites.Manage.All", "User.ReadWrite) by clicking + Add a Permission under Configured Permissions >> Choose Microsoft Graph >> Select Delegated Permissions >> Type the Permission in the search box >> Select the permission >> Click on Add Permissions

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/98514691/c2be8643-cc7e-4238-bf60-b1f9584bca00)

2. Then Grant Admin consent and make sure the Status column will be updated to confirm permissions are set.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/98514691/399347ad-aa5d-4fb6-a4e2-919edfe7e39a)

Once this was done, wait for 10-15 mins and try accessing the CMP application from Teams.


For more details, Refer here - 
https://github.com/OfficeDev/microsoft-teams-apps-champion-management/issues/87#issuecomment-1075105659

**Comment by Artpillz** [comment]
thank you will get back you shortly.

**Comment by Artpillz** [comment]
Thank you! Everything is working now.

**Comment by Artpillz** [comment]
Thank you, it's working. However, it seems that the Multi Badge Support in Digital Badge is not displaying pictures correctly.

**Comment by v-prigunasek** [comment]
Hi @Artpillz ,

Have you added "User.ReadWrite" permission also in the "SharePoint Online Client Extensibility Web Application Principal" app in the Azure Portal? Can you please check whether this permission is available under configured Permissions. 

Could you please share us the screenshot of Digital Badge library from the CMP SharePoint site?

**Comment by Artpillz** [comment]
Will do thank you

**Comment by Artpillz** [comment]
![Screenshot 2023-07-24 101127](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/0d98b4ef-c7bd-4543-a760-81ea88d3f320)
I didn't see it should be with Sites.Manage.All Right?

**Comment by v-saikirang** [comment]
Hi @Artpillz,

Yes, Please add "User.ReadWrite" permission also and check after few minutes.

Thanks.

**Comment by Artpillz** [comment]
thank you will do

**Comment by Artpillz** [comment]
Thank you for everything working as designed.
