### ISSUE TITLE
Install in existing site

### ISSUE THREAD

**Issue by loryanstrant** [OfficeDev/microsoft-teams-apps-champion-management#17]
Can this be installed in an existing SharePoint site instead of creating a new one?

**Comment by eshwarmsft** [comment]
Hi @loryanstrant  

Currently the CMP design flow is about having separate site which will be responsible for managing or restricting the data access to the limited users than all the users of the root site. At this moment the answer is not possible with the current design.

**Comment by v-saikirang** [comment]
Hi @loryaninsync,

 Thanks for your patience! We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 
To answer your question, yes you can now install in existing share point site. If you wish to install to a specific existing site you can download the source code and modify the location of SharePoint site the package installs to. This would require a recompile of the package.

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by JoshLeporati** [comment]
@loryanstrant with the latest update and everything being contained in single SPO site this is now possible, per @v-saikirang answer above. Direct link [here ](https://github.com/OfficeDev/microsoft-teams-apps-champion-management#customize-configuration)to that customization section.
