### ISSUE TITLE
LeaderBoard / Profile points not in sync

### ISSUE THREAD

**Issue by BanditUK2002** [OfficeDev/microsoft-teams-apps-champion-management#172]
I'm seeing an issue where the individual's total points and rank are not displaying on the left-hand side. In the example below I have 1100 point on the leaderboard but 0 on the left:

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/132071656/a7e2c54e-f414-4d53-a91b-813b3c7f458a)

**Comment by v-saikirang** [comment]
Hi @BanditUK2002 ,

Thanks for reaching out to us. Can you confirm the below:

1) Is this happening to all users or only you.
2) Can you share a full screenshot of the leaderboard without applying the search filter.
3) Can you filter your name in the Share point list  "Membership List" and share a screenshot.

Thanks.

**Comment by BanditUK2002** [comment]
Hi @v-saikirang 

1. It seems to be several users but not all
2. 
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/132071656/c6d33d09-3c20-4e84-9fe8-c86ac79180df)
3. I don't have "Membership List" but I do have "Member List", so I presume this is the one you mean - screenshot below

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/132071656/990b2083-f639-4827-8fdf-83b557638c01)

**Comment by v-saikirang** [comment]
Thanks for sharing the information. Can you please filter the member list with the user for who its working and share a screenshot. It would be great if you can share the screen shot of the leader board of that user.

Thanks.

**Comment by BanditUK2002** [comment]
Sorry for the delay in getting back to you - I've been capturing feedback from other users. It seems this is now working as expected - is it possible that opening the SP lists to capture the screenshots could have fixed it?

**Comment by v-saikirang** [comment]
Hi @BanditUK2002,

Glad it's working for you now. I don't think opening the SP lists would fix it. It could have been a glitch.

Thanks for your interest in the app.

Thanks.
