### ISSUE TITLE
Unable to complete "Become a Champion"

### ISSUE THREAD

**Issue by heather2552** [OfficeDev/microsoft-teams-apps-champion-management#173]
I am trying to add myself to the Champion Management Platform but I am getting an error message.  Also, I do not have the selections others have, see below.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/141074281/e8519048-2405-4d89-b28f-aefb8c343e04)

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/141074281/dd93ef5b-9335-4ac8-9d79-4c7f1f9bf852)
Thank you,

Heather

**Comment by v-chpaladugu** [comment]
Hi @heather2552 ,
Thanks for reaching out to us. Can you please confirm the below:
1. Open the Champion Management Platform app in browser teams and share the screenshot of error in console window.
2. Check whether you have edit access to the Member list in the ChampionManagementPlatform SharePoint site.

**Comment by heather2552** [comment]
Hello,

I am filling out the “Become a Champion” below:

***@***.***
This is the error message I get:

***@***.***

I don’t know where the ChampionManagementPlatform SharePoint site is to check if I have edit access to the Member list.

Thank you,

Heather Fischer
Senior Accountant, US Accounting Center

***@***.***
***@***.******@***.***>

Gallagher
2850 Golf Road, Rolling Meadows, IL 60008
www.ajg.com<http://www.ajg.com/>

**Comment by v-chpaladugu** [comment]
Hi @heather2552,
We are not able to see the screenshots you shared, so please reply through the Github.
Please check with the person who has setup the Champion Management Platform app whether you have edit access to the Member list, if not get the edit access to Member list from that person.
If this doesn't work, kindly share the screenshot of error from browser console window.
Follow the steps to see the error in console window:
1. Open CMP app in browser and try to replicate the issue.
2. Click F12 (sometimes Fn + F12) to get the console window.
3. Scroll down to bottom and capture the screenshot.
