### ISSUE TITLE
Digital Badge 

### ISSUE THREAD

**Issue by Artpillz** [OfficeDev/microsoft-teams-apps-champion-management#174]
Getting a message when trying to get Digital Badge
![Screenshot 2023-07-31 165433](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/9cf99c19-7f20-4271-985b-b3688f79be77)

**Comment by v-chpaladugu** [comment]
Hi @Artpillz ,
Thanks for reaching out to us. Can you confirm the below:
Please go to CMP SharePoint site and share the screenshot of 'Digital Badge Assets' document library (make sure you include all the columns in the screenshot).

**Comment by v-chpaladugu** [comment]
Hi @Artpillz,
Follow the below steps:
1. Please open the Champion Management Platform app in browser teams and try to replicate the issue.
2. Click F12 (sometimes Fn + F12) to get the console window, copy all the logs from the window.
3. Paste all the copied logs into a separate text file and share the file through Github.
please refer the link, to collect logs
[https://support.google.com/docs/thread/1873663/collecting-console-logs-chrome-browser-only?hl=en](url)

**Comment by Artpillz** [comment]
Fn+F12 is turning off my screens

**Comment by v-chpaladugu** [comment]
Hi @Artpillz ,
Can you try these steps to collect logs from console window.
1. Please try to access the CMP application in the browser version of MS Teams and open Developer tools from browser (or press Ctrl + Shift + I , this will open the developer tools window) and then select console tab to see the logs.
2. Open the Digital badge module and navigate to select a badge screen to replicate the issue.
3. Then right click on the Console window to Save it as a log file and share it across for further troubleshooting.

![cmp collect logs](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/c72ae491-5be6-4e31-b8c2-93df351c244f)

**Comment by Artpillz** [comment]
will do thank you

[teams.microsoft.com-1691170634143.log](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/12263238/teams.microsoft.com-1691170634143.log)

**Comment by v-chpaladugu** [comment]
Hi @Artpillz, 
It seems like you haven't opened Digital Badge Screen to collect logs. As I mentioned earlier, please open Digital Badge screen to save logs and share the file.

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/67e9ee5d-9d8b-4724-8c94-87673a3d6789)

Thanks
