### ISSUE TITLE
Can't Create Content in Champion Mangement

### ISSUE THREAD

**Issue by Artpillz** [OfficeDev/microsoft-teams-apps-champion-management#178]
I got the app working in Teams, but I am unable to create any content in Champion Management It doesn't translate to the app in Teams and this is probably.

**Comment by v-chpaladugu** [comment]
Hi @Artpillz,
Thanks for reaching out to us.
Can you please share the screenshot of CMP Home page and also share the screenshot of any error that you see.

Thanks.

**Comment by Artpillz** [comment]
If I add their Name here will give them full access to champion Management?
![Screenshot 2023-09-01 154222](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/5b059beb-a9e9-46c5-8fcb-6f1de23296e1)
![Screenshot 2023-09-01 134426](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/56ebc4c3-8b7f-4d77-97ac-5cc1bdb6773c)
 If I add their Name here will give them full access to champion Management?
![Screenshot 2023-08-31 120126](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/138717776/13dde71f-29e2-448d-82fa-5b92662f25d2)

**Comment by v-chpaladugu** [comment]
> If I add their Name here will give them full access to champion Management? ![Screenshot 2023-09-01 154222](https://user-images.githubusercontent.com/138717776/265137181-5b059beb-a9e9-46c5-8fcb-6f1de23296e1.png) ![Screenshot 2023-09-01 134426](https://user-images.githubusercontent.com/138717776/265137185-56ebc4c3-8b7f-4d77-97ac-5cc1bdb6773c.png) Adding their Name here too? ![Screenshot 2023-08-31 120126](https://user-images.githubusercontent.com/138717776/265137297-13dde71f-29e2-448d-82fa-5b92662f25d2.png)

Hi @Artpillz ,
This Will not give full access to CMP  Site. That list is used to store Admin roles of Tournament of Teams Section in CMP App.

**Comment by Artpillz** [comment]
Thank you so much for the information I will try and see if it works Thanks again

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Artpillz** [comment]
It work thank you and appreciate your help

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by v-chpaladugu** [comment]
Hi @Artpillz,
Glad it's working for you now.
Thanks for your interest in the app.

Thanks.
