### ISSUE TITLE
Error installing Copilot

### ISSUE THREAD

**Issue by JairoRepsol** [OfficeDev/microsoft-teams-apps-champion-management#179]
The user is using an admin account with an Office E3 license and global admin permissions. In addition, this account had to be granted access to the AppCatalog in SharePoint in order to enable the option to add apps.

In the first attempt, the customer did not have the E3 license assigned to the global admin, which is why they couldn't install CoE. The script displayed a message that said "Teams not found," and this is how I discovered that the requirements were not met.

For this reason, the customer followed the instructions following option B of the CoE installation process, successfully getting CoE installed without any issues.

The first time the Champions application was installed, the customer used another user with global permissions and an E3 license, reaching a point where everything became blocked. To rule out the possibility that the issue was related to not using the original admin user that was used to install CoE, the steps to uninstall the application and reinstall it using the original account used to install CoE were followed.

In this process, once the application is uploaded to SharePoint, we encountered this error capture. We disregarded this error, confirmed that all permissions were granted, and proceeded to install the application in Teams, where it remained permanently stuck in a loading state.

Currently, everything has been uninstalled following the installation guide's instructions, and on Monday, they will try again.

Key points to highlight:
- The customer followed option B to install CoE.
- The first time, two accounts were used, one for installing CoE and another for installing the Champions application.
- The application has been deleted according to the guide, and it has been reinstalled using the admin account that was used to install CoE.
- Permissions in Graph, assigned licenses, permissions in the app catalog, and the global admin role have all been checked.

**Comment by v-saikirang** [comment]
Hi @JairoRepsol ,

Thanks for reaching out to us.

Can you please share more details on the issue pertaining to CMP app only. Can you please delete the ChampionManagementPlatform sharepoint site if already created under both "Active" and "Deleted sites" from Sharepoint Admin center. Wait for an hour or so and then re install the app following the deployment guide.

If you still face any issues please share
1)  The screenshot of the APP when loading up
2) Screenshot of the "Site Contents" of the SharePoint site
3) Screenshot of the API permissions page from Admin center
4) Open the app as stand alone app in browser and share the console logs from the browser.

Thanks.

**Comment by JairoRepsol** [comment]
Hi @v-saikirang 

We have tried 2 times to uninstall everything and perform a complete cleanup by deleting the recycle site.

![Captura de pantalla 2023-10-05 162758](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/680a4567-422a-407a-8ec6-0b18f698e44c)
![Captura de pantalla 2023-10-05 162820](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/4b43340b-89e1-4404-ab4e-507aa073c4ec)
![Captura de pantalla 2023-10-05 162852](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/8db03bca-45e4-4112-86e6-4d2953dd40d8)
![Captura de pantalla 2023-10-05 162857](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/57a4dbe8-afad-4eb3-a225-88d7fad1e8a6)
![Captura de pantalla 2023-10-05 162951](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/695d2b01-3061-4405-a856-4a321baa2e08)
![Captura de pantalla 2023-10-05 163032](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/9082b6c9-8818-41df-ae05-7a268e577444)
![Captura de pantalla 2023-10-05 163106](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/168ce352-f097-497f-924f-0e01fac30563)
![Captura de pantalla 2023-10-05 163229](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/a014bb1d-f898-41da-b735-7cc5d0becd17)
![Captura de pantalla 2023-10-05 163334](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/91d38eb9-cc86-498f-bd29-0b2445be4696)

Thanks.

**Comment by v-saikirang** [comment]
Hi @JairoRepsol ,

Thanks for sharing the information.

May I know what do you mean by "option B of the CoE installation process". Trying to understand how is this related to Champion Management Platform app. When Champion Management App is installed and loaded for the first time it creates a new site called "Champion Management Platform". But i see a different site in your screenshot. can you please shed more light here.

Thanks.

**Comment by JairoRepsol** [comment]
Hi @v-saikirang 

Where is "option B of the CoE installation process".
We don't have this site "Champion Management Platform".

![Captura de pantalla 2023-10-05 170440](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/28b68865-728b-42cb-9b9e-84abfe8116f7)

Thanks.

**Comment by v-saikirang** [comment]
Hi @JairoRepsol 

This is what you mentioned in your first comment.

"For this reason, the customer followed the instructions following option B of the CoE installation process, successfully getting CoE installed without any issues.'

What is the url of the sharepoint site that you showed in the screenshot. 

Can you please search for just "champion" instead.

Thanks.

**Comment by JairoRepsol** [comment]
Hi @v-saikirang 

This is the option B https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Deployment-Guide#modern-app-catalog (Modern App Catalog) but we have tried it in modern and classic.

Site: https://repsol365.sharepoint.com/sites/CopilotCoE
App Catalog: https://repsol365.sharepoint.com/sites/1-IT-APPC

![Captura de pantalla 2023-10-06 134605](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/146854096/29dcdb02-5c36-4f27-9906-128a88338ffd)

Thanks.

**Comment by v-saikirang** [comment]
Hi @JairoRepsol ,

CMP installation cannot use an existing site for set up. It creates a specific site called "Championmanagmentplatform" automatically when you run the app for the first time and it then creates the supporting lists/data needed for the app.

But I see that you are trying to use an existing site https://repsol365.sharepoint.com/sites/CopilotCoE for the CMP set up. This scenario doesn't work as of now. For this you have to download, customize the code and generate your own custom package to suit your scenario.

So there might be 2 scenarios that might have happened here:
1) You installed the CMP app, then manually modified the URL of the site to  "sites/CopilotCoE".
2) The "championmanagementplatform" ended up under "Deleted Sites" section in SP admin center when you cleaned up. This will create a conflict and will not allow a new site to be created with same name.

Also please open Teams in browser, open the CMP app and share the browser console logs to check if we can find anything there. 

Please check and let me know if you need more information.
Thanks.
