### ISSUE TITLE
How to configure creation of the "Member List" on another site than the root site of the tenant?

### ISSUE THREAD

**Issue by jbienstman** [OfficeDev/microsoft-teams-apps-champion-management#18]
Hi,

I am able to change the name of the site collection that gets created by the App, but I can't find a way to change the location of the "Member List". This one always gets created in the https://tenantname.sharepoint.com/ root site, which I would like to change to an existing site collection.
I tried updating the "siteconfig.json" file, adding the "rootSideId" key (as shown in the screenshot on the deployment page) but provided the GUID of another (non root) site as value. However, it didn't work - the Member List still got created in the true root site of the SharePoint tenant.

Is there a way to control the location of the "Member List"?

Thank you in advance,

Kind Regards,

Jim

**Comment by eshwarmsft** [comment]
Hi @jbienstman  At this moment we are considering Member List creation at root level as there is limitation we see when tried to create at ChampionLeaderBoard Site level. So the code has limitations with Member List adding at sub site level as requested.

**Comment by jbienstman** [comment]
Hi @eshwarmsft - Understood that it is not possible now due to code limitations, Will it be possible in the future to change the location of the Member List?

**Comment by JoshLeporati** [comment]
@jbienstman this enhancement is planned for the next release, it will be located under the champion site by default. You would be able to modify the solution code to point it elsewhere as well.

**Comment by v-saikirang** [comment]
Hi @jbienstman, Thanks for your patience! We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by JoshLeporati** [comment]
@jbienstman with v1.2 the memberlist is now created in the same SharePoint site as all the other solution assets. As such, if you modify the sitecollection in the config and recompile the solution will install ALL assets (memberlist included) in the one site.
