### ISSUE TITLE
Copilot CoE API Permission

### ISSUE THREAD

**Issue by jscaion** [OfficeDev/microsoft-teams-apps-champion-management#181]
We find that the API permissions for the champion management platform are too permissive :

Microsoft Graph, User.ReadWrite 
Microsoft Graph, Sites.Manage.All 

Can you explain me why ? are there other possibilities ? Site.selected for example?

Let me know.

Regards.

**Comment by v-saikirang** [comment]
Hi @jscaion,

Microsoft Graph, Sites.Manage.All - This is for provisioning the site and supporting lists in sharepoint. We have already eliminated this in our next release. You can also remove this permission once you are done with app set up and after making sure the app is working fine.
Microsoft Graph, User.ReadWrite - This is for updating the user's office 365 profile picture through Digital Badge feature.

Please let me know if you need more information.
Thanks.
