### ISSUE TITLE
Can't start tournament of teams

### ISSUE THREAD

**Issue by apptemplatequestions** [OfficeDev/microsoft-teams-apps-champion-management#183]
Hi,
my customer wants to start using the tournament of teams functionality in the Champion Management app.
Unfortunately, the following error always appears when the admin tries to start the tournament:

<img width="902" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/69305126/86c61a24-82e6-40ad-b657-526b2aaeb25e">

Thank you for your help on this!

**Comment by v-chpaladugu** [comment]
Hi @apptemplatequestions,
Thanks for reaching out to us!
Can you please share the following files:
- Try to replicate the issue in browser version of Teams, click Ctrl+Shift+i to get console window opened and collect the logs as shown below and share it across for further troubleshooting.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/f237f6f6-35c4-4b14-92c2-aa70a867b838)

- Replicate the issue and collect the network traces as shown below and share the file.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/6f9b4085-559e-468a-b6eb-6d59eb5e23f4)

- Share the screenshot of site contents from CMP SharePoint site.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/c9cc84ec-e673-4065-9287-3beb8aebf301)

- Screenshot of 'Tournaments' list from CMP sharepoint site.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/cf1c88ab-a513-48ee-864d-483855f8dc4f)
