### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'toLowerCase')

### ISSUE THREAD

**Issue by rfoust** [OfficeDev/microsoft-teams-apps-champion-management#185]
I'm configuring the Copilot CoE and the champion management app works fine with my admin account, but when I try to access the channel tab using any other account, I get the error:

TypeError: Cannot read properties of undefined (reading 'toLowerCase')

It doesn't matter if the other account was added as a user in the app or not.  I've tried removing and reinstalling the tab/app/sharepoint data but the error persists. Note that the missing icon in the screenshot DOES show up after clicking OK.

![Screenshot 2023-11-08 at 9 45 15 PM](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/2991296/46ca5f55-9ddd-4431-9dd5-83d7672c49e3)

**Comment by v-chpaladugu** [comment]
Hi @rfoust,
Thanks for reaching out us.
Can you please share the following files:

- Try to replicate the issue in browser version of Teams, click Ctrl+Shift+i to get console window opened and collect the logs as shown below and share it across for further troubleshooting.
![Uploading Screenshot 2023-11-09 172021.png…]()
- Replicate the issue and collect the network traces as shown below and share the file.
![Screenshot 2023-11-09 172415](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/c08127eb-9543-4577-a6a7-364af4671122)
- Share the screenshot of site contents from CMP SharePoint site.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/9ec4aedb-973b-4c30-8af3-33047847b42a)
- Share the screenshot of 'Member List' in CMP SharePoint site.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/5e958401-e463-4d50-b1a6-9fdc040b342e)

Thanks.

**Comment by rfoust** [comment]
Sure, see attached. I also included a zip file with the log/har files.

![Screenshot 2023-11-09 at 8 25 51 AM](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/2991296/7c30923f-338e-45b3-9604-92693b28674e)
![Screenshot 2023-11-09 at 8 26 31 AM](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/2991296/adf6a1a0-7ab6-4a88-950b-47c1bb924958)
[teams-logs.zip](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/13308601/teams-logs.zip)

**Comment by rfoust** [comment]
Thanks for the feedback.  Can you explain that in more detail? The User.ReadWrite permission is already applied from what I can see:
![Screenshot 2023-11-10 at 8 11 53 AM](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/2991296/f0f1fc92-9164-4a49-9ee9-d70e1ac8fedc)

**Comment by v-chpaladugu** [comment]
@rfoust, Those are the permissions for Graph API access, but we need "Read" permission to be given to SharePoint root site for that particular user.
Please follow the steps to give Read access to User.
- Click this Url [https://prodduke.sharepoint.com/_layouts/15/user.aspx](url) and login with Admin account.
- Click this setting
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/4fb04803-7baf-45e0-9768-39954bd8f280)
- Choose the user you wanted to add and select "Read" Permission and Share the access.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/f83f6d61-9b3d-423e-8a49-e13c938c6922)
- Now Check CMP app again.

Thanks.

**Comment by v-chpaladugu** [comment]
> Hi @rfoust, This is the error that causing issue for user account to access profile properties from SharePoint. Since it doesn't have privilege to access logged in user email, it is throwing the error. Error: "GET https://prodduke.sharepoint.com/_api/SP.UserProfiles.PeopleManager/GetMyProperties 403 (Forbidden)"
> 
> Please provide "Read" access to User account from SharePoint and check again.
> 
> Thanks.

Hi @rfoust,
A small correction here, you need to give "Contribute" access to the user from SharePoint so that a Non champion user can access the app and also Admin can add him as a champion or User himself can raise a request to be a champion.
So "Read" access is not required instead give "Contribute" access to User from SharePoint.

**Comment by rfoust** [comment]
Still seeing the same error after adding the permission.  But doesn't that just affect the user's permission to the site?  Doesn't seem like that would modify the application's api permissions to read the user's profile, since that api call is a totally different URL.

**Comment by v-chpaladugu** [comment]
Hi @rfoust,
It is necessary to give at least "Read" permission to Sharepoint root site for all users, and which will not affect anything.
Can you please login with the User account which you have given "Read" access and hit this Url in a new tab
[https://github.com/OfficeDev/microsoft-teams-apps-champion-management/issues/url](url)

This should display screen like this
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/109651377/564e9b7c-096f-40d9-afc2-9882bbaa8f1f)

If not please share the screenshot of it.

Thanks

**Comment by v-saikirang** [comment]
Hi @rfoust,

I see the membership ship list has 2 accounts from seperate tenants. Can you please confirm which account is working and which one is not. And also may I know how you added the second account to the membership list. Ideally you should be adding people from Add Members option from the dash board. Please let us know.
Thanks.

**Comment by v-saikirang** [comment]
Hi @rfoust ,

I am closing this ticket since we didnt not get any response. Please re-open the ticket if you still have any issues.
Thanks.
