### ISSUE TITLE
Where to accept request to become a Champion

### ISSUE THREAD

**Issue by PrinceAdomako** [OfficeDev/microsoft-teams-apps-champion-management#186]
Hello, I have deployed the champions management app in my tenant with my adm account and synced it to Teams. But when I log in on Teams with my regularc accoutn and add the app, I am not an admin there. I have added my regular account as an owner of the sharepoint site that was created but I still cannot get my regular account to become an admin.

At he moment I have a request pending to make my regular account a champion but no idea where the request has gone or where i can approve this request. So I have 2 questions, where  can I manage these requests and where can I add an admin to the app? :) thanks

**Comment by v-saikirang** [comment]
Hi @PrinceAdomako,

Thanks for trying out the app. 

1) Log in to the app as admin
2) add your regular account as champion from the Add Member screen. If you have already done this proceed with next step.
3) Open "Members List" in SharePoint site and change the Role of your regular account to "Manager" by editing the list item.
4) now when you login with your regular account you should see the Admin Section.

Currently there is no way to add the admin from the app but we are already working on that feature and it should be part of one of our future releases.

Thanks.

**Comment by PrinceAdomako** [comment]
Hello ,

Thanks for your return, the issue is I cannot even log into the app as an admin. This is what I see when I am in the app on Team

[A screenshot of a computer  Description automatically generated]

And when I open, this, then I had the option to request to be a champion which I did.


[A screenshot of a computer  Description automatically generated]

On the sharepoint page, I see the request is pending but there is no option there to accept it.

[A screenshot of a computer  Description automatically generated]

**Comment by PrinceAdomako** [comment]
Just did thanks


Jisu

**Comment by v-saikirang** [comment]
Hi @PrinceAdomako 

Thanks for the screenshots. For some reason i dont see the admin account in the membership list. 

In any case for the regular account please change the Role to Manager and Status to Approved directly from the list.
Thanks.

**Comment by PrinceAdomako** [comment]
How can i change th erole to manager in the member list? There is no such option unfortunately

**Comment by PrinceAdomako** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/137994046/f1a6b3fe-1cd5-4713-b127-e81e0e192e74)

These are the options I get when i click on the role

**Comment by v-saikirang** [comment]
Click on "Edit in grid view" on the top ribbon and then change the values in the dropdown list for those 2 fields. 

Thanks.

**Comment by PrinceAdomako** [comment]
ok that seems to work thanks :)
