### ISSUE TITLE
Blue spinner spinning

### ISSUE THREAD

**Issue by ehsuyc** [OfficeDev/microsoft-teams-apps-champion-management#187]
Hello,

Not sure if this is the right place to get some help. This is the issue I'm having in my environment. I've followed the troubleshooting guide to check the permissions, etc. 

https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Troubleshooting#3-seeing-a-blue-spinner-spinning-for-a-while-without-showing-any-errors-same-behavior-remains-after-refresh

When I initially ran the PS script to create the site, all seemed well without errors. Later when I tried to delete the site to re-create it, I found out the site doesn't even exist in SharePoint Admin portal. Any idea is appreciated. Thank you.

Eugene

![2023-12-04 18_14_34-Photos](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/73055717/5c2f3f7a-60d9-4f0f-994b-95b1b5d86f9a)

**Comment by v-saikirang** [comment]
Hi @ehsuyc,

Thanks for reaching out to us.

Can you please refer to solutions discussed for a similar ticket and see if any one of them works for you. If not, please let us know.
https://github.com/OfficeDev/microsoft-teams-apps-champion-management/issues/185
Thanks.
