### ISSUE TITLE
Champion App with guest users

### ISSUE THREAD

**Issue by marcorocca1973** [OfficeDev/microsoft-teams-apps-champion-management#188]
Hello everyone
if I use Champ App with guest users (with Entra ID valid and E3 plan associated) I always receive this error (both in Teams web and client and SPO page).
I don't understand what's going on :(

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/22641502/296076ef-02ec-4f1a-a925-77faaf878a62)

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/22641502/664c4846-2ee7-4306-b9fa-864291a8cfc4)

**Comment by v-saikirang** [comment]
Hi @marcorocca1973,

Thanks for reaching out to us. Please allow us some time. We will try to replicate this issue and get back to you.
Thanks.

**Comment by marcorocca1973** [comment]
No news about this?

**Comment by v-saikirang** [comment]
Hi @marcorocca1973,

The app does not support guest users as of now. We have added this to our backlog and we will try to implement this in one of our future releases. Thanks for sharing the feedback on this.

Thanks.
