### ISSUE TITLE
Clarify Pre-requisites

### ISSUE THREAD

**Issue by bhargavshukla** [OfficeDev/microsoft-teams-apps-champion-management#19]
The steps to create the app package asks user to run npm install and gulp, however there are no mentions of installing NPM or Gulp in pre-requisites. 

Running latest version of NPM was resulting in failures when running npm install. Only using Node 10.24 from https://nodejs.org/en/download/releases/ fixed that issue.

To install gulp, I had to run npm install -g gulp .

The pre-requisites should provide reference to appropriate node.js version and download links as well as reference to command to install gulp so the steps don't fail and create confusion for someone who doesn't have developer background and is relying on instructions.

**Comment by eshwarmsft** [comment]
Hi @bhargavshukla  , 

Thanks for the feedback. Will be updating the readme file with the same.

**Comment by eshwarmsft** [comment]
@bhargavshukla  Updated pre-requisites

**Comment by JoshLeporati** [comment]
Thanks for updating this @eshwarmsft and for the feedback @bhargavshukla
