### ISSUE TITLE
Stuck Loading

### ISSUE THREAD

**Issue by JPGBC** [OfficeDev/microsoft-teams-apps-champion-management#190]
When trying to initiate, it keeps on loading in an infinite loop.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/154537894/f07ec096-b7b6-4234-9192-5081ca759e18)

Any solutions? tips?

**Comment by v-saikirang** [comment]
Hi @JPGBC,

Thanks for reaching out to us.

Can you please check this and see if it clears the issue.

https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Troubleshooting#3-seeing-a-blue-spinner-spinning-for-a-while-without-showing-any-errors-same-behavior-remains-after-refresh

Apart from this also check if the site collection is in "Active Sites" also. If yes, please navigate to the Share point site and share a screenshot of the "Site Contents" page. Can you also confirm if you approved the API permissions from Admin center as specified in the deployment guide. Please share a screenshot of the API Permissions page as well.

Thanks.
