### ISSUE TITLE
Stuck on loading after changing 'Members list' values prior to upload

### ISSUE THREAD

**Issue by DabHub2** [OfficeDev/microsoft-teams-apps-champion-management#191]
The Champions app is stuck on loading within MS Teams if we customise the Member list values following the customisation guidance. The 'Region' and 'Country' values aren't applicable to us, so we were wanting to amending these prior to uploading the app onto SharePoint.

If we upload the standard package it works fine, but if we amend config file to change the Members list values it gets stuck on loading. If we refresh the page when it's stuck, it returns the below error:

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/157139405/a8b1c558-f56e-4d64-ac34-c4f60406b87e)

All the lists appear fine within the SharePoint site, and adding the user into the members list gets the rest of the app to load but continues to show the above error for everyone that tries to access the app.

Please could someone advise what we're doing wrong?

APIs are all approved etc.

**Comment by v-saikirang** [comment]
Hi @DabHub2,

Thanks for reaching out to us.

Currently the only customization allowed with standard installation is as mentioned here in the [wiki](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Customizations#customize-member-list).

Any other changes would require changes in the code as well. Changing the config list value alone would not work. This means any changes you want to do, will have to be done with a custom version.

Please let me know if you need more information.
Thanks.

**Comment by DabHub2** [comment]
That's worked, thank you!

Apologies, I had only got as far as the section at the top where it mentions amending the .json.
