### ISSUE TITLE
Prevent champion from direct editing in SharePoint site and list values

### ISSUE THREAD

**Issue by wikitime** [OfficeDev/microsoft-teams-apps-champion-management#193]
During deployment, we added 'Everyone except external users' with Edit permission, granting 'Edit' permission to 'Everyone except external users' allows users including champions to modify the site and list values. If only 'Read' permission is granted, champions will be able to view content but not submit new items in the champion management platform, such as event records.

**Comment by v-saikirang** [comment]
Hi @wikitime,

Thanks for reaching out to us.

This is done as per design. If you need to restrict access please consider giving read access on the site and break down the permissions of the lists that needs contribute access. This way only few lists will have contribute access and rest of the site will read only. 

Please let us know if you need more information.

Thanks.

**Comment by wikitime** [comment]
Hi @v-saikirang,
Champions should have a read option only on site and lists too but then they can't submit events on the platform!!

**Comment by v-saikirang** [comment]
Hi @wikitime,

If the champions have Read only access on the lists as well, then they will not be able to submit any requests. This is as per design and expected. 

Thanks.
