### ISSUE TITLE
Leaderboard not showing any names - missing person profile information.

### ISSUE THREAD

**Issue by FleurWilliamson** [OfficeDev/microsoft-teams-apps-champion-management#195]
We recently set up the platform and most seems to be working without errors.  However the Leaderboard is not displaying the names or profile pictures.

![Screenshot 2024-04-09 180718](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/ebe41882-5356-4c8f-b63f-3e6d78930626)

The Members list seems to be completed in full.  However it seems a bit wrong to me that there are separate columns for FirstName and LastName and not a Person column to record a person selected from the address book.  How can we show a person profile if the list has no person column?

![Screenshot 2024-04-09 181259](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/c728af02-cd91-41a0-a7f5-62a57bb71072)

Did we miss a set up step?

**Comment by v-saikirang** [comment]
Hi @FleurWilliamson,

Thanks for reaching out to us.

I don't see anything wrong with the member list.

1) Can you please confirm if you have deployed the below package as well in your app catalog:
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/87538202/1846ca64-eb5f-423e-bc01-912ea0616fe7)

2) Can you please cross check the API permissions as per the deployment guide and share a screenshot of the API permissions page from your SP Admin center.
Thanks.

**Comment by Ben-Reg** [comment]
Quick update: I noticed Champions could see all of the names and profile pictures, but they weren't showing up for the user I had set as the manager.  I had added users using their login domain, so I tried switching them to their default address domain, and after that it seemed to work for everyone.

**Comment by FleurWilliamson** [comment]
Apologies for the late reply.
Yes I have the same App versions installed and enabled.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/06bbaaef-c73b-4655-b32e-b0b58d7b4711)

Thank you @Ben-Reg for confirming I'm not the only one.
I don't think we have different login domains and email domains in our organization.  Our logins are all the same as our emails.
And I have the same experience of missing names for both the accounts I added, one as an Admin, the other as a champion.  I will try adding some other users and see if they also see the same.

This is very concerning as I sold this program to the highest levels of our rather large business.  I hope that we can find a solution.

**Comment by FleurWilliamson** [comment]
I also noticed that as soon as I add a person the name does not show in the table.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/3d608709-0ff3-44a0-80c6-3d45e3536dd6)

**Comment by v-saikirang** [comment]
Hi @FleurWilliamson,

Can you please share a screenshot of

1) API permissions page
2) member list items

Also please open teams in browser and navigate to Add Member page and share the console log.

Thanks.

**Comment by FleurWilliamson** [comment]
Here are the screenshots:
API permissions page:
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/c1a937a7-2452-4263-8a4e-73335efb3ed8)

member list items:
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/7864aa35-7650-4e3c-8573-6dc0942eddd8)

Out tenant administrator who approved the API's also wrote this:
"I have added the permissions directly to the SharePoint Online Client Extensibility Web Application Principal"
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/6fff4465-1d0a-417f-b6b3-82c172b546d3)

We also tried uninstalling everything and reinstalling.
The console shows that it is a permissions issue, but we have not worked out why.
<img width="622" alt="image" src="https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/b476536c-dd4d-43ac-bf1c-f703e271dc4c">

**Comment by v-saikirang** [comment]
Hi @FleurWilliamson,

There seems to be a discrepancy with the API permissions. Can you please follow the step 13 from the [deployment guide](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Deployment-Guide). You would need below permissions only to make this work.

User.ReadWrite
User.Read.All
People.Read

Please make these changes and let me know if it worked.
Thanks.

**Comment by FleurWilliamson** [comment]
Thank you so much @v-saikirang 
My tenant admin added the **People.Read** permissions in the API - and that Partially fixed the issue.
He was able to see the image for his own account.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/80013204/addc1681-4d74-481e-8c68-07b7ac20b272)

Then he also added the **User.Read.All** permissions and he was then able to see images for other accounts as well
