### ISSUE TITLE
API access Permissions are not showing for approval

### ISSUE THREAD

**Issue by thomasdaggett** [OfficeDev/microsoft-teams-apps-champion-management#196]
After repeatedly trying I am still unable to see the championmanagement package permissions on my tenant API access page.  They neither show as approved or pending approval.  I have skipped this step but the solution does not seem to be working.  Is there a way to have the permissions to show or approve them outside of the API access page?  thanks thomas

**Comment by v-saikirang** [comment]
Hi @thomasdaggett,

Thanks for reaching out to us.

The API permissions should automatically show up when you deploy the package in the app catalog as per the deployment guide. Can you please remove the package and deploy again. Also please share a screenshot of the API permissions page.

Thanks.
