### ISSUE TITLE
Unable to be the admin of the champion portal 

### ISSUE THREAD

**Issue by vibhavrikhi1990** [OfficeDev/microsoft-teams-apps-champion-management#198]
Installed the necessary packages on the app store - SharePoint
Approved all the API permissions as suggested 
However, we're unable to see all the tiles and unable to be the admin of champ portal 
I'm the owner/site admin of the spo champion site as well. 
Reference screenshot!
![champion portal](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/130783135/d54c00fd-c330-4317-ab5d-dd1108a3f472)

**Comment by v-saikirang** [comment]
Hi @vibhavrikhi1990,
Thanks for reaching out to us.
Can you please share screenshot of "Members List" contents in SP site.
Thanks

**Comment by vibhavrikhi1990** [comment]
Please find the requested screenshots.
Also, while we give admin rights in the admin portal, it doesn't show the name in the champion management portal. 
![image (1)](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/130783135/98fa9817-b930-4a4a-b2a2-572bfe1a8384)
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/130783135/e6238ff6-4097-4a41-bc2a-8409c31a6edb)

**Comment by v-saikirang** [comment]
Hi @vibhavrikhi1990,

May I know why there are emails with 2 different domains and in which tenant is the app deployed.

Also can you check if the first person in the list with contractor email  is able to view the Admin dashboard. 
Can you also please share 
1) screenshot of the API permissions page 
2) Open the app in browser and share console logs.
Thanks.

**Comment by vibhavrikhi1990** [comment]
> Hi @vibhavrikhi1990,
> 
> May I know why there are emails with 2 different domains and in which tenant is the app deployed.
> 
> Also can you check if the first person in the list with contractor email is able to view the Admin dashboard. Can you also please share
> 
> 1. screenshot of the API permissions page
> 2. Open the app in browser and share console logs.
>    Thanks.

Yes Bhartendu singh is able to see the complete admin dashboard but apart from him nobody else. 
Axaltacs is our upn, and Axalta.com is primary email address.

**Comment by v-saikirang** [comment]
Hi @vibhavrikhi1990 ,

The issue is with different UPNs and email. For the below email in the Members list try changing the role to Manager and Status to Approved and check the dashboard.

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/87538202/ad856a25-d72f-445c-8b8e-f2372977e60c)

Thanks.

**Comment by vibhavrikhi1990** [comment]
> The issue is with different UPNs and email. For the below email in the Members list try changing the role to Manager and Status to Approved and check the dashboard.

Can you please share the screenshot, how to do that and from where?

**Comment by v-saikirang** [comment]
You can directly edit the list item in the Member list in SP and change those values.

Thanks.

**Comment by vibhavrikhi1990** [comment]
> You can directly edit the list item in the Member list in SP and change those values.
> 
> Thanks.

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/130783135/6b8b54b6-8387-463d-b466-155b54add9c6)


Remove both the entries and freshly add a new one with manager role, right?

**Comment by vibhavrikhi1990** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/130783135/d6823f11-1dc1-4dc3-aa94-76068374c782)

Done this, will it take sometime to reflect the admin rights?

**Comment by v-saikirang** [comment]
Hi @v-saikirang,

You should be adding your primary email address and not the UPN. Please edit the email.The change should reflect immediately.
Thanks.

**Comment by vibhavrikhi1990** [comment]
Perfect, you were right. That works :) However, I also, see we're unable to assign badges from the portal, what is the right way of doing it. please if you can tell

**Comment by v-saikirang** [comment]
Hi @vibhavrikhi1990,

Please refer to the "Digital Badge" section of the wiki - https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Solution-Overview#digital-badge
