### ISSUE TITLE
Champion managemant app issue in teams

### ISSUE THREAD

**Issue by watanabesara** [OfficeDev/microsoft-teams-apps-champion-management#199]
We deployed app in sharepoint and enable to all sites and teams. Champion management app is not working as expected.

**Comment by v-saikirang** [comment]
Hi @watanabesara,

Can you please share more details about the issue along with screenshots so we can help you.

Thanks.

**Comment by watanabesara** [comment]
Yes, see below:


SharePoint issue – Published a News Post, but it´s appearing with the wrong date and not showing at News Feed

I created this News post and published on 11/Jun: https://salesbridge.sharepoint.com/sites/BSAM-Digital%20Workplace/SitePages/Plugin-Drive-Change1.aspx

But this news post is not appearing as the last one at news

The most recent news was from last week (03/Jun)

[cid:07a57caa-188e-45b6-a60b-546c21fde52a]

If I click on See all:

https://salesbridge.sharepoint.com/sites/BSAM-Digital%20Workplace/_layouts/15/news.aspx?title=Tips%20-%20Acesse%20aqui%20as%20dicas%20de%20TI%20mais%20recentes&newsSource=1&instanceId=bd9126ac-9000-442b-b4e7-1a8533735cfc&webPartId=8c88f208-6c77-4bdb-86a0-0c47b4316588&serverRelativeUrl=%2Fsites%2FBSAM-Digital%20Workplace%2FSitePages%2FDW-Home.aspx&pagesListId=746fbd01-d0f7-4290-bee6-d6ddffc72351

The post from 11/Jun appears from 1. January. 1

 [cid:ca8bd6ad-5b3c-44cb-8153-7c66b2274438]

I found similar issue in another SharePoint, now at: BSAM Microsoft 365 Learning Center
https://salesbridge.sharepoint.com/sites/BSAM-BridgestoneOffice365UsersGroup/_layouts/15/news.aspx
Post also made per another user, see attached print screen
[cid:5fbc8a3e-43da-4d3d-9f8d-8046489d81df]



I made a post this week, and works fine. So it´s happening random.



Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: v-saikirang ***@***.***>
Enviado: quinta-feira, 20 de junho de 2024 05:32
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Watanabe, Sara ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)


Hi @watanabesara<https://github.com/watanabesara>,

Can you please share more details about the issue along with screenshots so we can help you.

Thanks.

**Comment by watanabesara** [comment]
***@***.*** would like to recall the message, "RE: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)".

**Comment by watanabesara** [comment]
sorry,  I sent a print from another issue....

Here is the correct print:

App is deployed but not loading....

[cid:7b81d0cf-7fa1-4d0f-a434-4fc4ebfb3170]




Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: Watanabe, Sara ***@***.***>
Enviado: quinta-feira, 20 de junho de 2024 08:05
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>; OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Mention ***@***.***>; SHUKLA Anvesh (External) ***@***.***>
Assunto: RE: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)

Yes, see below:


SharePoint issue – Published a News Post, but it´s appearing with the wrong date and not showing at News Feed

I created this News post and published on 11/Jun: https://salesbridge.sharepoint.com/sites/BSAM-Digital%20Workplace/SitePages/Plugin-Drive-Change1.aspx

But this news post is not appearing as the last one at news

The most recent news was from last week (03/Jun)

[cid:07a57caa-188e-45b6-a60b-546c21fde52a]

If I click on See all:

https://salesbridge.sharepoint.com/sites/BSAM-Digital%20Workplace/_layouts/15/news.aspx?title=Tips%20-%20Acesse%20aqui%20as%20dicas%20de%20TI%20mais%20recentes&newsSource=1&instanceId=bd9126ac-9000-442b-b4e7-1a8533735cfc&webPartId=8c88f208-6c77-4bdb-86a0-0c47b4316588&serverRelativeUrl=%2Fsites%2FBSAM-Digital%20Workplace%2FSitePages%2FDW-Home.aspx&pagesListId=746fbd01-d0f7-4290-bee6-d6ddffc72351

The post from 11/Jun appears from 1. January. 1

 [cid:ca8bd6ad-5b3c-44cb-8153-7c66b2274438]

I found similar issue in another SharePoint, now at: BSAM Microsoft 365 Learning Center
https://salesbridge.sharepoint.com/sites/BSAM-BridgestoneOffice365UsersGroup/_layouts/15/news.aspx
Post also made per another user, see attached print screen
[cid:5fbc8a3e-43da-4d3d-9f8d-8046489d81df]



I made a post this week, and works fine. So it´s happening random.



Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: v-saikirang ***@***.***>
Enviado: quinta-feira, 20 de junho de 2024 05:32
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Watanabe, Sara ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)


Hi @watanabesara<https://github.com/watanabesara>,

Can you please share more details about the issue along with screenshots so we can help you.

Thanks.

**Comment by v-saikirang** [comment]
Hi @watanabesara,

I am not able to see the screenshot. Can you please respond directly from github site instead of email which might be blocking the images.

Thanks.

**Comment by watanabesara** [comment]
attached the print 
![20240620erro-champion-manag](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173168310/3411951c-5a24-4a1f-8c1b-292dab0f8db6)

**Comment by v-saikirang** [comment]
Hi @v-saikirang,

Can you please share below:

1) screenshot of the "Sitecontents" page of the sharepoint site "championmanagementplatform"
2) screenshot of the API permissions page
3) Have you provided contribute access in SP site to the user.
4) Are you opening this app as global admin.
Thanks.

**Comment by watanabesara** [comment]
adding  Anvesh, can you please provide the requested info ?

Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: v-saikirang ***@***.***>
Enviado: quinta-feira, 20 de junho de 2024 10:40
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Watanabe, Sara ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)


Hi @v-saikirang<https://github.com/v-saikirang>,

Can you please share below:

  1.  screenshot of the "Sitecontents" page of the sharepoint site "championmanagementplatform"
  2.  screenshot of the API permissions page
  3.  Have you provided contribute access in SP site to the user.
  4.  Are you opening this app as global admin.
Thanks.

**Comment by watanabesara** [comment]
Hi @v-saikirang<https://github.com/v-saikirang>,

Could you please schedule meeting b/w 2PM to 9PM IST to discuss on this.

 App has been deleted would like deployment via screenshare.

Thanks and Regards,
Anvesh Shukla

  | Website: http://www.tcs.com<http://www.tcs.com/>

====================================================

[A picture containing logo  Description automatically generated]

________________________________
From: Watanabe, Sara ***@***.***>
Sent: Thursday, June 20, 2024 7:13 PM
To: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>; SHUKLA Anvesh (External) ***@***.***>; OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)

adding  Anvesh, can you please provide the requested info ?

Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: v-saikirang ***@***.***>
Enviado: quinta-feira, 20 de junho de 2024 10:40
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Watanabe, Sara ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)


Hi @v-saikirang<https://github.com/v-saikirang>,

Can you please share below:

  1.  screenshot of the "Sitecontents" page of the sharepoint site "championmanagementplatform"
  2.  screenshot of the API permissions page
  3.  Have you provided contribute access in SP site to the user.
  4.  Are you opening this app as global admin.
Thanks.

**Comment by v-saikirang** [comment]
Hi @watanabesara,

Can you also please change the teams language to english. You can revert after the set up is complete.

Thanks.

**Comment by watanabesara** [comment]
adding @SHUKLA Anvesh ***@***.***>

Dear Anvesh, can you please try the steps below ? as I don´t have access to admin center. Thx

Attached the guide, from the link that was shared




Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: v-saikirang ***@***.***>
Enviado: quinta-feira, 20 de junho de 2024 11:07
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Watanabe, Sara ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)


Hi @watanabesara<https://github.com/watanabesara> ,

Can you please try the below:

  *   Delete 'ChampionManagementPlatform' SharePoint site from both 'Active Sites' and 'Deleted Sites' from SharePoint admin center.
  *   Cross check all the steps mentioned in the deployment guide - https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Deployment-Guide
  *   Wait for 30 mins and try reopening the app using global admin account.

Thanks.

**Comment by watanabesara** [comment]
Hello @v-saikirang<https://github.com/v-saikirang>,

We have performed the steps as requested however we request you to schedule call b/w 2PM to 9PM IST.

Thanks and Regards,
Anvesh Shukla

  | Website: http://www.tcs.com<http://www.tcs.com/>

====================================================

[A picture containing logo  Description automatically generated]

________________________________
From: Watanabe, Sara ***@***.***>
Sent: Friday, June 21, 2024 12:15 AM
To: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>; OfficeDev/microsoft-teams-apps-champion-management ***@***.***>; SHUKLA Anvesh (External) ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)

adding @SHUKLA Anvesh ***@***.***>

Dear Anvesh, can you please try the steps below ? as I don´t have access to admin center. Thx

Attached the guide, from the link that was shared




Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: v-saikirang ***@***.***>
Enviado: quinta-feira, 20 de junho de 2024 11:07
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Watanabe, Sara ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)


Hi @watanabesara<https://github.com/watanabesara> ,

Can you please try the below:

  *   Delete 'ChampionManagementPlatform' SharePoint site from both 'Active Sites' and 'Deleted Sites' from SharePoint admin center.
  *   Cross check all the steps mentioned in the deployment guide - https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Deployment-Guide
  *   Wait for 30 mins and try reopening the app using global admin account.

Thanks.

**Comment by v-saikirang** [comment]
Hi @watanabesara,

Please share your email. I will send out an invite for 5 pm today.
Thanks.

**Comment by watanabesara** [comment]
please include @SHUKLA Anvesh ***@***.***> on the invite

"SHUKLA Anvesh (External)" ***@***.***> he has all necessary access.




Regards,

Sara



note: I´m sending this in a slot that's convenient for me, but feel free to respond at a time that's convenient for you, considering your time zone.

Planned OOO: 08 & 09/July

________________________________
De: v-saikirang ***@***.***>
Enviado: sexta-feira, 21 de junho de 2024 07:05
Para: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Watanabe, Sara ***@***.***>; Mention ***@***.***>
Assunto: Re: [OfficeDev/microsoft-teams-apps-champion-management] Champion managemant app issue in teams (Issue #199)


Hi @watanabesara<https://github.com/watanabesara>,

Please share your email. I will send out an invite for 5 pm today.
Thanks.

**Comment by watanabesara** [comment]
here is 
"SHUKLA Anvesh (External)" <anvesh.shukla.ext @ bridgestone.eu> he has all necessary access.

**Comment by v-saikirang** [comment]
Sent the invite for 5 PM.
Thanks.

**Comment by v-saikirang** [comment]
Hi @watanabesara,

As per my call with Anvesh below is the summary:

1) API permissions and Sharepoint site access to "Everyone" was missing in the current set up.
2) Once we fixed the above issues Anvesh was able to open the app as Manager.

Please refer to the "Solution Overview" wiki in git hub for more details on the App features.

Thanks.
