### ISSUE TITLE
Provide a way to add Manager and manage approvals

### ISSUE THREAD

**Issue by bhargavshukla** [OfficeDev/microsoft-teams-apps-champion-management#20]
Currently it isn't clear from instructions that the manager and champion roles must be assigned manually through Champions List. 

For a user not familiar with SharPoint wouldn't know how to manage approvals or change assign manager role to others.

It would be better if the app can provide a way to manage approvals and champion/manager role assignments directly in Teams app.

**Comment by JoshLeporati** [comment]
@bhargavshukla thank you for the feedback here, approvals are still currently located in the List location and for the time being will be managed from that location. Additionally you could build a powerautomate to send approvals via approval app in Teams and update the column from pending to approved (or even champion status). I'll look to publish a blog article outlining that potential to shed some insights on it for others as well.

There could be some elements where the list can be pinned into a management channel or access from the List app itself as well.

**Comment by JoshLeporati** [comment]
@bhargavshukla - also one other update here, there is an approval process in app to complete this process. The app (v1.2) has manage approvals button, selecting that will allow to approve from there or reject from there. It is updating the status field in the list for members.

**Comment by bhargavshukla** [comment]
Thank you @JoshLeporati that is fantastic news!
