### ISSUE TITLE
Icons/Images not displaying

### ISSUE THREAD

**Issue by SamB1209** [OfficeDev/microsoft-teams-apps-champion-management#200]
I have just configured and installed the Champion Management Platform for our organisation, however the icons/images on the home screen in Teams (both desktop and web app) are not pulling through and are displaying a 'broken link' icon with alt text:

![Champion Management](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/3c621142-f4ae-4d76-be22-2e03bb1724d0)

**Comment by v-saikirang** [comment]
Hi @SamB1209 ,

Thanks for reaching out to us.

May I know is this a new installation.

Thanks.

**Comment by SamB1209** [comment]
Hi, yes this is a new installation. Thanks

**Comment by v-saikirang** [comment]
Hi,

Can you try uploading the the package again in the app catalog and open the app in a new incognito browser and check.
Thanks.

**Comment by SamB1209** [comment]
Hi, I have tried this but am still getting same issue. See screenshots:

![app catalog](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/408b78c5-51bd-4305-a341-d5553b622284)

![incognito](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/7c4b21ae-8eed-4a47-a447-595186707d11)

**Comment by v-saikirang** [comment]
Hi @SamB1209,

We didn't see this issue encountered by any one so far. We will have to try to replicate this on our end and see. We will keep you posted if we find some thing.
Thanks.

**Comment by SamB1209** [comment]
I have looked in dev tools for one of the image sources, and tried to search for this in the browser, and it is coming back with an Access Denied error if that helps? Screenshot below (I have hidden our tenant from screenshot):

![2024-06-19_11-27-12](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/775700b0-c031-45ca-92c5-8f24bcce2eac)

**Comment by v-saikirang** [comment]
Hi @SamB1209,

Can you please check and confirm whether you have CDN enabled in your tenant and has */CLIENTSIDEASSETS origin in the Public CDN? 
Refer: https://learn.microsoft.com/en-us/sharepoint/dev/spfx/enable-microsoft-365-content-delivery-network?tabs=msposh#get-the-microsoft-365-cdn-status

**Comment by SamB1209** [comment]
Hi @v-saikirang , yes it looks like we have both:

![2024-06-20_09-35-28](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/d88c7e05-e88e-4301-94a9-a6aedcc2db09)

**Comment by v-saikirang** [comment]
Hi @SamB1209,

Can you replace the public CDN URL with your tenant url and see if you are able to access the images.
And also can you share any related errors in console.

Thanks.

**Comment by v-saikirang** [comment]
Hi @SamB1209,

I think i found the issue. if you see the last command in your screenshot, SVG file is not under included file extensions. And most of the images used in the app are SVG files. Please try including.
Thanks.

**Comment by SamB1209** [comment]
Hi @v-saikirang , yes I can access them within our tenant manually (they are all in this folder):

![assets](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/82cd18c6-80aa-44f8-8b65-044e7d086f49)

Console error is also below:

![2024-06-20_11-39-09](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/83c7bc35-989a-40ed-a5da-2f48752fa152)

**Comment by SamB1209** [comment]
> Hi @SamB1209,
> 
> I think i found the issue. if you see the last command in your screenshot, SVG file is not under included file extensions. And most of the images used in the app are SVG files. Please try including. Thanks.

I did think this but when running "Get-SPOTenant", SVG file type is listed under allowed file types:

![CDN](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/dde4e7fe-123d-4e19-a56a-287f8f5fab7f)

Nevertheless, I have just added the SVG file type as an allowed file type followed by the Get_SPOTenantCdnPolicies, it looks like a spelling error as it is listing SCG rather than SVG (as per my first screenshot)

![cdn2](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/b8fd3c44-c774-4b2b-a594-4edac8186042)

**Comment by v-saikirang** [comment]
Please confirm if its working now.

**Comment by SamB1209** [comment]
Nope still not working, getting same error. However, since manually adding SVG file type, I can see that is now included in the list:

![cdn3](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/173253859/31fb4aed-20a5-4db7-94db-f8ac51fd54d1)

**Comment by v-saikirang** [comment]
Hi @SamB1209,

I am not able to replicate the issue in our tenant with the CDN turned on. This seems to be a tenant specific issue.
Thanks.

**Comment by v-saikirang** [comment]
Hi @SamB1209,

What is the URL of the location where you directly accessed the assets.

**Comment by SamB1209** [comment]
The direct URL to the assets folder is:

<tenant_name>.sharepoint.com/sites/apps/ClientSideAssets/5099a3ef-113f-4baf-bb6a-a73b1dd286f8/

I can also get a ticket logged with Microsoft if you think it is an issue with our tenant.

**Comment by v-saikirang** [comment]
Hi @SamB1209,

I was able to replicate this issue when i removed SVG from the included file extensions. When i included SVG it started working again. I was not able to replicate this earlier because the "Set-SPOTenantCdnPolicy" has taken some time to take effect. Any update on your side?
Thanks.

**Comment by SamB1209** [comment]
Hi @v-saikirang , unfortunately we are still getting access denied. I have opened a ticket with Microsoft and am awaiting an update from them following an initial troubleshooting call. Thanks
