### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by preetamashetty** [OfficeDev/microsoft-teams-apps-champion-management#201]
I followed the deployment steps for Champion Management App, but when launching it on teams I am seeing the below error :

Something went wrong
If the problem persists, contact the site administrator and give them the information in Technical Details.
TECHNICAL DETAILS
ERROR:
Script error for: 78b11c7d-7ca8-47cb-a93c-d3beabb519a1_3.1.3
http://requirejs.org/docs/errors.html#scripterror

CALL STACK:
Error: Script error for: 78b11c7d-7ca8-47cb-a93c-d3beabb519a1_3.1.3
http://requirejs.org/docs/errors.html#scripterror
    at B (eval at e (https://res-1.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_feafccd8d41dd7dad5f809fdf5a17da4.js:127:10298), <anonymous>:8:252)
    at HTMLScriptElement.onScriptError (eval at e (https://res-1.cdn.office.net/files/sp-client/teams-web-part-application-assembly_en-us_feafccd8d41dd7dad5f809fdf5a17da4.js:127:10298), <anonymous>:30:244)

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Can you please open teams in browser and share console logs.

And also share a screenshot of the error that you see in the app.

Thanks,
Sai.

**Comment by preetamashetty** [comment]
The App works fine on the browser 

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/ae7bb46f-92da-41f6-8e69-53dd5d4fa83e)

The issue is with the Teams Client as well as mobile (tested both the new teams and classic teams client on desktop, tried clearing cache too but the issues persists)

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/81dc7a80-b413-44f6-82ad-14e8341f5713)

**Comment by v-saikirang** [comment]
@preetamashetty,

May i know which version of the app have you installed.

Thanks.

**Comment by v-saikirang** [comment]
@preetamashetty

Can you also confirm if you saw this error earlier on browser too.

Thanks.

**Comment by preetamashetty** [comment]
I have Microsoft Teams version 24137.2216.2931.2440.

And Champion Management Platform
Published by Teams Customer Advocacy Group
Version 2.6.0

**Comment by v-saikirang** [comment]
@preetamashetty 
Can you also confirm if you saw this error earlier on browser too.
Thanks.

**Comment by preetamashetty** [comment]
I am afraid I didnt check that before reporting this issue, and tried the app on browser only today, even today on the browser i dont see the default digital badges or champ icons, I did upload through sharepoint, but even they dont show

**Comment by v-saikirang** [comment]
@preetamashetty ,

Can you please share a screenshot of the site contents page of the SP site.

**Comment by preetamashetty** [comment]
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/ffc6469f-61e0-458a-9e20-f36cd6184dd5)

**Comment by preetamashetty** [comment]
The one item in Digital Badge Assets was uploaded by me

**Comment by v-saikirang** [comment]
@preetamashetty,

Ideally there should be one default image already uploaded. Any way can you share a screenshot of the library contents.

And can you please share a screenshot of what you see on Digital Badges in app.
Thanks

**Comment by preetamashetty** [comment]
This was something that I uploaded

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/354e38fb-a2c7-4926-bee2-1d86a9b9a4cf)

Site Contents

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/5a62dd77-240b-4f18-b8d2-16e6e30d4088)

Config Contents

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/d61ffde5-e600-4a81-a077-cf47c0949d5b)

And this is what I have under badges

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/58b02a16-89df-4124-8190-0bfbaae66262)

**Comment by v-saikirang** [comment]
Hi @preetamashetty ,

Can you please delete the "Digital Badge Assets" library, open the app in browser. When the app loads this "Digital badge assets" library is created along with the default badge. Now, check the digital badge screen in the app. If you still see the issue Share console logs from the browser while you are still on the Digital Badge screen.
Thanks.

**Comment by preetamashetty** [comment]
Tried that but still no Digital Badge or CMP Logo, though the folders got created automatically, attached console logs
[teams.microsoft.com-1719929427854.log](https://github.com/user-attachments/files/16069760/teams.microsoft.com-1719929427854.log)

**Comment by preetamashetty** [comment]
Deleted the "Digital Badge Assets" library, and opened the app in browser. When the app loaded the "Digital badge assets" library was created but without the default badge.

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Please try one more time. And if it still doesn't have the default image, please upload a picture and navigate to digital badge and share the console logs.
Thanks.

**Comment by preetamashetty** [comment]
Digital Badge Folder deleted from the SharePoint Site

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/6548d232-63c2-46cf-a365-610b394fd294)

Logged into Teams Web

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/6d117f1e-0e49-414d-96d3-273a4f4b9cfa)

Launched the Champion Management App

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/8a2c720e-fc5c-4c1d-ab08-424eba6bd3a0)

Clicked on Digital Badge and clicked on Accept

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/65142779-80e4-4c47-a669-92477a8d7302)

No Badges found

![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/174041043/fe343ac2-51db-410f-8e31-c8807fcdc303)

**Comment by v-saikirang** [comment]
Hi @preetamashetty,
I don't see the "DigitalBadgeAssets" library in the screenshot. Can you please run the app in browser and open the app with Tenant Admin account. Ideally when you open the app it should automatically create "DigitalBadgeAssets" library without which the digital badge will not work.
