### ISSUE TITLE
Badge not show when Set minimum point 

### ISSUE THREAD

**Issue by Joven-B** [OfficeDev/microsoft-teams-apps-champion-management#202]
I have set mininum point of badge to 2000 point (ex.) . When user completed the action till give more 2000 point in dashboard. user still can not claim the badge.
![badge](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/175178578/373bc721-df82-4a11-a511-1933547ac551)
![badge](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/175178578/f4af7663-4b23-4ecc-a3fc-ad2530e6fa44)
![point2](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/175178578/5c952d43-b125-45f3-9650-c6203a9e9622)

**Comment by v-saikirang** [comment]
Hi @Joven-B,
The Digital Badge points limit only applies to the CMP points and not Tournament of Teams. You have to earn points in CMP from Leaderboard to be eligible for the badges which are not tied to a tournament and has points limit. If a digital badge is mapped to a Tournament then the user will have to complete that tournament to be eligible for the badge.

Please check the[ Digital Badge](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Solution-Overview#digital-badge) section in the wiki for more details and let us know if you need more information.

Thanks.

**Comment by Joven-B** [comment]
Hi @v-saikirang 
My digital badge is mapped with point, I'm not sure anything was wrong of me.
![badge-point](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/175178578/c1c11c39-fcb4-42aa-8a6e-2ddaad79354a)

**Comment by v-saikirang** [comment]
Hi @Joven-B,

I see these badges are not mapped to any tournament. This means these points should be earned in CMP from leader board screen. The points in the tournaments will not apply here.
![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/87538202/565708ce-244c-49e0-a87f-27de64bc67c2)


![image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/assets/87538202/9e4f5103-8306-4674-875c-e56b12d23ffe)
