### ISSUE TITLE
Following up from my issues #201

### ISSUE THREAD

**Issue by preetamashetty** [OfficeDev/microsoft-teams-apps-champion-management#203]
The issue with the Digital Badge Assets Directory being empty continues, I am not sure if this is related to any permission issues, but I am the Global Tenant Admin so ideally that shouldnt be a problem, is there a way we can get on a troubleshooting call.

I tried deleting the app, the sites both from active and deleted sites, and re did the entire process, but the issue continues

See below

![image](https://github.com/user-attachments/assets/78ad857f-8611-4c6b-af85-199a51cde703)

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Thanks reaching out to us.

Can you please upload this[ image](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/blob/main/src/webparts/clbHome/assets/images/CMPBadge.png) to the "Digital Badge Assets" library and try opening teams in browser. 

![image](https://github.com/user-attachments/assets/b13ba952-b94f-4465-b785-79dee3b61ebe)


If it still doesn't work please open the Digital Badge screen and share the console logs from the browser so we can further investigate. Also share the screenshot of contents in "Digital Badge Assets".
Thanks.

**Comment by preetamashetty** [comment]
Hi,

I saw the badge when I uploaded it manually, now when I try to access the Champion management app via web browser, I see the below error

***@***.***

And my issue with team desktop app continues,

***@***.***
Thanks,

Preetam Shetty | McLarens
Senior Director of IT Infrastructure and Operations
***@***.******@***.***>
Remote - India
www.mclarens.com<http://www.mclarens.com/>

**Comment by preetamashetty** [comment]
After multiple refreshes, this is what I see on the browser

***@***.***

Thanks,

Preetam Shetty | McLarens
Senior Director of IT Infrastructure and Operations
***@***.******@***.***>
Remote - India
www.mclarens.com<http://www.mclarens.com/>

From: Preetam Shetty
Sent: Wednesday, August 28, 2024 5:46 PM
To: OfficeDev/microsoft-teams-apps-champion-management ***@***.***>; OfficeDev/microsoft-teams-apps-champion-management ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [OfficeDev/microsoft-teams-apps-champion-management] Following up from my issues #201 (Issue #203)

Hi,

I saw the badge when I uploaded it manually, now when I try to access the Champion management app via web browser, I see the below error

***@***.***

And my issue with team desktop app continues,

***@***.***
Thanks,

Preetam Shetty | McLarens
Senior Director of IT Infrastructure and Operations
***@***.******@***.***>
Remote - India
www.mclarens.com<http://www.mclarens.com/>

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Can you please directly share the images here in Git hub. Images sent through email are getting masked.
And as requested please share the console logs which will help us to investigate.

Thanks.

**Comment by preetamashetty** [comment]
This is the error I am getting both on Teams Desktop Client 

![image](https://github.com/user-attachments/assets/8aa69d62-b447-4f82-bd9e-a5109d4b1827)

And this what I see on the browser

![image](https://github.com/user-attachments/assets/edcf3361-672f-48ee-8f91-40e18ecdad59)

**Comment by preetamashetty** [comment]
Can I send the console logs privately

**Comment by preetamashetty** [comment]
[teams.microsoft.com-1724863426441.log](https://github.com/user-attachments/files/16786522/teams.microsoft.com-1724863426441.log)

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Thanks for sharing the logs.

Can you please confirm if you have CDN enabled in your tenant.

Thanks.

**Comment by preetamashetty** [comment]
Dear Sai,

No we don't have CDN enabled on our tenant


Thanks,



Preetam Shetty | McLarens

Senior Director of IT Infrastructure and Operations

***@***.******@***.***>

Remote - India

www.mclarens.com<http://www.mclarens.com/>

________________________________

**Comment by v-saikirang** [comment]
Hi @preetamashetty ,

Another user had similar issue and it turned out they had CDN enabled. Can you please check this [issue ](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/issues/200) and share screenshots by running those commands:

![image](https://github.com/user-attachments/assets/a2c0f7db-6c04-48ab-99ec-b06466dd4858)

**Comment by preetamashetty** [comment]
![image](https://github.com/user-attachments/assets/3003e1a7-e0fe-4a27-b04e-c0d98fe0c5b4)

CDN is disabled

**Comment by preetamashetty** [comment]
For some odd reason, teams web is working fine now, its only with desktop client, that I am seeing this error

![image](https://github.com/user-attachments/assets/4bcfa002-a118-4510-a946-d4f81ab13f97)

Teams Web

![image](https://github.com/user-attachments/assets/f870d30f-c279-4329-825f-8318129934df)

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Can you please try clearing your teams cache, sign out and sign in.

And can you also try opening the App directly from Apps section.

Thanks.

**Comment by preetamashetty** [comment]
Did everything, cleared cache, reset the app, sign out and sign in and finally uninstall and reinstall the app, same issue

***@***.***

Thanks,

Preetam Shetty | McLarens
Senior Director of IT Infrastructure and Operations
***@***.******@***.***>
Remote - India
www.mclarens.com<http://www.mclarens.com/>

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Can you please share your email and availability for a Teams call. We are usually available during 10:00 AM - 7:00 pm IST.
Thanks.

**Comment by preetamashetty** [comment]
Can we do this call on Monday 3 pm IST, my email address is ***@***.******@***.***>


Thanks,

Preetam Shetty | McLarens
Senior Director of IT Infrastructure and Operations
***@***.******@***.***>
Remote - India
www.mclarens.com<http://www.mclarens.com/>

**Comment by v-saikirang** [comment]
Hi @preetamashetty,

Can you please share your email in github.

Thanks.
