### ISSUE TITLE
ToTs -ability to easily publish for different groups

### ISSUE THREAD

**Issue by wendytschida** [OfficeDev/microsoft-teams-apps-champion-management#204]
My organization may want to run more than one Tournament at a time, and one might be geared towards only the members of the support group and knowledge sharing or something.  The other one might be geared towards the security group and have to do with something in their realm. However it doesn't pertain to the whole org or both groups. Without painfully messing with the SharePoint list permissions, an easy way to select which champions have access to which tournament when you create it - and then they are the only ones who see the tournament activities to do, etc, would be nice.

**Comment by v-saikirang** [comment]
Hi @wendytschida,

Thanks for your feedback. Currently there is no permissions mapped to a tournament. Anyone can participate in any app. You can consider customizing the app from your end to implement this additional security.  We will try assess and check the feasibility of this in future if possible. 

Thanks.
