### ISSUE TITLE
The Champion management app does not open in Teams

### ISSUE THREAD

**Issue by yogeshtech11** [OfficeDev/microsoft-teams-apps-champion-management#205]
Hello Team, 

We have deployed the Champion Management network application in SharePoint and Teams, however, whenever we try to open the app in Teams, it shows an error of Something went wrong. 
![Error](https://github.com/user-attachments/assets/facddfcd-e1d6-4733-9f4e-8295e7db40d1)

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

Thanks for reaching out to us.

1) Have you opened the app for the first time with a global admin account
2) Can you check if the share point site collection "championmanagementplatform" got created in SP admin center. If yes, please share a screenshot of the site contents.
3) Have you added "Everyone" to the SP site under "Members" group
4) Can you share a screenshot of the API permissions approved in SP admin center. 
5) Please go through the deployment guide and cross check each step.

Thanks.

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

As per the deployment guide i don't see the "User.Read.All" permissions in the screenshot you shared. Can you confirm this is missing. If yes, you will to delete the package from APP catalog and re publish  so the permissions will appear in API page.

Thanks,
Sai.

**Comment by yogeshtech11** [comment]
Hello @v-saikirang , 

I tried to redeploy the package but I still do not see the user.read.all permission there. Can we connect over Teams and check it together?

Regards, 

Yogesh Agrawal

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

You need to see these 3 permissions under Pending Request when you deploy the package.

![image](https://github.com/user-attachments/assets/eb529c11-7827-46bc-9447-d4bc639d6aaf)

1) Please remove the 2 instances of  "User.ReadWrite" permissions which is listed twice as per your screenshot.
2) Try the steps again.
3) Share a screenshot of all the API permissions in both Pending and Approved sections.

Thanks.

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

I am closing this ticket since we didn't get any response. Please feel free to reach out to us for any further issues.
Thanks.

**Comment by yogeshtech11** [comment]
Hello Team, Is there any way to completely remove the current setup and deploy it again?

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

Please refer to the[ Step 3](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/wiki/Troubleshooting#2-i-see-an-alert-that-says-an-unexpected-error-occurred-while-setting-up-the-app-please-try-refreshing-or-loading-after-sometime-during-first-run-experience) in the wiki.

Thanks

**Comment by AdLSacredDanielCurilIndiumPohl** [comment]
geh zu @microsoftopensource , Spreche

**Comment by yogeshtech11** [comment]
I tried to remove the app and tried add again, but I am unable to enable it. Please see the screenshot below. It works perfectly fine with another tenant. 

<img width="959" alt="Image" src="https://github.com/user-attachments/assets/95d65024-2776-4058-94de-71bee6bfc30b" />

**Comment by AdLSacredDanielCurilIndiumPohl** [comment]
Its Not ready :) its under construction:)

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

This does not look in issue with app specifically. This might be something related to your tenant since you are able to install it other tenant. 

Were you abe to install the app earlier in the same tenant. If yes, please remove the app completely and try again. If not, it could be related to App policies in your tenant. Please check.

**Comment by yogeshtech11** [comment]
It was there earlier and I had removed it as per the steps you provided earlier. I tried to remove the app from SharePoint and Teams.

**Comment by yogeshtech11** [comment]
@v-saikirang, can you please help?

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

Please try removing the app from the Teams Admin center.

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

Please try to repeat all the steps for re installation i shared earlier.

**Comment by yogeshtech11** [comment]
Hello @v-saikirang, the app is already removed from the Teams Admin center and I had already followed the steps, but it is not working, in meanwhile, I have raised a ticket with MS to check if there is any issues with tenant and app policies.

**Comment by v-saikirang** [comment]
Hi @yogeshtech11,

Please mention in the ticket that you are able to deploy the app in other tenant.
Thanks.
