### ISSUE TITLE
Questions-Contact

### ISSUE THREAD

**Issue by CyberRealm24** [OfficeDev/microsoft-teams-apps-champion-management#208]
Hello, 
I have a couple questions on implementing Microsoft Champions. Is there a way I can connect with the developers to ask questions or to set up a call.

Thank you!

**Comment by CyberRealm24** [comment]
Can this be used with external users? If so, would they have access to the organization's SharePoint sites?
Thank you!

**Comment by v-saikirang** [comment]
Hi @CyberRealm24,

Thanks for reaching out to us. Please post your questions here and we will be happy to assist you.
Currently this app cannot be used with external users due to some limitations.
Please let us know if you have additional questions.
Thanks.
