### ISSUE TITLE
Populate Event name and Member name in Event Track list

### ISSUE THREAD

**Issue by bhargavshukla** [OfficeDev/microsoft-teams-apps-champion-management#21]
Currently it is difficult to report on who delivered which event types. THe tabke in Event Track list includes reference to memberid and eventid. It is left to user to manually cross reference eventid to ID column in Event List and memberid to ID column in Member List.

Adding columns Member and Event Title/Type to Event Track Details and populating them when adding a row would make it better for tracking member activities better.

I recognize that the app shows activities when clicking on the person in leaderboard but it isn't sustainable in large orgs where sponsors might want to use PowerBI and other ways to report champion activities.

**Comment by JoshLeporati** [comment]
@bhargavshukla  -  we are now populating these items with version 1.2 on the Event Track List! When visiting that list now for recorded events the Member Name and Event title will show. Thanks for the feedback here.
