### ISSUE TITLE
Champion app permissions

### ISSUE THREAD

**Issue by MartinWhiteDAZN** [OfficeDev/microsoft-teams-apps-champion-management#22]
My company has reviewed this Champion app for teams and thinks it’s great. However, our security team are concerned about the level of permissions that it requires. 

The app requires access up to **managing all sites**. I know this is a delegated permission so it will only be able to manage the sites that the user can manage so the risk is less great than it may first appear. 
 
But the main concerns are:
1.	By granting this permission to the Champion app we are also granting it to all apps we deploy.
2.	Can we be sure that the code in _any_ app that is deployed won’t take advantage of the high level permission? We have some sensitive sites e.g. HR data. For example, code could be written to pull out sensitive data when an HR Admin uses an app.

What is the best wording to pass onto the security team?

**Comment by MartinWhiteDAZN** [comment]
Hi @karuanag 
Thanks for assigning my issue to yourself. Do you have any suggestions to help persuade our security team that the Champion app is safe to deploy?
Kind regards,
Martin

**Comment by v-saikirang** [comment]
Hi @MartinWhiteDAZN ,
Thanks for your patience!
With the current design there is no way to explicitly stop other applications from leveraging these API permissions in the tenant. 
If you strictly want to restrict these API permissions to the this app alone you can consider downloading the code and changing the authentication using MSAL and Azure App registration for graph API access. 
Please let me know if you need more information.
