### ISSUE TITLE
Error importing default cmp.sppkg

### ISSUE THREAD

**Issue by Hickey77** [OfficeDev/microsoft-teams-apps-champion-management#3]
Seeing this error trying to install the default SPO package.  Any ideas?

![image](https://user-images.githubusercontent.com/54556057/113875221-86531080-9784-11eb-920f-c6dd5a2f7b9c.png)

**Comment by VesaJuvonen** [comment]
Hi @Hickey77  - where did you see this exception and what were the actions performed for this. When you tried to upload it to the SharePoint app catalog or in some other step?

**Comment by VesaJuvonen** [comment]
Hi @Hickey77 - was able to repro the issue. Apparently we had a zip file containing the sppkg file in the solution folder and not the actual solution package. When this was then installed on the SharePoint tenant app catalog, you did indeed see the exception which you mentioned.

I changed the configuration a bit now and you can find the real sppkg file under SharePoint/Solution folder as defined in the documentation. This will then address the exception which you were seeing.

Thanks for reporting this and let us know if you ran into any other unexpected situations.
