### ISSUE TITLE
Use Site Collection App Catalog instead of Global App Catalog

### ISSUE THREAD

**Issue by bhargavshukla** [OfficeDev/microsoft-teams-apps-champion-management#30]
One of the concerns of most customers I work with is that the app template deploys in Global App Catalog, allowing the app to be available and deployed to any site in the SharePoint environment. Most customers want to control which sites the solution can be deployed to due to governance requirements. If the app deploys to Site Collection App Catalog instead of Global App catalog, it can be made available to desired SPO sites, meeting governance requirements.

This is a blocker for customers I have worked with and addressing it would enable broader usage of this app template.

**Comment by v-saikirang** [comment]
Hi @bhargavshukla , Thanks for your patience!

By design  this app needs to be deployed at the tenant level so it can be made available in the Teams. The App package cannot be deployed at the site collection level. Please let me know if you need more information.
