### ISSUE TITLE
Deploy Multiple Instances

### ISSUE THREAD

**Issue by Martin-Day** [OfficeDev/microsoft-teams-apps-champion-management#34]
Hello!
I was wondering if there was a way to deploy multiple instances of this app each with different member lists and config?
This would be useful as we have different champion networks for different transformation projects.
Thanks in advance
Martin

**Comment by JoshLeporati** [comment]
Hi @Martin-Day - some enhancements coming that you can leverage to enable that type of experience:

In an upcoming release we will be moving the member list to create under the champion site that gets created. That will keep all assets in one location.

Secondly, with that release you could then modify the package to deploy in different sites. So if you created alternate champion networks you would modify the source to install in that location. So each location you would modify the source to install there and load them each individually to support multiple programs.

The change in code to consolidate those assets is coming very soon and will enable you to support that scenario! Hope this helps! Keep on the lookout in this community for updates soon related to that package.
