### ISSUE TITLE
Continuous circle of waiting - 2

### ISSUE THREAD

**Issue by sarahcharlesRW** [OfficeDev/microsoft-teams-apps-champion-management#35]
I am receiving this problem and can see the last recorded report of this is marked as issue closed even though other people have added to the chat with the problem.

I have checked - the app permission requests have been approved..

![error](https://user-images.githubusercontent.com/49232225/122379734-094fce80-cf5f-11eb-8f3b-767c03119971.png)

**Comment by mgh1066** [comment]
I have exactly the same issue but on the web it builds the full dashboard but champions leader board returns 403 error
In desktop I get exactly the same as sarahcharlesRW.  For a 5 min deployment I seem to be spending alot of time trying to get it working :-) 

Is there a version 2.0.  It something related to permissions but I've got the SharePoint site shared correctly as per instructions

**Comment by JoshLeporati** [comment]
@sarahcharlesRW - generally this is shown when a user who didn't deploy the solution is accessing it for a first time and contribute permissions aren't applied to either all users or the specific ones. 

https://github.com/OfficeDev/microsoft-teams-apps-champion-management/#add-champion-management-platform-tab-in-teams

It would be step 4 here. Can you confirm that was done and if so, we can further troubleshoot. Thanks!

Also FYI @mgh1066

**Comment by mgh1066** [comment]
Thanks Josh, yes double checked the grant permissions still the same issue , is this a known issue  that v2 is looking to address?
thanks M

**Comment by sarahcharlesRW** [comment]
Hi there
I have allocated my admin account an Office License and even then I have the spinning circle issue in teams. I understand this looks like a permissions issue but I followed the instructions and it still does not work

**Comment by sarahcharlesRW** [comment]
Hi there
So to make sure i had not missed anything i completely deleted the Sharepoint (and from the recycle bin) and the application from teams and went through the instructions a second time.  What I now have is this, the spinning circle has gone but some of the elements dont appear t created like the member list 

![image](https://user-images.githubusercontent.com/49232225/123942415-05767000-d993-11eb-8aa5-781e3fb7df34.png)

**Comment by JoshLeporati** [comment]
Did the other lists create on the champion site @sarahcharlesRW ? The member list gets created on root SharePoint site. Navigating away from the platform app and back to it still just shows the same blank view?

**Comment by sarahcharlesRW** [comment]
Hi @JoshLeporati , Yes event track details and events list got created and the members list is on the root sharepoint site. Yes navigating away and back still show blank.  Can i move the members list to the champion site? or does it have to stay there?

**Comment by JoshLeporati** [comment]
Hi @sarahcharlesRW, for this version the list has to be on root. However in our next update coming out soon it will be moved to be contained in the same site as the other champion resources!

**Comment by sarahcharlesRW** [comment]
@JoshLeporati ok thanks.. so having read other comments on here .. i think to make this work i need to give everyone except external users edit permissions on the members list is that correct

**Comment by mgh1066** [comment]
I've deployed from scratch a couple of times now and every time I get the same as @sarahcharlesRW .... followed instructions.  Should I hold off investigating any further and wait for the next release @JoshLeporati 

especially 

 From <https://github.com/OfficeDev/microsoft-teams-apps-champion-management> ![image](https://user-images.githubusercontent.com/69787520/119333872-089d8280-bca8-11eb-8653-7ae7256dace8.png)

  . Select Share
  . Enter in 'Everyone except external users'
  . Change permissions to Edit
  . Unselect send email
  . Press share

**Comment by JoshLeporati** [comment]
Could you both let me know one more thing. If you click on the champion leader board - does it also take you to a blank screen or do you see an option to signup on left? 

Do you see an item populated in the member list on root site or is it blank? If blank - and the above let you request to become a champion does it populate? If it doesn’t populate can you add yourself (using default email address as title) to the member list - then does it display any results?

Thank you for the feedback and continued patience / information sharing!

**Comment by mgh1066** [comment]
Turner & Townsend Confidential


Could you both let me know one more thing. If you click on the champion leader board - does it also take you to a blank screen or do you see an option to signup on left?

Wants me to signup on left.




***@***.***D76F54.9353D600]

***@***.***D76F54.9353D600]

If I try and add entry I click submit

***@***.***D76F54.FA75D040]

**Comment by mgh1066** [comment]
It  asks me to signup as a champion but no records are found.  If I  try and add an entry I get response status 403. 

Interestingly enough did a bit of testing. I have 2 profiles
AdminProfile : admin privilege's allocation such as SharePoint admin
NormalUserProfile  : normal user to admin roles assigned

Adminprofile : install champion app follow instructions all works fine and app functions as expected in teams logged in as adminprofile
NormalUserProfile : when accessing champion app in teams the issue outlined above happens.  403

permission related with the 403,  but I have granted everyone access to the site collection as outline in the deployment instructions.

not sure if this helps

Thanks M

**Comment by JoshLeporati** [comment]
That’s very helpful! That points to that the solution installed correctly and we are indeed running into a permissions issue on the ChampionManagementPlatform page and potentially the member list. 

First - can you remove the permissions on the championmanagementplatform page and readd permissions. It should be for modify - you can also do this by configuring advanced permission on the page itself - for the three that will be listed (owner / member / visitor) grant rights to the member and add the everyone group (disable email send). 

Please try it granting permissions that way and let’s see if that makes a difference (versus the share route).

**Comment by sarahcharlesRW** [comment]
Sorry it took me a while to get back, but I confirm I have the same behaviour as @mgh1066

**Comment by sarahcharlesRW** [comment]
I removed the permissions and readded them.. the site permissions for members look like this.
![image](https://user-images.githubusercontent.com/49232225/124565682-3692ec80-de3a-11eb-882a-7b8b0e5ce06f.png)

I still have a 403 forbidden error when i try and become a champion.

**Comment by sarahcharlesRW** [comment]
OK.. so now i have give permissions to everyore except external to the members list on our default sharepoint site and i have sucessfully registered as a champion..

**Comment by mgh1066** [comment]
I've granted permission as @sarahcharlesRW  to the member list on default and I can add a user but i now get champions submission pending. no 403 error...if i remove access the 403 error returns

I still don't have the fully built menu I just see the champions leader board option.  Our security team are concerned about me changing the default sharepoint site to everyone has edit permissions.

Hope this helps

M

**Comment by sarahcharlesRW** [comment]
@JoshLeporati Do you have anything further to tell us? this is quite frustrating, I have the same issue as @mgh1066, the user i am trying to install this for is very frustrated as the promised functionality is not there... I might have to tell them this just does not work as promised, it is taking too much of my time.

**Comment by JoshLeporati** [comment]
Hi there, sorry for my delay. We are working to finalize an update this week, which should be released next week. With this it should address the primary security concern of modifying permissions in the root site, as well as hopefully clear up any other potential issue causing the main app from loading.

Once it’s posted next week I’ll ping you back in this thread to give the update a try and see that we can get it loaded from that update.

Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sarahcharlesRW** [comment]
@JoshLeporati .. ok thanks

**Comment by sarahcharlesRW** [comment]
@JoshLeporati .. Just wondered if there was an update?

**Comment by JoshLeporati** [comment]
@sarahcharlesRW + @mgh1066 - thanks for your patience! Yes, we did update yesterday and will be more broadly communicating today on v1.2 updates here in the repository. Please try v1.2 and see if these updates get you up and running and let us know here in the issue thread anything you run into! + @Porkai-Pandian

**Comment by v-saikirang** [comment]
Hi @sarahcharlesRW , @mgh1066 - 
Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by JoshLeporati** [comment]
@sarahcharlesRW / @mgh1066 - just wanted to check in to see if these changes in 1.2 have helped address these issues and if you’ve had a chance to test again?

**Comment by mgh1066** [comment]
> @sarahcharlesRW / @mgh1066 - just wanted to check in to see if these changes in 1.2 have helped address these issues and if you’ve had a chance to test again?

@JoshLeporati  trying to get it installed but unable to delete the current site due to an internal DLP issue which I'm waiting on our security team to resolve.  Update to follow soon as I can perform scratch install

**Comment by JoshLeporati** [comment]
Gotcha, thanks for the update!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JoshLeporati** [comment]
Hi @mgh1066 - just wanted to check back in to see if you've had any success getting the old site removed and 1.2 deployed to test?

**Comment by mgh1066** [comment]
Turner & Townsend Confidential


No I haven’t, frustrating isn’t the word.  Still waiting for security to address the DLP issue.  Escalated to Management 😊

**Comment by mgh1066** [comment]
Turner & Townsend Confidential

Deployed and looks to be working well.  Further update to follow.

Regards
Martyn Hewitt
M365 Technical Specialist
Turner & Townsend
Low Hall, Calverley Lane, Horsforth, Leeds, LS18 4GH
www.turnerandtownsend.com<http://www.turnerandtownsend.com/>

Turner & Townsend Limited
Registered office: Low Hall, Calverley Lane, Horsforth, Leeds LS18 4GH, United Kingdom | Registered in England and Wales | Registration No. 06468643

**Comment by JoshLeporati** [comment]
@mgh1066 that’s great to hear! Please let us know the further outcome and as you begin to use your feedback here! If no other issues after today I’ll close out this issue but do feel free to engage back with other questions or feedback, thanks for your patience and work with us on this!

#ChampionsRock!

**Comment by JoshLeporati** [comment]
@sarahcharlesRW - any chance you were able to try the new package and any update?

**Comment by sarahcharlesRW** [comment]
@JoshLeporati .. I have been on leave, I will have a look at this over the next couple of days

**Comment by mgh1066** [comment]
@JoshLeporati  have you had any reports of permission issue when trying to access the app

Its working for me but colleagues gets permnission denied when they click on the link  even though they have exactly the same app policy as me.  Also added them as admin to the SP site

![Capture](https://user-images.githubusercontent.com/85633776/130227095-67be44d8-9038-4267-91d2-fc7761091488.JPG)

thanks

**Comment by v-saikirang** [comment]
Hi @mgh1066 ,

Can you please confirm if you have teams app policies seperately set for these 2 users to override the global policy. 

Please change the policy to allow custom apps for these users. Once you change it may take some time to take effect. Log out and login back after some time and check. You may also consider switching their policy to global policy if not needed.

![image](https://user-images.githubusercontent.com/87538202/130229697-9b8fc6ca-8f20-451d-8a31-79f21207107b.png)


Let me know if you need more information.
Thanks.

**Comment by mgh1066** [comment]
thats exactly what I have for the specific policy and my test colleagues have applied.  Out global policy doesn't allow but prior to changing it for users I was testing with  a specific policy which allows all custom apps and overrides global.

I've had it applied to  pilot  colleagues for days, I'm on the right track just seems odd works for me and not them even though we have exactly same policy assigned....I'll continue testing thanks for getting back

**Comment by v-saikirang** [comment]
Hi @mgh1066,

Please let us know if you need additional help on this or if we can close this issue.

And please note that we have published a new version of the app that fixes few known issues and some improvements. You can check ReadMe for additional details on how to upgrade the package to the latest version(1.3.0.0).

Thanks.

**Comment by sarahcharlesRW** [comment]
Sorry I havent much time for this.. i tried it once but i could not compile the code in node.js i  got an error, and i havent had time to revisit it. its already taked too much of my time.

I have put some time in my calendar tomorrow to try one more time and then i will give up if it doesnt work, its just not worth this amount of effort

**Comment by v-saikirang** [comment]
Hi @sarahcharlesRW,

May i know if you are looking to customize the code. If not, you dont have to compile the code. You can directly deploy the package file. Please refer to the section "Standard Installation" in the ReadMe document - https://github.com/OfficeDev/microsoft-teams-apps-champion-management/blob/main/README.md.
If you need any help with this, please share your email and i will send out a meeting invite on Teams .
Thanks.

**Comment by sarahcharlesRW** [comment]
no i dont want to change anything..thanks for pointing that out.. i will give that a go

**Comment by v-saikirang** [comment]
Hi @sarahcharlesRW ,

May i know what version of the app you currently have installed so i can point you correctly.

Thanks.

**Comment by v-saikirang** [comment]
Hi @sarahcharlesRW,

May I know if you have any updates on this. Were you able to try installing this.
Thanks.

**Comment by sarahcharlesRW** [comment]
I managed to deploy this and have been waiting for confirmation from the person who runs our champions program. It is now looking good. Thanks, you can close this issue off.
