### ISSUE TITLE
‎Champion management platform‎

### ISSUE THREAD

**Issue by rajendrasn** [OfficeDev/microsoft-teams-apps-champion-management#36]
Hi,
I tried setting up this App in Syngenta tenant, but I was not able to proceed further step-10 from the steps provided in below link:
https://github.com/OfficeDev/microsoft-teams-apps-champion-management .

The API’s which needs to be approved from the Tenant are not visible.

**Comment by JoshLeporati** [comment]
Hi @rajendrasn - once you load the SharePoint package it should take a few minutes but then located the SharePoint admin center you will see a new advanced menu pop up with API approval steps there. You'll need to select each one and select approve. Please let us know if you are still not seeing it after initially loading and deploying the application to your Tenant.

**Comment by rajendrasn** [comment]
Hi Josh, I tried and after few minutes the API are still not available in Admin center for approval. Here by I'm attaching screenshot of the package deployed and API approval screen.
![ChampionManagement](https://user-images.githubusercontent.com/41720784/123035097-6092ea80-d408-11eb-88dc-9eced599098c.png)

Thanks
Rajendra

**Comment by JoshLeporati** [comment]
@rajendrasn thanks for the info! It looks like you've got some API access already approved from other items? These could be overlapping and that's why these wouldn't show. Can you check in your org wide for these three dependencies:
- User.ReadWrite
- Sites.ReadWriteAll
- Sites.ManageAll

If they are already out there then that's why they aren't showing for approval this go round and you should be good to proceed.

**Comment by rajendrasn** [comment]
Hi Josh,

Its still not working, i see the site is created but only 2 list are created in the site. 
![image](https://user-images.githubusercontent.com/41720784/123574449-7b40d700-d7ed-11eb-954b-48fdf226ac89.png),
Did we have to build the solution once?

Thanks
Rajendra

**Comment by JoshLeporati** [comment]
@rajendrasn this is expected. In this release those two assets are created under the champion site and the member list is created on a root site. With that event list being populated it shows the package deployed assets and created data there. If you check your root site do you see member list? If not it could be access to root site. 

In upcoming release all assets will be created under that champion site (member list)

**Comment by rajendrasn** [comment]
Hi Josh,
I cant see the members list at the root site. I'm having SharePoint tenant admin access.
Even if the list is created and I'm not able to see, if I'm go to next step(step 12) - to sync with teams, this step is also failing. 

Can we have a call via Teams or Zoom? 

![image](https://user-images.githubusercontent.com/41720784/123957598-9b2cf200-d9c9-11eb-98e9-066b7b79ad4b.png)

Thanks
Rajendra

**Comment by v-saikirang** [comment]
Hi @rajendrasn ,  Thanks for your patience! We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by JoshLeporati** [comment]
@rajendrasn - per Sai comment above were you able to try this with 1.2?

**Comment by rajendrasn** [comment]
Hi Josh,

I tried with the latest version bit still the issue is same, can we have a quick call via Teams to have a look into this.

Thanks
Rajendra

**Comment by JoshLeporati** [comment]
sure thing Rajendra, what's a good contact email for you?
________________________________

**Comment by rajendrasn** [comment]
Hi Josh, 
I took the latest code and deployed it in our tenant and it got successfully deployed and synched with Teams. But when I add the app in Teams it is just spinning. Attached screenshot.

Thanks
Rajendra
![CMP_Screenshot](https://user-images.githubusercontent.com/41720784/132159055-ddcc0970-4f6a-4ee9-a2a3-cba79a7b05b5.png)

**Comment by v-saikirang** [comment]
Hi @rajendrasn ,

Can you please share your email so we go over this on a teams call.
Thanks.

**Comment by rajendrasn** [comment]
HI,

My email id is rajendra_negi01@infosys.com.

Thanks
Rajendra
