### ISSUE TITLE
Unable to redeploy Championship Management Platform

### ISSUE THREAD

**Issue by say-brad** [OfficeDev/microsoft-teams-apps-champion-management#37]
I followed the steps and deployed the Championship management platform, but then I had the circling error of not all the groups formed on the Champions Page, so I deleted the site, and then followed by application.

I am then trying to recreate the solution, importing the solution shows success but API access page no permission requests are made, assuming its already there I tried but with no success, after going through the issues here, I deleted the site permanently and now the site also not  getting created and am stuck , any inputs are appreciated to get this going. 

Application is listed on the SharePoint Apps Page
![image](https://user-images.githubusercontent.com/87368524/125501647-4371b541-63be-483b-8ca0-a0a13d921879.png)

API Access I don't see it. 
![image](https://user-images.githubusercontent.com/87368524/125501786-9c42fd57-2d86-4902-8a82-201b20e3d941.png)

When I sync, I get "sync failed to Teams"
![image](https://user-images.githubusercontent.com/87368524/125502165-90421359-c548-48af-b304-1b9510ee1b0a.png)

also I dont see the SharePoint site created. 
![image](https://user-images.githubusercontent.com/87368524/125502320-105598de-d1f1-4bf1-805e-fce0deff4557.png)

**Comment by v-saikirang** [comment]
Hi @say-brad ,  Thanks for trying this app. We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

You don't have to approve the graph permissions again if you have already done once. In your screenshot you can see the permissions are under "Approved" section.

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by JoshLeporati** [comment]
@say-brad just wanted to check in to see if you were successful in getting 1.2 / updated package deployed?

**Comment by say-brad** [comment]
Hello Josh, haven't got into installing it, will be doing this week and keep you updated.

Regards,
Sayee

**Comment by JoshLeporati** [comment]
Sounds good, thanks @say-brad !

**Comment by JoshLeporati** [comment]
@say-brad just wanted to check in to see if you were able to re-deploy? thanks!

**Comment by JoshLeporati** [comment]
@say-brad please feel free to open a new issue if you are still having any issues with the installation. Also please note we have [version 1.3](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/blob/main/README.md) out as of this post and that should be the latest for you to run the install against or upgrade to, thanks!
