### ISSUE TITLE
Assistance with deployment

### ISSUE THREAD

**Issue by carlosrsolis** [OfficeDev/microsoft-teams-apps-champion-management#38]
We have been unsuccessful in deploying this.  At the last MS Higher Ed Advisory Committee Board meeting it was suggested that I reach out to this group to ask someone for assistance with this matter.  

Is this something someone here would be able to help with?
Best regards

**Comment by v-saikirang** [comment]
Hi @carlosrsolis,  Thanks for trying this app. We have updated the package to a new version V1.2 yesterday with few fixes and improvements. Can you please uninstall the existing package and try installing the new package from the same location - [link](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution). 

You can see the updated ReadMe [here](https://github.com/OfficeDev/microsoft-teams-apps-champion-management) for the 1.2 changelog and upgrading instructions as well under the section "**Upgrade to version 1.2.0.0**".

**IMPORTANT NOTE**: Please wait for 15 minutes after you have completed first 4 steps under the section **"Upgrade to version 1.2.0.0"** in ReadMe and then continue with step 5. This is to avoid cache related issues for the deleted assets.

**Comment by JoshLeporati** [comment]
@carlosrsolis - were you able to get 1.2 loaded or do you still require any assistance?

**Comment by JoshLeporati** [comment]
@carlosrsolis - please let us know if you still require assistance here. Happy to assist if help is still needed, i'm going to close this out for now but just respond back and we can troubleshoot any further issues with 1.2 install
