### ISSUE TITLE
Wont update the members list attributes v1.2

### ISSUE THREAD

**Issue by l2marsha** [OfficeDev/microsoft-teams-apps-champion-management#50]
Hi,
after installing v1.2 i am trying to change the attributes required to be filled out on the Become a Champion page. i have added 2 new columns in the SharePoint list but they do not show on the Become a Champion signup. i have hidden the focus area and group columns and added Area and Branch. focus area and group still show on the sign up page but the new columns do not.

originally i edited the name and input of Focus area and group columns. this caused the entire app to white screen when become a champion was clicked or the leader board if you were already a champion. i had to delete the site and re create it.

i am running v1.2 the guide is limited on how exactly you do this but i have followed what is there under additional customisation options:
**This action is done from selecting the list you would like to edit (champion list for this example), selecting the drop down on the column, then navigating to Column settings -> Edit.**

Can you please advise
**columns on site list**
![image](https://user-images.githubusercontent.com/88155490/127974422-838943ff-79f9-4ff6-930b-38c6030076a3.png)

**displayed attributes on sign up**
![image](https://user-images.githubusercontent.com/88155490/127974491-2d1e659a-b4e9-498d-b556-ee62ea05da3b.png)

**Comment by v-saikirang** [comment]
Hi @l2marsha,

The current package cannot pick up the changes you do on your site/list/columns. If you want to do such customization you will need to download the source code, make required changes in the code, generate new package and then deploy. This will require some development effort from your end. The current package will work if you don't make any changes to the site/lists/fields.

Thanks.

**Comment by JoshLeporati** [comment]
@l2marsha - if you add new values for focus area / group / region - those would pickup and show from the dropdowns above. Like @v-saikirang mentioned though, any further customization (to the UI to show other elements) would need to be done within the code for that to show.

Another common area to add new values is to the event list. Adding new events would populate under the record event in the leaderboard.

You can always add additional fields to capture information about the champions on the member list (or any other list for that matter), but that data would not be displayed anywhere except the list. This could be used for tracking other elements if needed.
