### ISSUE TITLE
Where to find CMP File Download

### ISSUE THREAD

**Issue by kdebrino** [OfficeDev/microsoft-teams-apps-champion-management#53]
Hello, 

I am hoping you can point me in the right direction as to how to find the CMP download folder as referenced in step 4. Trying to get this kicked off. 
![image](https://user-images.githubusercontent.com/88908838/129418733-0706df18-0ba4-4e12-b032-f116fdd52370.png)
Thanks in advance!

**Comment by v-saikirang** [comment]
Hi @kdebrino,
Please check the Standard Installation section of the ReadMe document if you want to use the package file as is without any further  customization. Let me know if you need more information. If you want to customize the code then you have to follow the Custom Installation section. In this case you will have to download the entire folder using download option in GitHub. The downloaded folder is the CMP folder that is being referenced in step 4. Thanks.

**Comment by JoshLeporati** [comment]
@kdebrino as Sai mentioned the above NodeJs instructions are for customized deployments where you need to modify the code. If you are looking for the preconfigured / standard package file to load into SharePoint/Teams - that package can be found here in our code source:

https://github.com/OfficeDev/microsoft-teams-apps-champion-management/tree/main/sharepoint/solution 

download that file you would then upload and follow the steps in the ReadMe starting here:
https://github.com/OfficeDev/microsoft-teams-apps-champion-management#deploy-your-package-to-sharepoint
