### ISSUE TITLE
Icon keeps spinning with v1.2

### ISSUE THREAD

**Issue by mgmjtech** [OfficeDev/microsoft-teams-apps-champion-management#55]
These are the deployment steps that I took. However, after adding the Champion Management app, the icon beside champion leader board keeps spinning.
Account using has global and SharePoint roles
1. downloaded the cmp.sppkg  v1.2
2. added to the SharePoint admin app catalog
3. approved api access
4. sync to teams
5. open teams and add app "champion management platform"
6. Icon spinning
other issues - can't find a site called "ChampionManagementPlatform" https://<yourtenant>.sharepoint.com/sites/ChampionManagementPlatform/

Please let me know if I am missing something here.

**Comment by mgmjtech** [comment]
Hello,
Any updates on the next release?

**Comment by v-saikirang** [comment]
Hi @mgmjtech ,

We will let you know shortly. 
Thanks.

**Comment by JtcainTX** [comment]
I am also seeing this same issue, and I would be interested in the timeline for a fix.

**Comment by v-saikirang** [comment]
Hi @mgmjtech and @JtcainTX ,

We have published the new package file in the same location. Assuming  that you already have deployed the old package but never got it working you can refer to the section "Upgrade to version 1.3.0.0 from 1.1.0.0" in ReadMe file - https://github.com/OfficeDev/microsoft-teams-apps-champion-management/blob/main/README.md

Let me know if you need more information or if you are facing any issues.
 Thanks.

**Comment by JtcainTX** [comment]
I have published the version, and the App does load. However, I only see a single option on the home screen (see attached)
![2021-09-06 06_16_18-Window](https://user-images.githubusercontent.com/53141377/132209355-72c89e61-a071-4b7a-b01e-5fee72f53282.png)
I have waited about 2 hours and cleared the cache in Team. I can confirm that the SharePoint site does exist, but it has almost no content.

**Comment by v-saikirang** [comment]
Hi @JtcainTX,

Can you please confirm the package version that you see in Appcatalog is 1.3.0.0?
Have you used the same account to install the App for the first time. 
Can you please share a screenshot of the "Members List" from the "ChampionManagementPlatform" site collection.
Thanks.

**Comment by JtcainTX** [comment]
Yes, the package is version 1.3.0.0
![2021-09-06 07_05_55-Apps for SharePoint - All Apps and 5 more pages - JC Org - Microsoft​ Edge](https://user-images.githubusercontent.com/53141377/132215043-539c880d-a8b4-491a-b211-48aca9c0258b.png)
Yes, the API permissions are approved:
![2021-09-06 07_07_45-SharePoint admin center and 6 more pages - JC Org - Microsoft​ Edge](https://user-images.githubusercontent.com/53141377/132215206-1bc098cb-1a65-44f5-8f5c-9873f7ee36b1.png)

**Comment by JtcainTX** [comment]
I was able to refresh once more, and I now have all the options:
![2021-09-06 07_13_47-Greenshot](https://user-images.githubusercontent.com/53141377/132215939-16e4d435-2459-4496-8de0-4a4b0c0ce69b.png)

**Comment by JoshLeporati** [comment]
@JtcainTX that's great to hear, thanks for the update!

@mgmjtech - were you able to get deployed with version 1.3?

**Comment by Korn1699** [comment]
I had the same issue with 1.3.  Clearing my cache on the desktop app didn't fix it.  I just tried to add it in the browser version.  There was a notification that popped up saying that I was added as a manager for the app.  After clicking that, it came up fine.  I'm guessing that the desktop app was having some issue dealing with that notification.  Hopefully, that helps someone.

**Comment by v-saikirang** [comment]
Thanks for your feedback @Korn1699.

Hi @mgmjtech Can you please confirm if you were able to deploy 1.3. Please let us know if you need any support from us.
Thanks.

**Comment by mgmjtech** [comment]
> Thanks for your feedback @Korn1699.
> 
> Hi @mgmjtech Can you please confirm if you were able to deploy 1.3. Please let us know if you need any support from us.
> Thanks.

Sorry for the delay in my response.  Yes, I was successfully deployed with v1.3. Thank you!

**Comment by JoshLeporati** [comment]
That's great to hear, thanks for the confirmation and patience @mgmjtech!

/Josh
