### ISSUE TITLE
Bundle error

### ISSUE THREAD

**Issue by SPHLu** [OfficeDev/microsoft-teams-apps-champion-management#56]
Hello,

I tried building the solution via AzureDevops YAML pipeline, but encountered this error
![grafik](https://user-images.githubusercontent.com/89574590/130926661-708dfa9f-1f4f-489e-b31c-a794d96f78b5.png)

**Comment by v-saikirang** [comment]
Hi @SPHLu,

Can you please confirm if we can close this issue or if you need additional help.
Thanks.

**Comment by SPHLu** [comment]
yes, this workaround will suffice. Thanks
