### ISSUE TITLE
Bundle error

### ISSUE THREAD

**Issue by joelfmrodrigues** [OfficeDev/microsoft-teams-apps-champion-management#6]
Hello,

I am getting the following error when trying to bundle the solution

![image](https://user-images.githubusercontent.com/19577724/114185383-95c98980-993d-11eb-9fad-ad5658204512.png)

**Comment by yhabersaat** [comment]
Hi @joelfmrodrigues, made a PR #8 for this issue.

**Comment by VesaJuvonen** [comment]
Issue has been merged and solved. Thanks for taking care of this @yhabersaat. Closing this one.
