### ISSUE TITLE
Unable to successfully upload app package to App Catalog

### ISSUE THREAD

**Issue by mindfield-ca** [OfficeDev/microsoft-teams-apps-champion-management#60]
I am unable to successfully upload the app (version **1.3**) to the tenant App Catalog as I receive the errors:

Valid App Package: No
App Package Error Message: Invalid SharePoint App package. Error: File contains corrupted data.

![Package_error](https://user-images.githubusercontent.com/51539748/133435398-255f8bfa-9bc0-4570-bce0-b72cc833a24f.png)

Note that I did not have this issue with version **1.2**, however I was experiencing another issue where the SharePoint site was not being created as expected after deploying the Teams app. This is apparently corrected with version 1.3.

**Comment by JoshLeporati** [comment]
Hi @mindfield-ca, the app version showed is 1.0, with a file name of cmp (1), which looks like it could be a duplicate of a download. 

Could you try clearing your local download file location - remove that package from your app catalog - and attempt to download the latest 1.3 version from [this location](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/blob/main/sharepoint/solution/cmp.sppkg), hit download on right side of page to get just the SP package file I directly linked you to in the overall code repository.

Please let us know results of this

**Comment by mindfield-ca** [comment]
Looks like there was no issue after all; I renamed the cmp package to something else, re-uploaded, and now deployed and installed successfully! Thanks!

**Comment by JoshLeporati** [comment]
glad to hear @mindfield-ca , does it show version 1.3 over 1.0 in screenshot?
