### ISSUE TITLE
Failed to sync solution to Teams

### ISSUE THREAD

**Issue by Gitgeek195** [OfficeDev/microsoft-teams-apps-champion-management#61]
Unable to sync customized solution to Teams. Its failing with error "Failed to sync solution to Teams".

Already tried below two options:
1) Deleting old App from MS Teams.
2) Allowing permissions to External App.

Please suggest what could be wrong here and solution for it.

**Comment by v-saikirang** [comment]
Hi @Gitgeek195,

Can you please provide more context. Do you already have old version. If yes, which version are you having already. And have you already started using the App and do you have data in the "ChampionManagementPlatform" site collection. Please share screenshots as needed.
Thanks.

**Comment by Gitgeek195** [comment]
Hi @v-saikirang,

Yes, I had the old version. Now trying to upload and deploy my own customized App. The customized package has been created successfully as per the process mentioned in the blog. As next step, I deployed the SharePoint App package on Sharepoint environment. It is also successful without errors. But, when I try to Sync the Solution to Teams via SharePoint it throws error "Failed to sync Solution to Teams".

We tried this in fresh environment as well where the Old App was not present already. But still we are getting same error.

**Comment by v-saikirang** [comment]
Hi @Gitgeek195,

So i understand that you have downloaded the code and generated a new package? Can you please confirm. If yes, may i know what changes you have done in the solution on a high level. 

And can you also confirm if you have provided the API permissions in Sharepoint Tenant Admin. Can you please share a screenshot.

Thanks.

**Comment by Gitgeek195** [comment]
Hi @v-saikirang,

Yes, correct. Downloaded the code and generated new package with our changes.
Changes are minor like replacing images & editing texts. We have kept the variable names and other naming conventions same for that matter. Idea was to check if we are able to deploy our changes successfully.

Yes, the 3 API permission which it asks for has been provided.

Screenshot of API attached for reference.

![image](https://user-images.githubusercontent.com/91057936/134125193-a145b8dc-a7a4-4c6a-9c20-40f1c2f321cc.png)

**Comment by v-saikirang** [comment]
Hi @Gitgeek195,

Can you please make sure you have deleted the App from "Apps" section as shown below.

![image](https://user-images.githubusercontent.com/87538202/134125688-829fd2c8-98ec-47e6-bbc0-98d5769b31a4.png)

And do you have the same issue with the package from Github as well or it happens only with the package you generated?
Thanks.

**Comment by Gitgeek195** [comment]
Hi @v-saikirang,

Yes, the App has been deleted already but still same issue comes up.

No, I don't face any issues with package from Github. It happens only for customized package created.

**Comment by v-saikirang** [comment]
Hi @Gitgeek195,

Can you please share your email so we can get more information on this.

Thanks.

**Comment by v-saikirang** [comment]
Hi @Gitgeek195, 
Just checking if you have any updates on this and if you need any help. Please let me know.
Thanks.

**Comment by v-saikirang** [comment]
Hi @Gitgeek195,

Can you please share if you have any updates on this. Thanks.

**Comment by v-saikirang** [comment]
Hi @Gitgeek195,

I am closing this issue for now. Please open a new issue if you are still having issues or need assistance.
Thanks.
