### ISSUE TITLE
Administrative options are not shown to users who are configured as managers

### ISSUE THREAD

**Issue by jwilcot** [OfficeDev/microsoft-teams-apps-champion-management#63]
Fresh deployment of v1.3.  API permissions granted and the /sites/ChampionManagementPlatform SharePoint site was successfully provisioned. 

All employees were granted edit access to the site collection.  Users who have been added to the Member List as managers do not see any administrative options in the Teams app, only the "Leaderboard" icon, receiving the following error in Teams for web:

"An embedded page at (tenant sp root collection) says / an unexpected error occurred while retrieving user role.  Below are the details: TypeError: Cannot read property 'toLowerCase' of undefined"

Tried deleting app and site and re-deployed, to no avail.

![image](https://user-images.githubusercontent.com/40610847/137939365-f06a7865-ba88-4d01-9a53-e7a52157e420.png)

**Comment by v-saikirang** [comment]
Hi @jwilcot,

Thanks for your feedback. Closing this issue.
