### ISSUE TITLE
Unable to update app layout in Microsoft Teams

### ISSUE THREAD

**Issue by bchamnarnkit** [OfficeDev/microsoft-teams-apps-champion-management#65]
Hi Team, Is there a way to customize the app layout of the Champions Management app? Specifically I want to customize the registration layouts. I find that when I update these in the SharePoint lists (The headers), it does not update the header in the actual app despite the choices being updated. Thanks!
<img width="1180" alt="Screenshot 2021-11-15 174655" src="https://user-images.githubusercontent.com/84174370/141768591-5fb271ab-84c1-40b1-9ca7-fb2158552192.png">

**Comment by v-saikirang** [comment]
Hi @bchamnarnkit,

Updating the share point lists will not update the layout of the forms. If you want to change the layout you will have to download the code and make changes in the React components, generate the new package and deploy it. Please check the ReadMe section in the github for more details.
Thanks.
