### ISSUE TITLE
After deleting champions user list, app content disappear

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-champion-management#66]
Hi,
yesterday we have replaced users used to test with official users champion list but immediately app look like corrupted and show a white page instead of content.

Data are all present on SharePoint, list populated with data, but app on Teams doesn't work. 

Considering that are simple row and that has not changed structure of SharePoint site, probably there's something that is correlated with deletion but we don't know where.

We have tried also to deploy again app but result is always the same

**Comment by v-saikirang** [comment]
Hi @faalive,
Ideally the champions should be added using "Add Members" screen in the app.
We would need more information here to know more about the issue. 

1) What is the difference between the test and official accounts.
2) What do you mean replacing users. Can you please elaborate the steps.
3) Can you please share screenshots of the "Members List" and the App home page
4) Did you try logging in with the Tenant admin account that you used to install the app for the first time. Can you please share the screenshot of the view.
5) If the app works fine for the Tenant Admin try adding a new user through "Add Member" and see if it works for that users.
6) Can you login with the account which is having issues in a browser and share a screenshot of the browser console logs.
Thanks.

**Comment by faalive** [comment]
> Hi @faalive, Thanks for trying out the App. Ideally the champions should be added using "Add Members" screen in the app. We would need more information here to know more about the issue.
> 
> 1. What is the difference between the test and official accounts.
> 2. What do you mean replacing users. Can you please elaborate the steps.
> 3. Can you please share screenshots of the "Members List" and the App home page
> 4. Did you try logging in with the Tenant admin account that you used to install the app for the first time. Can you please share the screenshot of the view.
> 5. If the app works fine for the Tenant Admin try adding a new user through "Add Member" and see if it works for that users.
> 6. Can you login with the account which is having issues in a browser and share a screenshot of the browser console logs.
>    Thanks.

Hi @v-saikirang answer below:

1. there's no difference: to test app cx has inserted a couple of users that has been deleted to have a clean list of Champions
2. cx has replaced name of column in italian language so _Name_ has been changed with _Nome_  and so on
3. Problem is that I cannot see data anymore because look likes that SP site cannot be created and app status is stuck "waiting" also if package has been uploaded, deployed and syncronized on Teams 

<img width="1112" alt="CM_1" src="https://user-images.githubusercontent.com/72658126/142047982-b88cb746-4a15-4aa4-924a-5502bc825bb8.png">

<img width="1263" alt="CM_2" src="https://user-images.githubusercontent.com/72658126/142047894-ef0555ec-bc1e-4ead-b926-7a89a8f404d2.png">

**Comment by v-saikirang** [comment]
Hi,
Please do not change the list/column names. 
Can you try refreshing the APP first. If it doesn't work please follow the below steps to re install the app.

1) Delete the App in Teams
2) Delete the share point site in both "Active sites" and "Deleted Sites" section from the sharepoint admin center.
3) Delete the WSP from the App catalog
3) Wait for 15- 20 minutes
4) Perform fresh install as per Read Me instructions
5) If you see an error message "Try again after some time", please refresh the app after 15 minutes.

Please let me know if you need more information/help.
Thanks.

**Comment by faalive** [comment]
It's worked :) Great!!!

**Comment by v-saikirang** [comment]
Hi @faalive,
Thanks for confirming. I am closing this issue.
Thanks.
