### ISSUE TITLE
Fail to sync to Teams

### ISSUE THREAD

**Issue by raiceam** [OfficeDev/microsoft-teams-apps-champion-management#67]
I followed this doc to create a Standard deployment, I am Sharepoint admin and Teams admin, I also tried with a global admin in the Enterprise and I still cannot make it Sync to Teams. 

![image](https://user-images.githubusercontent.com/94491423/142072929-004bf092-6e7e-4da0-a245-4764c04688f2.png)

![image](https://user-images.githubusercontent.com/94491423/142073114-3d89e2d0-5b46-4a65-822f-9f8fab946fb0.png)

This is the error we get when we Sync to Teams. I tried to open a case with MS Support, but they sent us to developers.
![image](https://user-images.githubusercontent.com/94491423/142073508-5b89c399-7587-4851-aa5f-2dce6d63b66b.png)

Please advise what to do after this.

**Comment by v-saikirang** [comment]
Hi @raiceam,

Thanks for trying out this app.
Can you please go to the "Apps" section in your Teams and search for "Champion" and check if you already see the "Champion Management Platform" app there. If yes, please delete and try syncing again.

Thanks.

**Comment by raiceam** [comment]
it showed up after few days. Thank you.

**Comment by v-saikirang** [comment]
Hi @raiceam ,
 Thanks for confirming. I am closing this issue.
Thanks.
