### ISSUE TITLE
Global Rank is not showing data

### ISSUE THREAD

**Issue by faalive** [OfficeDev/microsoft-teams-apps-champion-management#68]
Hi,
yesterday, after app deployment, we noticed that Global Rank part is not showing any data (point and ranking) as below

![image](https://user-images.githubusercontent.com/72658126/142417043-abeaebf9-0bc1-4161-bc3e-05e626a51b34.png)

Any idea

Regards

**Comment by v-saikirang** [comment]
Hi @faalive,

1) Was this working correct earlier.
2) Can you open this in browser and share the console logs screenshot.
3) Can you also try with the admin account
Thanks.

**Comment by faalive** [comment]
yes, it's worked during all test phase. When we have installed app again a customized column name (in italian language) all works except final rank. We are using at moment only admin account

![image008 (002)](https://user-images.githubusercontent.com/72658126/142879262-3a816062-a84f-4210-8597-6e7ad1ceab3d.jpg)

**Comment by v-saikirang** [comment]
Hi @faalive,

Can you please try the app without any customizations and confirm it works.
 If you want to customize the app you cannot directly use the package. You will have to download the code, make changes to the code as per your customizations and redeploy the newly generated package. Please let me know if you need more information.
Thanks.

**Comment by v-saikirang** [comment]
Hi @faalive,  Can you please confirm if you still see any issues.

Thanks.
