### ISSUE TITLE
First name & Last Name populated incorrectly 

### ISSUE THREAD

**Issue by wsho71** [OfficeDev/microsoft-teams-apps-champion-management#70]
Hi,

We are using champion management platform. When we add a new member, the first name and last name populated incorrectly.
For example: 
- Member name: Yeoh Mei Kuan
- In sharepoint list, First Name = Yeoh, Last Name = Mei.

**Comment by v-saikirang** [comment]
Hi @wsho71, 
Thanks for trying this app. 
May I know what is the actual First name and Last Name of the user as per AD.
Thanks,
Sai.

**Comment by wsho71** [comment]
Hi Saikirang,

First Name: Yeoh
Last Name: Mei Kuan
Display Name: Yeoh Mei Kuan

**Comment by v-saikirang** [comment]
Hi @wsho71,
Thanks for sharing the details. We will look in to this get back to you at the earliest.
Thanks.

**Comment by v-saikirang** [comment]
Hi @wsho71,

We have noted down the issue and will correct in our future releases. Thanks for bringing this up.

And please note that this will not have any functional issues with the App. The only place that gets affected is the Display Name on the Side bar on Leader Board. It will show the truncated name here. Rest of the functionalities should work with out any issues. I am closing this issue for now but please let us know if you need more information or assistance.
Thanks.
