### ISSUE TITLE
CMP first load failing with no error

### ISSUE THREAD

**Issue by olivjat** [OfficeDev/microsoft-teams-apps-champion-management#74]
On first load of the Teams app, Champion Leader board tile shows up and a spinning circle.
It spins for ever and stays stuck.
App is loaded in Teams Windows client.
Tried removing all components and reloading the cmp package several times. Did not make a difference.
Tried loading the app in Teams Web client after removing the following assets from the SharePoint site:
- Digital Badge Assets
- Event Track Details list
- Events List
- Member List
It now prompt with a message saying "Admin permission have been granted to user X. Please refresh the app"
All is now functional.

**Comment by v-saikirang** [comment]
Hi @olivjat,
Thanks for trying this app.
I understand that you are now able to load the app successfully. Is there anything that i can help you with. Please let me know.
Thanks.
