### ISSUE TITLE
Digital badge can not be retrieved nor applied

### ISSUE THREAD

**Issue by RobertHoegner** [OfficeDev/microsoft-teams-apps-champion-management#75]
Digital badges are not shown, even tho i just deployed the solution and the library has default images without having them tagged to tournaments. When trying to apply badge this error is shown:

![image](https://user-images.githubusercontent.com/49672998/150087466-227faf42-2b7f-499f-95f3-8f3f516ad63e.png)

Any ideas?

here the list of bades for reference:
![image](https://user-images.githubusercontent.com/49672998/150087631-6fe04828-fc57-4d2e-855e-596ea3500a16.png)

**Comment by v-saikirang** [comment]
Hi @RobertHoegner,

Thanks for your feed back.

May i know if you have changed the column names in the Digital Badge library. I see different column names in your screenshot.
And can you please open Teams in browser and share a screenshot of the console errors.

Thanks.

**Comment by RobertHoegner** [comment]
i did not change the column names, it is just german UI - sorry for that.

there you go with the screenshot:
![image](https://user-images.githubusercontent.com/49672998/150094527-27027edd-62a8-4da6-9399-e7fcb107c41b.png)

**Comment by v-saikirang** [comment]
Hi @RobertHoegner, Can you please expand the last error in the console logs and share a screenshot.

**Comment by RobertHoegner** [comment]
sorry, we can also have a short teams session if that helps
![image](https://user-images.githubusercontent.com/49672998/150096812-a9362fe6-e5cf-4f71-8317-3dafc9b2200c.png)

**Comment by v-saikirang** [comment]
Sure. Please share your email and we can set up the call. Thanks.

**Comment by RobertHoegner** [comment]
robert.hoegner@faber-castell.com - won't be available today anymore sadly but feel free to invite for tomorrow between 11-15 CET or after 16:30 CET

**Comment by v-saikirang** [comment]
@RobertHoegner Thanks for the details. I have sent you the invite for tomorrow.
Thanks.
