### ISSUE TITLE
Error running npm install

### ISSUE THREAD

**Issue by timoleo23** [OfficeDev/microsoft-teams-apps-champion-management#77]
Hi, I cloned the repo locally then executed the npm start command from VS Code (using admin mode) and I get the following errors.

![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/17161633/151031781-57ab81d7-d4a1-4a30-9e53-cbaa014fed28.png)

I'm running npm v7.19.1 and node v14.18.1

**Comment by v-saikirang** [comment]
Hi @timoleo23,

Thanks for your feedback.

May i know what customization are you trying to implement. Have you tried installed the package directly without cloning the code. Please let me know.
Thanks.

**Comment by timoleo23** [comment]
Hi @v-saikirang, thank you for your support and guidelines - This issue is now resolved - Here are the 2 steps I had to do:
1. Move my project forlder to a location where the file path was shorter
   I changed it from
   C:\GitHub-local\Teams-Apps-demos\microsoft-teams-apps-champion-management
   to
   C:\GitHub-local\Teams-Apps-demos\apps-champion-mngt

2. Use the following command to install the solution
   ```bash
   npm install --save node-releases 
   ```
