### ISSUE TITLE
Champions (Employees) cannot see all options in CMP - SharePoint Member List

### ISSUE THREAD

**Issue by Pa623** [OfficeDev/microsoft-teams-apps-champion-management#82]
We rolled out CMP, but the internal employees that are added as members in the CMP cannot see all options, but only a moving circle. We tried to edit the email addresses of the invited champions in the SharePoint member list, but they don't have access to the platform, regardless of the E-mail addresses we use in SharePoint. 

Last time, we investigated the following solution, but unfortunately it is not working as follows:
1)	The issue is due to the difference in UPN and Email. Below is the snapshot of the results when we searched for Anna in share point. The CMP App assumes both UPN and Email are same.

2)	When adding a user through “Add Member” screen it’s adding the ids with “x-x.com” and the user is not able to see the options. But when we changed it to “xx.com” it started working.

As I have demonstrated we have 2 options in this use case where the UPNs and Emails are not matching.

1)	Add people to through ”Add Members” and modify the emails in the “Members List” in SharePoint.
2)	By default the employees will only see LeaderBoard option and they can request to become a champion. Once they submit the request the Admin has to approve the access using “Manage Approvals” option in the App. After Approval the champion can access other options.
In this case it works as expected and no manual fix is required.

Any ideas what the issue can be?

**Comment by v-saikirang** [comment]
Summary of our discussions:
1)	Every user who need to access the app should be added to “Members” group in the Share point Site. Once we have given access to the users who earlier had issue is now able to access the app.
2)	You could also consider adding AD security groups to the Share point if you already have any.
3)	If the members themselves request access from the App’s Leaderboard as an admin you can approve the request from “Manage Approvals” option on Dashboard. This way you don’t have to fix the emails in the “members” list in share point manually.
Thanks.
