### ISSUE TITLE
Tournament Ranking not working

### ISSUE THREAD

**Issue by plakerl** [OfficeDev/microsoft-teams-apps-champion-management#83]
Experiencing am issue with the latest release of the platform.  The tournament rank doesn't appear to be working and not keeping track of who has completed actions.  Despite completing actions I see the rank not increasing.  
![image](https://user-images.githubusercontent.com/27173205/155347273-183f17b5-a281-4f5b-908a-f47d7dc386b1.png)

Almost feels like I am missing a step to start the tournament but confirmed that is not the case and the tournament is indeed started.

**Comment by plakerl** [comment]
Also note that the global rank for Champions is working fine.

**Comment by v-saikirang** [comment]
Hi @plakerl ,
Thanks for your feedback on the app.
Can you please share a screenshot of TOT leader board page as well. 
Thanks.

**Comment by plakerl** [comment]
Here you go 
![image](https://user-images.githubusercontent.com/27173205/155535117-90039a46-3866-4de5-9a70-2967a779a2d0.png)

**Comment by v-saikirang** [comment]
Hi @plakerl,

1) Can you please confirm if these API permissions are approved in Sharepoint admin portal:
![image](https://user-images.githubusercontent.com/87538202/155539275-38670727-3323-4cdb-96bd-fb7d2a0ca33a.png)

2) May i know if you have changed any columns in any of the SP lists created by default.
3) Can you share a screenshot of "User Actions" List settings page where it shows the list of columns and also a screenshot of the list data.

**Comment by plakerl** [comment]
Here is what I see for API access which could be the issue.  Working with Global Admin on that.  I have not modified any List and the User actions settings screen also attached.
![image](https://user-images.githubusercontent.com/27173205/155572068-9c6470a4-2342-44e7-b36b-d9bb05d438de.png)
![image](https://user-images.githubusercontent.com/27173205/155572130-84273741-8538-4577-b7e4-00e8ed1b14c4.png)

**Comment by v-saikirang** [comment]
Hi @plakerl ,

I see that you already have the Api permissions approved. So i dont see an issue with that.

Can you share the screenshot of the contents inside the User Actions list.

**Comment by plakerl** [comment]
Here are some of the user actions that are for a current touranment. 
![image](https://user-images.githubusercontent.com/27173205/155578648-d8d89405-7868-4386-9da0-c3a1af27bc64.png)

**Comment by v-saikirang** [comment]
Hi @plakerl,

Thanks for your patience. If possible can you share your email id so we can look in to this over a teams call.
Thanks.
