### ISSUE TITLE
Blue Spinning Circle on app first-run/site creation (& More)

### ISSUE THREAD

**Issue by HubZeb** [OfficeDev/microsoft-teams-apps-champion-management#87]
I have been trying to install 2.0.0.0 on main tenant for a month or so but each time, it stalls on the spinning blue circle (note: I am sharepoint admin for our tenant and fulfil the prerequisites listed on this site; I have also been able to get the same version working correctly on my dev tenant)

(between install attempts, I first remove the app from the Teams admin console and from the App Catalogue, as well as the relevant site collection and API permissions from the SharePoint admin console.  I then wait some time for changes to take effect before trying again)

Every time I run through the deployment guide, it seems to stall _after_ creating the sharepoint site collection, but before (or at the point of) the creation of the lists:

Event Track Details
Events List
Member List

So these three lists never appear in Site Contents

(Note: it _does_ however seem to create the library "Digital Badge Assets")

![image](https://user-images.githubusercontent.com/101109574/157033455-798b9dc7-0c39-44ad-8841-a22a84a38b99.png)

My initial 'fix' for this was to import working lists from my dev tenant (using ShareGate) - this seemed promising, and led to most of the app functionality working, including the creation of additional lists when setting up Tournament of Teams... 

However, two critical issues later presented themselves:

Firstly, we would get an error when trying to apply the digital badge to profile pictures:

_An unexpected error occured while retrieving the digital badges. Below are the details: {"response":{},"status":400,"statusText":"Bad Request","isHttpRequestError":true}_

Secondly, when navigating around the Tournament of Teams options, clicking on Tournament of Teams Status would give the following error:

_An unexpected error occured while getting users. Below are the details: {"errorCode":"consent_required","errorMessage":"AADSTS65001: The user or administrator has not consented to use the application with ID '41bcc5a6-a7a8-458b-b5b3-647dbe4d4372' named 'SharePoint Online Client Extensibility Web Application Principal'. Send an interactive authorization request for this user and resource.\r\nTrace ID: 9e473067-6cf6-4c81-aca2-006d12e30d01\r\nCorrelation ID: 46ec3660-adf2-4c7c-a4d6-09f8d108e2a1\r\nTimestamp: 2022-02-22 13:05:40Z","name":"InteractionRequiredAuthError"}_

there's also a further (more minor) bug where if using the _Dark Theme_ for Teams, adding a new user will format the form entry text as white against a white background (it still works, it's just hard to tell what you're typing) - though this issue was also present on the otherwise-working dev environment.

With all of the above in mind, I uninstalled the app and removed it from Teams/SharePoint entirely, before trying to reinstall it again, only this time with Teams in a web browser and running a HTTP trace during the setup step.

errors in the trace files suggest authentication errors when trying to set the SP lists up, but I cannot identify what is causing this; I have compared and replicated SP settings from live to dev tenant, and nothing has 'broken' the ability to install on the dev tenant.

(I actually now have two sets of HTTP trace logs, which seem to vary slightly in how they error - though they both seem to boil down to authentication between the app and SharePoint)

I'm now not sure what to try next, so any assistance you might be able to lend would be gratefully received

Many thanks

**Comment by HubZeb** [comment]
Hi @v-saikirang 

Sure thing:

API Permissions:
![image](https://user-images.githubusercontent.com/101109574/157045172-5e8b2836-e2f3-4186-bd1d-97eaf7533e67.png)

Console errors (note, I might miss a few lines between image 2 and 3 as there were around three pages worth, but the error for each line was largely the same):
![image](https://user-images.githubusercontent.com/101109574/157046484-0bd4086a-96e7-40a9-8937-73af8194f027.png)
![image](https://user-images.githubusercontent.com/101109574/157046501-640eae30-aa05-43f6-ad96-86ec6e7f1912.png)
![image](https://user-images.githubusercontent.com/101109574/157046518-fd6b2a22-97c6-40a1-ae2c-713d6fe7876d.png)

Thanks

**Comment by v-saikirang** [comment]
Hi @HubZeb,
Thanks for the details.
Can you also try a fresh install by deleting the cmp sitecollection from both "Active Sites" and "Deleted Sites" and repeating the steps. You don't have to delete the API permissions. Please wait for 30 mins after deleting the site.
After "Sync to Teams" open the app in browser and share a screenshot of the console errors.

Thanks.

**Comment by v-saikirang** [comment]
Hi @HubZeb,
Thanks for the detailed log. 
From the logs I see that it says "Site collection already existing". But if you have performed a fresh install and then opened teams it should not say this. Instead it should say "Creating site collection". So can you please confirm these are the logs from the first load after fresh install.
Is the CMP site collection created? If yes, can you try access this URL in a new browser and share a screenshot. Replace with your actual tenant. Can you also check if your account is added in owners group in Share point. 
Thanks.
https://[tenant].sharepoint.com/sites/ChampionManagementPlatform/_api/site/id

**Comment by HubZeb** [comment]
Hi @v-saikirang 

The CMP site collection was created (and creation time matches when I ran the app for the first time) I can confirm that I am both listed as site admin and am in the site owner group for this site collection.

These are the correct logs; I noticed that it said the site collection already existed and thought it odd too, as I had deleted it from active, then from deleted sites, then waited at least an hour before starting the log and running the app.

I've just looked through the log file (previously attached) again, and towards the end of the log, it does actually say that it's creating the site collection:
![image](https://user-images.githubusercontent.com/101109574/157429828-59cd9310-70d8-4d66-a3e5-1f1d5c758a99.png)

...before confirming the creation:
![image](https://user-images.githubusercontent.com/101109574/157430635-30125f43-f52d-46ff-90b4-31dc921d2565.png)

https://[tenant].sharepoint.com/sites/ChampionManagementPlatform/_api/site/id gives the following:
![image](https://user-images.githubusercontent.com/101109574/157430440-a76216fb-0315-4a17-90bc-d7cc55c23f28.png)

One thing I was going to mention previously but it looks like I didn't include... when I first ran the app, I got this popup:
![image](https://user-images.githubusercontent.com/101109574/157431311-de5bb401-7993-433b-8d57-9668843a6987.png)

...I have seen this before on my dev tenant, where refreshing Teams from this would first give another popup which says the user has been granted access, before progressing the creation of the site collection and related lists; the app's UI would then populate with all of the correct icons.  The live tenant does not get this second popup.

Thanks

**Comment by v-saikirang** [comment]
Hi @HubZeb,

It's strange how the logs are showing both the scenarios. Please refresh after some time in a new browser and share the logs. If possible can you please share your email id so we can go over this through a teams call if needed.
Thanks.

**Comment by HubZeb** [comment]
Hi @v-saikirang 

ran again - this one looks more 'normal':

[CMP_RunOnce_110322.log](https://github.com/OfficeDev/microsoft-teams-apps-champion-management/files/8231583/CMP_RunOnce_110322.log)

email is mhubbard@zebra.com (I'll edit this post to delete this line from here once you've confirmed receipt)

Thanks

**Comment by v-saikirang** [comment]
Hi @HubZeb,

As per our trouble shooting sessions below is the summary:
1) Issues with Graph API calls from the application
2) Implemented workarounds to set up and configure the app
3) The Digital Badge is still not working due to graph dependency
4) Once the graph api issue is fixed the Digital Badge should also work.

Since you are already working with support Engineer on a different ticket to fix the Azure Graph APIs issue iam closing this ticket for now. Please let us know if you see any issues.
Thanks.

**Comment by HubZeb** [comment]
some 'close notes', just in case it helps others with the same issue:

Digging into Azure >> App Registrations >> API Permissions for "SharePoint Online Client Extensibility Web Application Principal"...

the Graph API entries _should_ be listed here... on my Dev tenant, these were listed under 'Other Permissions..." (you can commit them to 'Configured Permissions' from here by clicking on the '...' after each listed API):

![image](https://user-images.githubusercontent.com/101109574/159472809-f9dff7cd-690c-4eac-b6c2-2ec6f6433822.png)

However, the live tenant was not showing these permissions at all:

![image](https://user-images.githubusercontent.com/101109574/159473101-33dd36f3-d0c5-4880-b24a-f26241b96f8b.png)

To resolve this, I got myself added to the Application Administrator role (this required the assistance of a global admin):

![image](https://user-images.githubusercontent.com/101109574/159473233-21b9288a-1fa9-46aa-a893-30260594b2af.png)

Once I had this role, I was able to add permissions for the relevant API:

![image](https://user-images.githubusercontent.com/101109574/159473326-a70134e6-b12b-44da-a03f-c64b4d6cdfbb.png)

Once the API are added (1), you then need to grant admin consent (2) and the Status column will be updated to confirm permissions are set.

Once this was done, the Graph-specific parts of the CMP app worked flawlessly

Thanks
