### ISSUE TITLE
App not loading components when added as Personal App in Teams

### ISSUE THREAD

**Issue by ogershun58** [OfficeDev/microsoft-teams-apps-champion-management#88]
We downloaded deployed the package on 2/10/2022. CMP works when used in a tab, but when we try to add it as a personal app - no components are loaded.
![image](https://user-images.githubusercontent.com/100610816/159067285-6ac0c3ee-51ef-4b4b-a571-4ba61453ec66.png)

**Comment by v-saikirang** [comment]
Hi @ogershun58,

Thanks for your patience. May i know if your's is a GCC tenant. We have noticed few issues with GCC tenants.
Thanks.
