### ISSUE TITLE
Platform not loading

### ISSUE THREAD

**Issue by emmamhelm** [OfficeDev/microsoft-teams-apps-champion-management#89]
Hi - We have installed the Champion Management Platform into our teams site, however we are getting the blue ring and it is not going away. We have attempted to re-add the application and that is also not working.

![Screenshot 2022-03-29 132116](https://user-images.githubusercontent.com/102563210/160508464-827ef502-e812-4340-ab48-4b2c369740f3.png)
.

**Comment by v-saikirang** [comment]
Hi @emmamhelm,

Thanks for you patience. I would like to check few things here:
1) Have you used Tenant admin account for loading the app for the first time.
2) Have you approved Graph API permissions in share point admin portal
3) Is the site collection "ChampionManagementPlatform" created. You can check this in admin portal. Also check under "Deleted sites"
4) Can you please open teams in browser and share the console logs when you load the app.

Thanks.

**Comment by v-saikirang** [comment]
Hi @emmamhelm,

Can you please provide the required details.

Thanks.

**Comment by NHSharePointGuy** [comment]
I'm running into the same thing. The 3 MS Graph lines are enabled in API Access but none have a package name. We had installed and removed v1.0. Should we have removed the API Access prior to reinstalling?

**Comment by NHSharePointGuy** [comment]
Our issue is resolved. The original site collection was still in the Deleted sites list. We permanently deleted it and the app finished installing quickly.

**Comment by NHSharePointGuy** [comment]
> I'm running into the same thing. The 3 MS Graph lines are enabled in API Access but none have a package name. We had installed and removed v1.0. Should we have removed the API Access prior to reinstalling?

Our issue was resolved by permanently deleting the old site collection from the Deleted sites recycle bin

**Comment by v-saikirang** [comment]
Hi @emmamhelm,

Thanks for the confirmation. Please note that we have released a new package yesterday in the same link with few fixes and updated features. I suggest you pick up and install the latest package as per upgrade document. Please let me know if you need more information.
Thanks.
