### ISSUE TITLE
App not loading components when added as Personal App in Teams

### ISSUE THREAD

**Issue by SriGutha** [OfficeDev/microsoft-teams-apps-champion-management#9]
The app is not loading the components like Add Members, Digital Badge etc., when added as Personal App in Teams.

![image](https://user-images.githubusercontent.com/3690797/114635279-01875b80-9c8a-11eb-9429-c190718222a3.png)

**Comment by saurabhjatara** [comment]
I have a similar issue
![issuecmp](https://user-images.githubusercontent.com/23356557/115608253-a8f83400-a303-11eb-9a8a-898c48fa1023.JPG)
.

**Comment by karuanag** [comment]
Hello @SriGutha Have you added any Champions to the underlying list?

**Comment by Smitat-msft** [comment]
@SriGutha thanks for being patient while we are trying to fix this.

**Comment by stuartridout** [comment]
> Hello @SriGutha Have you added any Champions to the underlying list?

@karuanag - I have the same issue and I have added Champions.  It's only in the personal app context, not the Teams tab.

**Comment by eshwarmsft** [comment]
This feature is not there in the current version of CMP. Will try to incorporate on the coming versions with the same.

**Comment by eshwarmsft** [comment]
@SriGutha Recent update Champions Management Portal 1.1.0.0 fixed this issue. Please try again with the updated changes.

**Comment by SriGutha** [comment]
@eshwarmsft - Thank you !!
